### ISSUE TITLE
When will v2.2.0 release?

### ISSUE THREAD

**Issue by goace** [apache/rocketmq-client-go#1037]
I wonder when will V2.2 be released?

I really need this version as it fixes a fatal bug for us.

**Comment by naah69** [comment]
So do I!
we need `WithConsumeTimeout`

**Comment by goace** [comment]
@naah69 这个社区感觉已经没人维护了。。

**Comment by francisoliverlee** [comment]
doing this release -_-

**Comment by francisoliverlee** [comment]
https://github.com/apache/rocketmq-client-go/tree/v2.1.2.rc2 is coming, try it
