### ISSUE TITLE
和rocketmq-clients项目的关系是？

### ISSUE THREAD

**Issue by kpvt001** [apache/rocketmq-client-go#1043]
此项目和另一个client的项目https://github.com/apache/rocketmq-clients 的关系是？
**项目中应该使用哪个go client？**

**Comment by pzhx521** [comment]
https://github.com/apache/rocketmq-clients , as known as RocketMQ 5.x SDK.
5. x has significant changes to 4. x and is not directly compatible with each other.
My understanding is that the `rocketmq-clients` project is a new client implementation for `>= 5. x`.
If using version `<= 4. x`, use project `rocketmq-client-go`.

**Comment by francisoliverlee** [comment]
+1
and i will close the issue, any problems, feel free to re-open it.

**Comment by twgcode** [comment]
按照文档: https://rocketmq.apache.org/zh/docs/sdk/01overview 中的意思 这个仓库的 sdk 是可以 使用 服务端 rocketmq 5.x 的？
