### ISSUE TITLE
请问ConsumeMessageBatchMaxSize参数保证每次消费条数吗？

### ISSUE THREAD

**Issue by gzlboy** [apache/rocketmq-client-go#1066]
为何我设置成>1的数，但每次获取到的都是一条？

**Comment by francisoliverlee** [comment]
it works as i tested.
ConsumeMessageBatchMaxSize should be 1 <= ConsumeMessageBatchMaxSize <= 1024

**Comment by bogerv** [comment]
> 这个值只限制获取到的最大数量，并不保证每次获取到指定条数

后面有定位到什么原因吗, 我也有遇到相同的问题, 设置ConsumeMessageBatchMaxSize, 但是消费的时候总是1条数据
