### ISSUE TITLE
According to the information in the documentation (https://rocketmq.apache.org/docs/sdk/01overview), does the SDK in this repository support the usage of RocketMQ 5.x server?

### ISSUE THREAD

**Issue by twgcode** [apache/rocketmq-client-go#1070]
按照文档: https://rocketmq.apache.org/zh/docs/sdk/01overview 中的意思 本仓库的 sdk 是可以 使用 服务端 rocketmq 5.x 的？

**Comment by francisoliverlee** [comment]
golang sdk for 5.X is here : https://github.com/apache/rocketmq-clients/tree/master/golang

**Comment by twgcode** [comment]
> 5.X 的 golang sdk 在这里：[https ://github.com/apache/rocketmq-clients/tree/master/golang](https://github.com/apache/rocketmq-clients/tree/master/golang)


我知道这个仓库 https://github.com/apache/rocketmq-clients/tree/master/golang) 是 用于 5.X 的，但是根据 [文档](https://rocketmq.apache.org/zh/docs/sdk/01overview/)  rocketmq server 5.x 是可以兼容 Remoting 协议的，所以 我可以使用本仓库的 sdk？ 我之前不想使用  https://github.com/apache/rocketmq-clients/tree/master/golang 的原因是  
- 这个仓库 在 README 文件中 他是不推荐在生产环境中使用 （当然最新的README中已经没了）
- 最新的 golang 版本的 tag 是个 `rc` 的(最新的 README 已经没有了 不推荐在生产中使用的说明)，给人的感觉 这个库还不是很稳定

**Comment by cserwen** [comment]
本仓库的 Go SDK 是基于 Remoting 协议实现的，理论上可以访问 5.x 版本（5.x版本支持 Remoting 和 gRPC 协议） @twgcode
