### ISSUE TITLE
新版何时release？严重bug需要等待修复

### ISSUE THREAD

**Issue by kpvt001** [apache/rocketmq-client-go#1072]
目前最新release存在严重bug，已注意到几个月前在master中被修复。由于有要求一定要用release版本，请问何时release？

距离严重bug修复后，不release的时间也太长了。

**Comment by WRAllen** [comment]
+1，这么严重的问题还不发版

**Comment by lihqi** [comment]
+1

**Comment by Yanbuc** [comment]
具体是哪个bug呀

**Comment by HubQin** [comment]
直接用master版

**Comment by lawtech0902** [comment]
哪个bug？

**Comment by yangxiaohui-coll** [comment]
https://github.com/apache/rocketmq-client-go/issues/993 这个bug

**Comment by fuyou001** [comment]
我们尽快发版本。

**Comment by ilaziness** [comment]
这个和另一个客户端https://github.com/apache/rocketmq-clients/tree/master/golang 什么区别？ 都是挂在apache组织下面的，都在更新，就是不同人实现的go客户端？

我按example里面的例子写的，消费两个消息后就不消费了，提示`INFO[0700] [BALANCE-SKIP] since consumer paused`

**Comment by joyzho** [comment]
+1

**Comment by francisoliverlee** [comment]
> 
for rocketmq 5.X: https://github.com/apache/rocketmq-clients/tree/master/golang using grpc
for rocketmq 4.X: https://github.com/apache/rocketmq-client-go using remoting

**Comment by joyzho** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by MyungBice** [comment]
什么时候更新版本啊

**Comment by francisoliverlee** [comment]
v2.1.2 has released by https://github.com/apache/rocketmq-client-go/tree/v2.1.2
