### ISSUE TITLE
请教，在client端设置消息的key-value怎么没在rocketmq-console上体现呀？

### ISSUE THREAD

**Issue by gzlboy** [apache/rocketmq-client-go#1079]
![image](https://github.com/apache/rocketmq-client-go/assets/1492060/19953b5c-976c-4b41-9597-33ae092b90f8)
key和tag看到了，但是设置的demo-key在rocketmq-console中看不到，是rocketmq-console不支持还是什么原因？

**Comment by francisoliverlee** [comment]
try lastest version , this would work
![image](https://github.com/apache/rocketmq-client-go/assets/5908412/86048eed-938c-49ce-9222-fdd311ef07de)

**Comment by 0daypwn** [comment]
你这个问题应该提在 https://github.com/apache/rocketmq-dashboard 

client支持With和Get
https://github.com/apache/rocketmq-client-go/blob/da20ee7b0743a08ecf1fc53403f530b74eea2257/primitive/message.go#L151-L159
