### ISSUE TITLE
Add producer unit test

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#108]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
add producer unit test

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
must-have

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

**Comment by wenfengwang** [comment]
added at https://github.com/apache/rocketmq-client-go/pull/109
