### ISSUE TITLE
producer.SendAsync panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 474903784** [apache/rocketmq-client-go#1102]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b8491e]

goroutine 4896 [running]:
github.com/apache/rocketmq-client-go/v2/internal.(*rmqClient).ProcessSendResponse(0x2658e60?, {0xc001d5dee0?, 0xffffffffffffffff?}, 0x0, 0xc000680470?, {0xc001f540b8?, 0x1?, 0x1?})
        /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.2-0.20230803074138-7eedaf948c60/internal/client.go:730 +0x3e
github.com/apache/rocketmq-client-go/v2/producer.(*defaultProducer).sendAsync.func1(0xc0025c9b60?, {0x26389c0, 0xc000680470})
        /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.2-0.20230803074138-7eedaf948c60/producer/producer.go:411 +0x128
github.com/apache/rocketmq-client-go/v2/internal.(*rmqClient).InvokeAsync.func1(0x1e34160?)
        /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.2-0.20230803074138-7eedaf948c60/internal/client.go:591 +0x2b
github.com/apache/rocketmq-client-go/v2/internal/remote.(*ResponseFuture).executeInvokeCallback.func1()
        /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.2-0.20230803074138-7eedaf948c60/internal/remote/future.go:50 +0x2a
sync.(*Once).doSlow(0xc002c58720?, 0x0?)
        /usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
github.com/apache/rocketmq-client-go/v2/internal/remote.(*ResponseFuture).executeInvokeCallback(0xc0029e7040?)
        /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.2-0.20230803074138-7eedaf948c60/internal/remote/future.go:48 +0x45
github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).receiveAsync(0x1f49ca0?, 0x0?)
        /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.2-0.20230803074138-7eedaf948c60/internal/remote/remote_client.go:139 +0x34
github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).InvokeAsync.func1()
        /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.2-0.20230803074138-7eedaf948c60/internal/remote/remote_client.go:129 +0x2f
github.com/apache/rocketmq-client-go/v2/primitive.WithRecover(0xc000228360?)
        /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.2-0.20230803074138-7eedaf948c60/primitive/base.go:100 +0x3e
created by github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).InvokeAsync
        /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.2-0.20230803074138-7eedaf948c60/internal/remote/remote_client.go:128 +0x20c

**Comment by 474903784** [comment]
![image](https://github.com/apache/rocketmq-client-go/assets/19564665/79d797af-6bc3-4a8a-a5f5-71ef52ad75e9)
err：request timeout

**Comment by cococolanosugar** [comment]
Maybe you need to pass a clean ctx for AsyncPublish function.

**Comment by 474903784** [comment]
miss return when err != nil，so occur panic: runtime error: invalid memory address or nil pointer dereference
