### ISSUE TITLE
update offset to broker success这个日志输出太多

### ISSUE THREAD

**Issue by WRAllen** [apache/rocketmq-client-go#1127]
每次看diamond里面的log，用到mq的pod看日志一次可以打三十几行的：update offset to broker success

![image](https://github.com/apache/rocketmq-client-go/assets/25947700/f1b207ce-b359-4eec-9cab-e9d7dd45b58b)

而且2～3秒一次，日志一下子就被刷掉了，有没有办法降低info为debug，或者不打印这个update offset to broker success

**Comment by zl03jsj** [comment]
```go
"github.com/apache/rocketmq-client-go/v2/rlog"
.....
	rlog.SetLogLevel(logrus.WarnLevel.String())
.....
```
Or you can set the environment `ROCKETMQ_GO_LOG_LEVEL= warn`
