### ISSUE TITLE
2.0.0-alpha2 PushConsumer Shutdown

### ISSUE THREAD

**Issue by banbo** [apache/rocketmq-client-go#130]
2.0.0-alpha2 PushConsumer Shutdown function is just return nil，when can this approach be implemented?
```
func (pc *pushConsumer) Shutdown() error {
	return nil
}
```

**Comment by wenfengwang** [comment]
it will be fixed in next release: 2.0.0-rc1. it will be released at 8.7

**Comment by banbo** [comment]
> it will be fixed in next release: 2.0.0-rc1. it will be released at 8.7

8.7 release still not implement this func, i am wait for this func, the cgo version is not work good

**Comment by wenfengwang** [comment]
the 2.0.0-rc1 has been postponed, we are doing our best for releasing it on 8.14 around.

**Comment by wenfengwang** [comment]
fixed at: https://github.com/apache/rocketmq-client-go/pull/172
