### ISSUE TITLE
Can not compile from the scratch

### ISSUE THREAD

**Issue by jacyo** [apache/rocketmq-client-go#14]
vendor/github.com/apache/rocketmq-client-go/core/push_consumer.go:147:14: could not determine kind of name for C.SetProducerLogFileNumAndSize

vendor/github.com/apache/rocketmq-client-go/core/push_consumer.go:152:14: could not determine kind of name for C.SetProducerLogLevel

vendor/github.com/apache/rocketmq-client-go/core/push_consumer.go:141:14: could not determine kind of name for C.SetProducerLogPath
编译时产生的错误。

**Comment by ShannonDing** [comment]
Got it, it will be fixed in PR #13 .

**Comment by ShannonDing** [comment]
Fixed.
