### ISSUE TITLE
rocketmq-client-go-2.0.0-alpha2 from master branch ?

### ISSUE THREAD

**Issue by pangliang** [apache/rocketmq-client-go#142]
rocketmq-client-go-2.0.0-alpha1 is native branch release, why rocketmq-client-go-2.0.0-alpha2  is master branch release ?

2.0.0 version is native version, i think

I download asset `source.zip` from release, get files:

rocketmq-client-go-2.0.0-alpha2
├── benchmark
│   ├── consumer.go
│   ├── main.go
│   ├── message.go
│   ├── producer.go
│   └── stable.go
├── changelog
├── CONTRIBUTING.md
├── core
│   ├── api.go
│   ├── api_test.go
│   ├── cfuns.go
│   ├── error.go
│   ├── log.go
│   ├── log_test.go
│   ├── message.go
│   ├── message_test.go
│   ├── producer.go
│   ├── producer_test.go
│   ├── pull_consumer.go
│   ├── push_consumer.go
│   ├── push_consumer_test.go
│   ├── queue.go
│   ├── queue_selector.go
│   ├── queue_selector_test.go
│   ├── utils.go
│   ├── version.go
│   └── version_test.go
├── doc
│   └── Introduction.md
├── examples
│   ├── main.go
│   ├── producer.go
│   ├── producer_orderly.go
│   ├── pull_consumer.go
│   └── push_consumer.go
├── LICENSE
├── NOTICE
├── PULL_REQUEST_TEMPLATE.md
└── README.md

**Comment by ShannonDing** [comment]
Sorry for this mistake, I will check this release again and fix it.

**Comment by ShannonDing** [comment]
fixed, Could you please check agian？

**Comment by pangliang** [comment]
good! thanks...
