### ISSUE TITLE
Support Namersrv domain

### ISSUE THREAD

**Issue by wenfengwang** [apache/rocketmq-client-go#147]
The issue tracker is **ONLY** used for the python client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

support namesrv addr of http://xxxx

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

must have

**Comment by ShannonDing** [comment]
good job! now I set the nameserver address to a domain name like "namerserver.xxx.com", it does not work.

**Comment by ShannonDing** [comment]
closed due to #161
