### ISSUE TITLE
Can provide a C++ independent version?

### ISSUE THREAD

**Issue by wangzhipeng** [apache/rocketmq-client-go#16]
如果没有C++经验，感觉第一步就跪在了编译上

**Comment by ShannonDing** [comment]
See the CPP SDK [README](https://github.com/apache/rocketmq-client-cpp/blob/master/README.md), there is a shell to build CPP Core automatically.
and more, if you don't want to build the CPP core, you can download [CPP CORE & C HEAD FILES](https://opensource-rocketmq-client.oss-cn-hangzhou.aliyuncs.com/cpp-client/linux/1.0.2/RHEL7.x/librocketmq.tar.gz).
then copy the library to /usr/local/lib and the head files to /usr/local/include/rocketmq.

**Comment by ddatsh** [comment]
go 之后的版本，看起来还是会提供binary only的编译方式
我再等等

**Comment by gaufung** [comment]
> 如果没有C++经验，感觉第一步就跪在了编译上

I have started **non-official** project for rocketmq-client in go.  If you are interested in this [repo](https://github.com/gaufung/rocketmq), fork it.

**Comment by Liberxue** [comment]
Can I create a new warehouse and develop it with a single go?

**Comment by wenfengwang** [comment]
Because multiple languages are needed to provide, which means controllability and reliability are most important in the official projects. but the cost of a native client is very expensive, you need to implement the private protocol and come up to new feature of rocketmq-java, which need more contributors to maintain native client and more complex codebase, however, most contributors are unstable and complex codebase isn't friendly for potential contributors. so build on cpp language is easy and feasible. IMO, the third-party client in pure go is very welcome, if you interested in the native client, please feel free to create a new repo. but I am strongly recommended you chose official project at first : )!

**Comment by welcome112s** [comment]
####mac:
-  http://zhiliao365.com.cn/mac/librocketmq.a   
- http://zhiliao365.com.cn/mac/librocketmq.so

#### ubuntu
-  http://zhiliao365.com.cn/ubuntu/librocketmq.a  
-  http://zhiliao365.com.cn/ubuntu/librocketmq.so

**Comment by wenfengwang** [comment]
We are planning to make a pure go client,  do please expectation!

**Comment by welcome112s** [comment]
https://github.com/welcome112s/rocketmq-cpp-bin

**Comment by jerry-tao** [comment]
```
Milestone1(due: 2019.3.10)
```
Is it still ongoing?

**Comment by wenfengwang** [comment]
@jerry-tao yes, the workload exceeded our expectations...the alpha version will be released at the end of April or early May

**Comment by jerry-tao** [comment]
@wenfengwang Consider release a version with basic features, so others can create PR or modified by themself.

**Comment by wenfengwang** [comment]
@jerry-tao we are doing this as soon as possiable

**Comment by mumushuiding** [comment]
我在windows下的操作顺序：
0.下载"http://opensource-rocketmq-client-us.oss-us-west-1.aliyuncs.com/cpp-client/windows/1.2.0/rocketmq-client-cpp.lib"和"http://opensource-rocketmq-client-us.oss-us-west-1.aliyuncs.com/cpp-client/windows/1.2.0/rocketmq-client-cpp.dll"并修改名字成rocketmq.lib和rocketmq.dll
1.将rocketmq.lib和rocketmq.dll放到C:\usr\local\lib下
2.go get github.com/apache/rocketmq-client-go
3.进入rocketmq-client-go/examples目录
4.go build
报错：-mingw32/bin/ld.exe: skipping incompatible /usr/local/lib\rocketmq.lib when searching for -lrocketmq
5.set GOOS=linux
6.go build
报错：..\core\api.go:32:20: undefined: LogConfig

真是难，没招了

**Comment by 15332318109** [comment]
undefined: LogConfig 你看下，你是不是配置哪里出了问题。

**Comment by 15332318109** [comment]
现在ROCKETMQ就是在语言上有所限制，相对RABBITMQ还是少，虽然JAVA支持非常好。但是为了社区还是希望能编写些其他语言的版本的client。

**Comment by mumushuiding** [comment]
LogConfig 是core文件下log.go中定义的一个结构
// LogConfig the log configuration for the pull consumer
type LogConfig struct {
	Path     string
	FileNum  int
	FileSize int64
	Level    LogLevel
}

**Comment by wenfengwang** [comment]
please track [2.0.0 Production Ready Road map](https://github.com/apache/rocketmq-client-go/issues/57)
