### ISSUE TITLE
Add ut for defaultConsumer

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#178]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Add ut for defaultConsumer

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

**Comment by ShannonDing** [comment]
For PR #179, the test file consumer/mock_offset_store.go lacks ASF Header, could you please create a new PR and fix it?
