### ISSUE TITLE
How to create a topic?

### ISSUE THREAD

**Issue by ofttryaj** [apache/rocketmq-client-go#182]
I do not find a API to  create a topic by the client?

**Comment by wenfengwang** [comment]
You could use `mqadmin` tools to create a topic, more details here: https://rocketmq.apache.org/docs/cli-admin-tool/

**Comment by ofttryaj** [comment]
@wenfengwang why not provide the API to create topic

**Comment by wenfengwang** [comment]
The Go client will have not to support any admin features, it's not the orientation of Go client

**Comment by ofttryaj** [comment]
Thank you
