### ISSUE TITLE
Repeated consumption problem when changing consumeMessageBatchMaxSize 

### ISSUE THREAD

**Issue by Me1onRind** [apache/rocketmq-client-go#183]
native分支 我给 consumer/option.go增加了一个方法 设置consumeMessageBatchMaxSize
```go
func WithConsumeMessageBatchMaxSize(consumeMessageBatchMaxSize int) Option {
    return func(opts *consumerOptions) {
        opts.ConsumeMessageBatchMaxSize = consumeMessageBatchMaxSize
    }   
}
```
以将consumeMessageBatchMaxSize设置为1为例，启动后使用后没有什么问题,但是发现如果在不启动
```go
consumer.WithConsumerOrder(true)
```
的情况下，写入offset.json文件的 offset偏移量每次都只+1或者不变, 从而导致重启的时候会消费一些已经消费过的历史消息。 同时消费端还会丢一两条数据。集群模式下远程维护offset也会有这个问题。

使用的操作系统是centos7, 单机测试, 一个消费进程，一个推送进程每次推送10条消息入同一个queue。
自己简单看了下代码似乎是因为非顺序消费时, offset比较大的消息先被消费, offset小的后被消费,而这两种情况更新offset时都是更新最小的被顺序消费的消息的offset
consumeMessageBatchMaxSize相对每次pull下来的消息个数较小时就会发生, 如果是开启顺序消费则没有这个问题。
不过,我不确定这是否是一个问题。

**Comment by ShannonDing** [comment]
Offset update method was modified by # 187, could you please check again in your env?

**Comment by Me1onRind** [comment]
It isn't solve the problem.  There is my simple demo:
https://github.com/Me1onRind/rocketmq-demo
You can keep comsumer.go running. Every time go run product.go,  will send 10 messages.
In my env,  the consumer can't consume 10 messages every time and check the local offset.json, the offset is wrong.  By the way, you need add consumeMessageBatchMaxSize in rocketmq-client-go's code(consumer/option.go).
```go
func WithConsumeMessageBatchMaxSize(consumeMessageBatchMaxSize int) Option {
    return func(opts *consumerOptions) {
        opts.ConsumeMessageBatchMaxSize = consumeMessageBatchMaxSize
    }   
}
```

**Comment by Me1onRind** [comment]
I think I find the reason and I create a pull request
https://github.com/apache/rocketmq-client-go/pull/206

**Comment by ShannonDing** [comment]
close due to #206
