### ISSUE TITLE
Internal package in go

### ISSUE THREAD

**Issue by ofttryaj** [apache/rocketmq-client-go#184]
When I use rocketmq-client-go `internal` package, go will complain that use of internal package `github.com/apache/rockemq-client-go/internal/utils` not allowed

**Comment by wenfengwang** [comment]
What's scenario you want to use internal/utils? in common, the internal should not be used by external.

**Comment by ofttryaj** [comment]
`examples/consumer/pull/main.go`, this example use the `github.com/apache/rockemq-client-go/internal/utils` at line 49

**Comment by wenfengwang** [comment]
@ofttryaj it's our mistake, we will fix it

**Comment by wenfengwang** [comment]
fixed at https://github.com/apache/rocketmq-client-go/pull/199

**Comment by ShannonDing** [comment]
close due to #199
