### ISSUE TITLE
v2.0.0-alpha2 /examples/consumer/retry/concurrent/main.go retryLevel 1 comment error

### ISSUE THREAD

**Issue by chuyuqiao** [apache/rocketmq-client-go#185]
![image](https://user-images.githubusercontent.com/14037300/64403426-1f064380-d0ab-11e9-8f95-61c1c924660b.png)
the right is that mean 1s later before consume

**Comment by ShannonDing** [comment]
It will be fixed in the next release.

**Comment by wenfengwang** [comment]
fixed at https://github.com/apache/rocketmq-client-go/pull/200

**Comment by ShannonDing** [comment]
close due to #200
