### ISSUE TITLE
OffsetStore differ from java impl

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#186]
**BUG REPORT**

1. Please describe the issue you observed:
In impl, OffsetTable type is map[string]map[int]*queueOffset, which mean topic -> queueId -> offset, but actually, we maybe get queue1 on broker1 and broker2 if we deploy 10 queue on 3 broker. so  OffsetTable impl is wrong.
in Java, offsetTable type is ConcurrentMap<MessageQueue, AtomicLong>, so there is no problem.

**Comment by ShannonDing** [comment]
Yes, you are right, it is possible that there is the same queue id in different brokers. the offset table should be at least a three-dimensional vector that like brokername->queueid->offset.
