### ISSUE TITLE
Refactor MessageSelector

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#192]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
use MessageQueue is better

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

**Comment by ShannonDing** [comment]
According to #187, there may be the same queue id in different brokers, using MessageQueue info for routing will be better.

**Comment by ShannonDing** [comment]
close due to #193
