### ISSUE TITLE
[native]PushConsumer clustering does not auto create %RETRY% topic

### ISSUE THREAD

**Issue by wolftankk** [apache/rocketmq-client-go#194]
It has 2 problems:

1. topic has created, but client say not exists.
2. it's not auto creating a group.

```
INFO[0000] the consumerGroup=go-auto-create-group start beginning. messageModel=Clustering, unitMode=false 
WARN[0000] do balance of group: go-auto-create-group, but topic: RECHARGE_MOBILE does not exist. 
WARN[0000] do balance of group: go-auto-create-group, but topic: %RETRY%go-auto-create-group does not exist.

WARN[0000] query topic route from server error: topic not exist 
the topic=%RETRY%go-auto-create-group route info not found, it may not exist
exit status 255
```

**Comment by wolftankk** [comment]
Ahhhhhhha....

I found a magic method.

1. consumer not using consumer.Clustering, and launch.

2. change code, reusing  consumer.Clustering

3. launch!

It's woking OK!!

**Comment by ShannonDing** [comment]
There is probably a bug, could you please check more detail and fix it if it's a bug?

**Comment by wolftankk** [comment]
hmm, Maybe the code triggers this problem.

github.com/apache/rocketmq-client-go/consumer/push_consumer.go:151

```go
	pc.client.UpdateTopicRouteInfo()
	for k := range pc.subscribedTopic {
		_, exist := pc.topicSubscribeInfoTable.Load(k)
		if !exist {
			pc.client.Shutdown()
			return fmt.Errorf("the topic=%s route info not found, it may not exist", k)
		}
	}
```

I retry more times, find a solution.

1. [FIRST TIME] use a new group (with clustering). use c.Start(). catch a error. 
```
the topic=%RETRY%go-auto-create-group7 route info not found, it may not exist
```

ctrl - c .

2. [SECOND TIME] run c.Start(). catch a error
```
INFO[0000] the topic [%RETRY%go-auto-create-group8] route info changed, old <nil> ,new {"OrderTopicConf":"","queueDatas":[{"brokerName":"iz8vbahalty0z0999g241tz","readQueueNums":1,"writeQueueNums":1,"perm":6,"topicSynFlag":0}],"brokerDatas":[{"cluster":"DefaultCluster","brokerName":"iz8vbahalty0z0999g241tz","brokerAddrs":{"0":"10.100.1.178:10911"}}]} 
INFO[0000] receive broker's notification, the consumer group: go-auto-create-group8 

ERRO[0000] fetch offset of MessageQueue [topic=RECHARGE_MOBILE, brokerName=iz8vbahalty0z0999g241tz, queueId=0] error: broker response code: 22, remarks: Not found, V3_0_6_SNAPSHOT maybe this group consumer boot first 
```

3. [THIRD TIME] run c.Start(). it's working.

**Comment by dreaminglwj** [comment]
the same promblem for me when using on ali cloud,
for me:
1.everything ok on public network
2.never succeed on ali interal network  --- at last i tried this "and MUST wait 10 seconds." and it works

**Comment by wolftankk** [comment]
It does not seem to work.

**Comment by zenghur** [comment]
I came across the same problem. But I fixed it by using WithNamespace:-)

**Comment by wolftankk** [comment]
> I came across the same problem. But I fixed it by using WithNamespace:-)

You need a new group name. The old group name maybe auto creates.

**Comment by ShannonDing** [comment]
link #258

**Comment by wenfengwang** [comment]
It seems to be resolved, is there any update?

**Comment by qshuai** [comment]
> I came across the same problem. But I fixed it by using WithNamespace:-)

What is the default namespace?

**Comment by dreaminglwj** [comment]
您好，您的邮件已收到，我会尽快查看，^_^

**Comment by lixianmin** [comment]
最新版本 	github.com/apache/rocketmq-client-go/v2 v2.1.3-0.20250427084711-67ec50b93040

还在报这种错: WARN[0000] do balance of group: go-auto-create-group, but topic: %RETRY%go-auto-create-group does not exist.
