### ISSUE TITLE
[native]offset has been rising while go client running

### ISSUE THREAD

**Issue by kelly6** [apache/rocketmq-client-go#201]
I start 12 go consumers(simple/main.go), then I run `sh mqadmin consumerProgress -n 'x.x.x.x:9876' -g group_name` to check the consume stat.

Consume TPS looks fine.
But "Diff Total" has been rising rather than falling.
RocketMq-console-ng has the same problem.

like this:
`Consume TPS: 25228.600000000002
Diff Total: 7118856919`
`Consume TPS: 27406.566666666666
Diff Total: 7119656287`
`Consume TPS: 27304.166666666668
Diff Total: 7119700399`

cpp client and java client don't have this problem, everything is fine. So I guess that offset in go client maybe wrong.

**Comment by ShannonDing** [comment]
Is it the latest code?
Could you please share more detail info about your test env?
info log of the updating offset is better.

**Comment by kelly6** [comment]
Sorry, my mistake. I new a consumer without consumer.Clustering option. Default model is BroadCasting.

**Comment by ShannonDing** [comment]
IMO, it is better to change the default model to Clustering.
and it will be disscussed later.

**Comment by kelly6** [comment]
> IMO, it is better to change the default model to Clustering.
> and it will be disscussed later.

I agree with that.

**Comment by ShannonDing** [comment]
@kelly6  PR #208 is merged, Could you please test it again in your env?

**Comment by kelly6** [comment]
> @kelly6 PR #208 is merged, Could you please test it again in your env?

offset goes fine now.

**Comment by ShannonDing** [comment]
close this issue due to #208 .
