### ISSUE TITLE
[native]Send trace message to broker error with acl.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq-client-go#202]
1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
Let broker open ACL
    - What did you expect to see?
Send trace message to broker success with ACL.
    - What did you see instead?
failed
2. Please tell us about your environment:

     - What is your OS?
macOS mojave 10.14.6
     - What is your client version?
latest
     - What is your RocketMQ version?
4.5.2
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

in fuc newTraceInterceptor, lack of acl set.

**Comment by xujianhai666** [comment]
LGTM

**Comment by ShannonDing** [comment]
refer to #240

**Comment by ShannonDing** [comment]
close due to #240
