### ISSUE TITLE
[native]use it with govendor

### ISSUE THREAD

**Issue by dreaminglwj** [apache/rocketmq-client-go#204]
how to use native branch with govendor?

**Comment by liangyuanpeng** [comment]
i run main.go from native branch


but i got some error 


lanrendeMacBook-Pro:examples lanren$ go run main.go
# github.com/apache/rocketmq-client-go/core
../core/cfuns.go:22:10: fatal error: 'rocketmq/CMessageExt.h' file not found
#include <rocketmq/CMessageExt.h>
^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

any help?

**Comment by xujianhai666** [comment]
> i run main.go from native branch
> 
> but i got some error
> 
> ```
> lanrendeMacBook-Pro:examples lanren$ go run main.go
> # github.com/apache/rocketmq-client-go/core
> ../core/cfuns.go:22:10: fatal error: 'rocketmq/CMessageExt.h' file not found
> #include <rocketmq/CMessageExt.h>
> ^~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> any help?

@liangyuanpeng  From my experience, we always modify vendor.json under vendor dir, But, that is dangerous if upgrade wihtout care. By the way, go mod support smooth migaration from govendor
