### ISSUE TITLE
[native]To supply an inner message queue selector by hash(args) as java.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq-client-go#209]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
now the SDK allowed the user to add manual selector,
It is better to supply an inner message queue selector by hash(args) as java.

**Comment by xujianhai666** [comment]
@ShannonDing I thought that is extra method. With golang, we could pass arg in ctx, and get arg from ctx, so the target is finished.

**Comment by ShannonDing** [comment]
close due to #249
