### ISSUE TITLE
[native]how to set requirebu go mod for native branch.

### ISSUE THREAD

**Issue by 2547409617** [apache/rocketmq-client-go#229]
github.com/apache/rocketmq-client-go v2.0.0-alpha1
github.com/apache/rocketmq-client-go v2.0.0-alpha2
both fail:
 require github.com/apache/rocketmq-client-go: version "v2.0.0-alpha2" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

**Comment by wolftankk** [comment]
github.com/apache/rocketmq-client-go 2.0.0-alpha1
github.com/apache/rocketmq-client-go 2.0.0-alpha2

This version is git tag.

**Comment by 2547409617** [comment]
请问一下go mod 里面如何使用呢？
文档里面是github.com/apache/rocketmq-client-go v2.0.0-alpha1

**Comment by wolftankk** [comment]
```
require (
github.com/apache/rocketmq-client-go 2.0.0-alpha1
)
```

like this.

**Comment by 2547409617** [comment]
it work
