### ISSUE TITLE
[native]panic send message

### ISSUE THREAD

**Issue by wolftankk** [apache/rocketmq-client-go#231]
(PANIC=String method: runtime error: invalid memory address or nil pointer dereference), error:[TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 201ms, size of queue: 60

**Comment by ShannonDing** [comment]
Could you please share more detail logs?

**Comment by xujianhai666** [comment]
“broker busy” message comes from broker. Is there any enough panic info ?

**Comment by xujianhai666** [comment]
@wolftankk “broker busy” message comes from broker. Is there any enough panic info ?

**Comment by wolftankk** [comment]
> @wolftankk “broker busy” message comes from broker. Is there any enough panic info ?

I will try to get more detail.
