### ISSUE TITLE
[Native]route info not found

### ISSUE THREAD

**Issue by dreaminglwj** [apache/rocketmq-client-go#233]
The issue tracker is **ONLY** used for the go client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
	EnrollProducer, err = rocketmq.NewProducer(
		producer.WithNameServer([]string{Conf.RocketmqInstanceProdTrade.TcpPoint}),
		producer.WithGroupName(Conf.RocketmqTopicEnroll.GroupId),
		producer.WithRetry(1),
		producer.WithCredentials(primitive.Credentials{
			AccessKey: Conf.RocketmqInstanceProdTrade.AkId,
			SecretKey: Conf.RocketmqInstanceProdTrade.AkSecret,
		}),
		// producer.WithConsumerOrder(true),
		producer.WithNamespace(Conf.RocketmqInstanceProdTrade.InstanceId),
		// producer.WithQueueSelector(s) // 用于自定义路由，选择往哪个队列里面添加消息
	)

msg := primitive.NewMessage(conf.Conf.RocketmqTopicEnroll.TopicName, msgBody)
				msg.WithTag(conf.Conf.RocketmqTopicEnroll.Tag)

				res, err := conf.EnrollProducer.SendSync(context.Background(), msg)
				if err != nil {
					logrus.Errorf("send message error: %s\n", err)
				} else {
					logrus.Infof("send message success: result=%s\n", res.String())
				}

    - What did you expect to see?
{"level":"error","msg":"send message error: topic=xxx%topic-enroll route info not found\n","time":"2019-10-03T13:25:40+08:00"}
{"level":"error","msg":"send message error: topic=xxx%topic-enroll route info not found\n","time":"2019-10-03T13:37:32+08:00"}
{"level":"error","msg":"send message error: topic=xxx%topic-enroll route info not found\n","time":"2019-10-03T13:39:59+08:00"}
{"level":"error","msg":"send message error: topic=xxx%topic-enroll route info not found\n","time":"2019-10-03T13:56:19+08:00"}

    - What did you see instead?

2. Please tell us about your environment:

     - What is your OS?

     - What is your client version?

     - What is your RocketMQ version?

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

    - [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
    - [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
    - ...

**Comment by dreaminglwj** [comment]
did the native branch send heart beat automatically ?

**Comment by xujianhai666** [comment]
> did the native branch send heart beat automatically ?



> did the native branch send heart beat automatically ?

@dreaminglwj yes

**Comment by xujianhai666** [comment]
@dreaminglwj did u call `EnrollProducer.Start()`?

**Comment by xujianhai666** [comment]
> did the native branch send heart beat automatically ?

@dreaminglwj I reproduce this problem when topic is not created. so maybe `conf.Conf.RocketmqTopicEnroll.TopicName` is not created

**Comment by wenfengwang** [comment]
@dreaminglwj Does the question resolved? if not, is there any update?

**Comment by wenfengwang** [comment]
close due to inactive
