### ISSUE TITLE
[Native]need help to use multiple consumer

### ISSUE THREAD

**Issue by yiitz** [apache/rocketmq-client-go#234]
I use the native version with two consumer(same group) but cannot work expected, the consumer lose some messages and both receive a same message(clustering mode)

**Comment by xujianhai666** [comment]
@yiitz  pls add WithGroupName(groupName) and WithInstanceName(instanceName) for client start.

**Comment by ShannonDing** [comment]
link #242

**Comment by ShannonDing** [comment]
@yiitz plz have a try on #242

**Comment by ShannonDing** [comment]
close due to #242
