### ISSUE TITLE
[master]could not determine kind of name for C.CreateOrderlyProducer

### ISSUE THREAD

**Issue by soWill666** [apache/rocketmq-client-go#235]
# github.com/apache/rocketmq-client-go/core
../../../pkg/mod/github.com/apache/rocketmq-client-go@v1.2.2/core/producer.go:81:14: could not determine kind of name for C.CreateOrderlyProducer
../../../pkg/mod/github.com/apache/rocketmq-client-go@v1.2.2/core/producer.go:284:18: could not determine kind of name for C.SendMessageOrderlyByShardingKey

go version go1.13 darwin/amd64

**Comment by ShannonDing** [comment]
Hi, the newly added feature "SendMessageOrderlyByShardingKey" will be supported by CPP kernel 1.2.4. recently, you can build the latest CPP code by build.sh script to use this feature.

**Comment by ShannonDing** [comment]
link #232

**Comment by soWill666** [comment]
thanks.
