### ISSUE TITLE
[Native] receiveResponse use to many memory

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#252]
**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

with lots of client, each client connect to every broker, connection use bufio.scanner with big memory, which will waste lots of memory, use bufio.reader is better, 

2. Please tell us about your environment:

     - What is your OS?

     - What is your client version?

     - What is your RocketMQ version?

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by ShannonDing** [comment]
link #256

**Comment by ShannonDing** [comment]
close due to #255
