### ISSUE TITLE
[Master] ReConsumeLater doesn't work as expected.

### ISSUE THREAD

**Issue by zenghur** [apache/rocketmq-client-go#257]
1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?

      Use CommonProducer model to produce a common message and receive the message. Then 
          "ReConsumeLater" the message.

    - What did you expect to see?

       I would see the message again.

    - What did you see instead?

      The message has gone.

2. Please tell us about your environment:

     - What is your OS?
     
        Ubuntu 16.04

     - What is your client version?
     
       f73c8d2cd6654d6b791f902ae77d758da21a330f

     - What is your RocketMQ version?

       rocketmq-client-cpp: 9fa724eadfc78b61220ca4bdb314db45ecc830d5
       aliyun rocketmq instance

**Comment by ShannonDing** [comment]
could you please share the log?

**Comment by zenghur** [comment]
> could you please share the log?

There is no log. Returning `ReConsumeLater` behaves like returning `ConsumeSuccess` and I haven't seen the message again.

**Comment by zengxiaobai** [comment]
you may try message model with CLUSTER model, I have met this case with BroadCaster.  But maxReconsumeTimes cannot be support until you modify rocketmq-client-cpp with version upper than 3.5.1 and  carring the maxReconsumeTimes to broker.

**Comment by wenfengwang** [comment]
> you may try message model with CLUSTER model, I have met this case with BroadCaster. But maxReconsumeTimes cannot be support until you modify rocketmq-client-cpp with version upper than 3.5.1 and carring the maxReconsumeTimes item to broker.

@zenghur does the reply resolve your problem?

**Comment by ShannonDing** [comment]
ping @zenghur

**Comment by ShannonDing** [comment]
close due to timeout.
