### ISSUE TITLE
[Native]i want know the branch v2.0.0-alpha2  which time can use prod

### ISSUE THREAD

**Issue by hanzhonghua0927** [apache/rocketmq-client-go#264]

**Comment by hanzhonghua0927** [comment]
Hi, when will this branch (v2.0.0-alpha2) be available in production ?

**Comment by wenfengwang** [comment]
no specific date, it depends on testing progress.

**Comment by hanzhonghua0927** [comment]
> no specific date, it depends on testing progress.

thank you ,  Does the master branch have this function ? ( consumeFromWhere)

**Comment by ShannonDing** [comment]
> > no specific date, it depends on testing progress.
> 
> thank you , Does the master branch have this function ? ( consumeFromWhere)

CONSUME_FROM_LAST is the default value.
others such as CONSUME_FROM_FIRST and CONSUME_FROM_TIMESTAMP will not be supported later.

**Comment by wenfengwang** [comment]
@hanzhonghua0927 The 2.0.0-alpha3 has been released, welcome to have a try : ) https://github.com/apache/rocketmq-client-go/releases/tag/v2.0.0-alpha3

**Comment by wenfengwang** [comment]
close due to duplicated: https://github.com/apache/rocketmq-client-go/issues/57
