### ISSUE TITLE
[master] It will not throw exception when producer or consumer missing model

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq-client-go#268]
The issue tracker is **ONLY** used for the go client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
       Create producer or consumer missing model (ConsumerModel、ProducerModel)

    - What did you expect to see?
      Throw exception

    - What did you see instead?
       It will not throw exception.

**Comment by ShannonDing** [comment]
link #269
