### ISSUE TITLE
[master] Subscribe multiple topics no effect

### ISSUE THREAD

**Issue by sonicrang** [apache/rocketmq-client-go#270]
I have a consumer and sub two diff topic with diff tag.
Logs show that two topic was sub succeed
But when the secend topic is sub，the first topic is unsub (in alicloud console)
How to deal with the problem
![image](https://user-images.githubusercontent.com/5936153/67748982-17d63300-fa67-11e9-9857-9b89bf1a725b.png)

![image](https://user-images.githubusercontent.com/5936153/67749668-997a9080-fa68-11e9-87cc-5c49a6fd0fd6.png)

![image](https://user-images.githubusercontent.com/5936153/67749703-a6977f80-fa68-11e9-93b4-fad05a7dfbdb.png)

![image](https://user-images.githubusercontent.com/5936153/67749738-badb7c80-fa68-11e9-9667-8947cd355d2f.png)

**Comment by ShannonDing** [comment]
Hi, I find your try to connect the aliyun service, did you install the latest CPP core in the official link?

**Comment by sonicrang** [comment]
Thx for reply. Of course I start up this work follow this repo's doc step by step. But I use bin file directly.

http://mirrors.tuna.tsinghua.edu.cn/apache/rocketmq/rocketmq-client-cpp/1.2.3/rocketmq-client-cpp-1.2.3-bin-release.tar.gz

**Comment by sonicrang** [comment]
Thx again. I will try it.

**Comment by wongxinjie** [comment]
> Hi, I find your try to connect the aliyun service, did you install the latest CPP core in the official link?

Can I use native version without install the lastest CPP core??

**Comment by sonicrang** [comment]
@ShannonDing Hi, I've tried like you say. It's ok now.
