### ISSUE TITLE
[native]start multiple consumer in one process, or subscribe multiple topic in one consumer couldn't work.

### ISSUE THREAD

**Issue by wongxinjie** [apache/rocketmq-client-go#271]
1. Please describe the issue you observed:
    - What did you do (The steps to reproduce)?
I create a consumer  using Aliyun RocketMQ service, if I just subscribe one topic in one consumer or start one consumer in one process, it works normally. But when it comes to subscribe multiple topics in one consumer or start multiple consumers in one process, it just prints the starting log and hangs.
    - What did you expect to see?
Subscribe multiple topics could work normally.

    - What did you see instead?

2. Please tell us about your environment:

     - What is your OS?
ubuntu 18.04

     - What is your client version?
native
     - What is your RocketMQ version?
lastest

**Comment by ShannonDing** [comment]
link #242

**Comment by wongxinjie** [comment]
> link #242

nope, I try but the PR didn't fix the bug.

**Comment by wolftankk** [comment]
> > link #242
> 
> nope, I try but the PR didn't fix the bug.

In the RocketMQ admin `consumer` page, u try to find where this group is in?  and detail log for it.

**Comment by xujianhai666** [comment]
strange, I run native version online, everything is okay. could u write an example for us? thx a lot

**Comment by xujianhai666** [comment]
strange, I run native version online, everything is okay. could u write an example for us? thx a lot @wongxinjie

**Comment by wenfengwang** [comment]
I reproduce the situation and found many unexpected cases of below

## Subscribe 2 topics in a consumer
Case 1: nothing received, maybe hang
Case 2: received  only one topic messages, another can't receive
Case 3: all received.

## Start 2 consumers in a process
Case 4: one consumer received and another not
Case 5: one consumer received and another not, and broker response to Code: 24
![image](https://user-images.githubusercontent.com/9766821/69343340-6c588100-0ca8-11ea-99ce-e404ca70c5f6.png)

Case 6: all can't receive messages

**Comment by wenfengwang** [comment]
> I reproduce the situation and found many unexpected cases of below
> 
> ## Subscribe 2 topics in a consumer
> Case 1: nothing received, maybe hang
> Case 2: received only one topic messages, another can't receive
> Case 3: all received.
> 
> ## Start 2 consumers in a process
> Case 4: one consumer received and another not
> Case 5: one consumer received and another not, and broker response to Code: 24
> ![image](https://user-images.githubusercontent.com/9766821/69343340-6c588100-0ca8-11ea-99ce-e404ca70c5f6.png)
> 
> Case 6: all can't receive messages

I will try to fix these

**Comment by wenfengwang** [comment]
fixed at: https://github.com/apache/rocketmq-client-go/pull/310

**Comment by wenfengwang** [comment]
@wongxinjie In RocketMQ, it is not allowed that create multiple consumers have the same `consumerGroup` in one client Instance。If you want to create multiple consumers have the same `consumerGroup` in one process, you should make sure for unique [ClientID](https://github.com/apache/rocketmq-client-go/blob/native/internal/client.go#L330) by calling [WithInstance](https://github.com/apache/rocketmq-client-ACgo/blob/native/consumer/option.go#L176) when create consumer instance. 

After fixing, it may work well that subscribe multiple topics in one consumer and create multiple consumers that have different `consumerGroup` in one client instance, welcome have a test :)
