### ISSUE TITLE
[Native] Bug of SearchOffsetByTimestamp 

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#281]
**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

code of SearchOffsetByTimestamp is 29, and timestamp param is mills instead of seconds.

2. Please tell us about your environment:

     - What is your OS?

     - What is your client version?

     - What is your RocketMQ version?

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by wenfengwang** [comment]
fix at https://github.com/apache/rocketmq-client-go/pull/282
