### ISSUE TITLE
 [Native][bug]nil map in buildSubscriptionData

### ISSUE THREAD

**Issue by hhtlxhhxy** [apache/rocketmq-client-go#287]
The issue tracker is **ONLY** used for the go client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

> panic: assignment to entry in nil map
`goroutine 7 [running]:
github.com/apache/rocketmq-client-go/consumer.buildSubscriptionData(0xc0002f4ca5, 0x9, 0x48cce78, 0x3, 0x48cd989, 0x4, 0xc00003c0c0)
	/go/pkg/mod/github.com/apache/rocketmq-client-go@v0.0.0-20190719094155-f38894a34ad4/consumer/consumer.go:929 +0x2a3
github.com/apache/rocketmq-client-go/consumer.(*pushConsumer).Subscribe(0xc000287480, 0xc0002f4ca5, 0x9, 0x48cce78, 0x3, 0x48cd989, 0x4, 0x4903a80, 0x4030491, 0x4903a90)
	/go/pkg/mod/github.com/apache/rocketmq-client-go@v0.0.0-20190719094155-f38894a34ad4/consumer/push_consumer.go:190 +0x112`

2. Please tell us about your environment:

     - What is your OS?
MacOS

     - What is your client version?
rocketmq-client-go@v0.0.0-20190719094155-f38894a34ad4
     - What is your RocketMQ version?
rocketmq-all-4.5.2 

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
![image](https://user-images.githubusercontent.com/13634428/68119628-22e50380-ff3e-11e9-9ee2-9ed7c4da18b2.png)

when the ms.Type is TAG and the ms.Expression is not "*", the process panic for nil map

**Comment by wenfengwang** [comment]
the bug was fixed at https://github.com/apache/rocketmq-client-go/pull/181, it works well in the latest code of native branch, could you have a try?
