### ISSUE TITLE
[Native]How can I disable the log out put?

### ISSUE THREAD

**Issue by hhtlxhhxy** [apache/rocketmq-client-go#288]
![image](https://user-images.githubusercontent.com/13634428/68120487-78baab00-ff40-11e9-8a1f-da53d468bd10.png)

As you see, I have my log frame in use ,how can I disable the log output in rocketmq-client-go?

**Comment by wenfengwang** [comment]
@hhtlxhhxy Hi, we have added the `SetLogger` for go-client, you could set your customized `Logger` Object. in general, we suggest users replace the default logger with specified, but you want to use default anyway, you can set log level by use env parameter: `export ROCKETMQ_GO_LOG_LEVEL=error`. please see PR: https://github.com/apache/rocketmq-client-go/pull/290/files for detail.
