### ISSUE TITLE
C.NOT_SUPPORT_NOW && C.PRODUCER_SEND_TRANSACTION_FAILED

### ISSUE THREAD

**Issue by BoBoGithub** [apache/rocketmq-client-go#289]
安装完后 执行某个实例时 提示如下错误，请问则个是什么问题 谢谢！

bobo@ubuntu:test$ go run T004.go 
\# github.com/apache/rocketmq-client-go/core
../github.com/apache/rocketmq-client-go/core/error.go:42:35: could not determine kind of name for C.NOT_SUPPORT_NOW
../github.com/apache/rocketmq-client-go/core/error.go:37:40: could not determine kind of name for C.PRODUCER_SEND_TRANSACTION_FAILED

**Comment by ShannonDing** [comment]
did you use the code in master? These two C enums are newly added.
you can use the v1.2.4 instead.

**Comment by BoBoGithub** [comment]
@ShannonDing 谢谢你的回复；切换到v1.2.4分支后 这个两个C enums错误好了，消息能正常发出 并被成功消费，但是执行完后报了个异常 如下图：

![2019-11-07 10-43-16屏幕截图](https://user-images.githubusercontent.com/4011103/68355821-711b2200-014b-11ea-8a02-49a91b1fec8a.png)

**Comment by ShannonDing** [comment]
这个是发现的已知问题，CPP内核里实现的shutdown是异步的， 这里在shutdown之后直接将实例destroy了，会抛出段错误。 
你可以在使用时先临时把shutdown producer注释掉规避一下。

**Comment by BoBoGithub** [comment]
收到
