### ISSUE TITLE
[Native]TopicTest route info not found?

### ISSUE THREAD

**Issue by hhtlxhhxy** [apache/rocketmq-client-go#292]
1、the client version 4364ebd190588b4a40963182495318002b03e63a, when I try to produce message to broker, I got the error
![image](https://user-images.githubusercontent.com/13634428/68444347-8eb2bf00-0211-11ea-97c6-391adab12fe0.png)
 
the producer code below
![image](https://user-images.githubusercontent.com/13634428/68444419-b43fc880-0211-11ea-8807-88e1a87b95b6.png)

but........

when I change the version to f38894a34ad47549dd55230918c3657011bb1a43, producer works ok!!!
![image](https://user-images.githubusercontent.com/13634428/68444691-8eff8a00-0212-11ea-939e-5cc93aea6a13.png)

the producer code below
![image](https://user-images.githubusercontent.com/13634428/68444704-9c1c7900-0212-11ea-8daf-aa44570d1c24.png)

**Comment by wenfengwang** [comment]
@hhtlxhhxy Do you have retry on 4364ebd?

**Comment by wenfengwang** [comment]
@hhtlxhhxy I can't reproduce the same situation on 4364ebd, if you reproduce it, please provide more details and reopen the issue, : )
