### ISSUE TITLE
[Native] [Bug] rmqClient close

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#293]
**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
    rmqClient use `close bool` to represent the current status, but there are many goroutines run for rmqClient, which means race condition, sometimes `close ` will miss for some goroutine. 
    we observe sometimes partitions are blocked without any consuming, we doubt `close` is the murderer.

    - What did you expect to see?
close should be chan for really close.
    - What did you see instead?

2. Please tell us about your environment:

     - What is your OS?

     - What is your client version?

     - What is your RocketMQ version?

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by wongxinjie** [comment]
We also encountered this problem, "io ReadFull error".
