### ISSUE TITLE
[native][bug] io ReadFull error

### ISSUE THREAD

**Issue by wongxinjie** [apache/rocketmq-client-go#294]
1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
even using the example/simple code, but comment the flowing line
 ``` 
time.Sleep(time.Hour) 
``` 
there will always "io ReadFull error" error reports  

    - What did you expect to see?
graceful shutdown, no error reports if shutdown successfully.

2. Please tell us about your environment:

     - What is your OS? ubuntu18.04

**Comment by wenfengwang** [comment]
reproduce when exiting producer sometimes:
![image](https://user-images.githubusercontent.com/9766821/69342084-c3108b80-0ca5-11ea-804e-f82b87c43467.png)

**Comment by wenfengwang** [comment]
https://github.com/apache/rocketmq-client-go/pull/308
