### ISSUE TITLE
[Master]client-cpp version is not match client-go version, how to choose?

### ISSUE THREAD

**Issue by whk-isat** [apache/rocketmq-client-go#296]
I build rocketmq-client-cpp release-1.2.3, 
when I use rocketmq-client-go maste, I build my project error like :
![image](https://user-images.githubusercontent.com/31062226/68465173-e91d4100-024c-11ea-9397-e8986411b3f2.png)

when I use rocketmq-client-go v1.2.4, error like :
![image](https://user-images.githubusercontent.com/31062226/68465246-0d791d80-024d-11ea-9539-df329c84b383.png)

when I use rocketmq-client-go v1.2.2, error like :
![image](https://user-images.githubusercontent.com/31062226/68465278-2386de00-024d-11ea-95d4-399044f170e3.png)

how to do with these error? 
what is the version mapping between  rocketmq-client-cpp and  rocketmq-client-go?

**Comment by whk-isat** [comment]
when I use rocketmq-client-go v1.2.2, error like :
![image](https://user-images.githubusercontent.com/31062226/68463999-b5d9b280-024a-11ea-9216-75ac911efa26.png)

**Comment by whk-isat** [comment]
@ShannonDing

**Comment by ShannonDing** [comment]
Hello, the go/python SDK are newly added some new features, so there are some issues with the version mapping. 
for time being,  
go v1.2.0 <===> CPP 1.2.3, 
go v1.2.2+ <===>  latest code. 
so, if you want to connect a local broker, the latest CPP code should be compiled and install, and if you want to connect ALIYUN, it is better to follow the setup on its website as there is the latest binary on its website.
for more info, the CPP v1.2.4 will be released soon to support the newly go and python SDK versions.

**Comment by wenfengwang** [comment]
close due to inactive long time, if there is any update, please reopen free : )

**Comment by gy95** [comment]
> 
> 
> Hello, the go/python SDK are newly added some new features, so there are some issues with the version mapping.
> for time being,
> go v1.2.0 <===> CPP 1.2.3,
> go v1.2.2+ <===> latest code.
> so, if you want to connect a local broker, the latest CPP code should be compiled and install, and if you want to connect ALIYUN, it is better to follow the setup on its website as there is the latest binary on its website.
> for more info, the CPP v1.2.4 will be released soon to support the newly go and python SDK versions.

  which go version does cpp1.2.2   need？
