### ISSUE TITLE
[Native] [Bug] remoteBrokerOffsetStore read missing fallthrough 

### ISSUE THREAD

**Issue by jalesys** [apache/rocketmq-client-go#299]
**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

missing `fallthrough` before [https://github.com/apache/rocketmq-client-go/blob/4364ebd190588b4a40963182495318002b03e63a/consumer/offset_store.go#L288](https://github.com/apache/rocketmq-client-go/blob/4364ebd190588b4a40963182495318002b03e63a/consumer/offset_store.go#L288)

    - What did you do (The steps to reproduce)?

    - What did you expect to see?

    - What did you see instead?

2. Please tell us about your environment:

     - What is your OS?

     - What is your client version?

     - What is your RocketMQ version?

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

    - [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
    - [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
    - ...

**Comment by wenfengwang** [comment]
@jalesys Hi, Could you start a PR for fixing the bug?

**Comment by wenfengwang** [comment]
fixed
