### ISSUE TITLE
go get rocketmq-client-go error

### ISSUE THREAD

**Issue by geekso001** [apache/rocketmq-client-go#3]
go get github.com/apache/rocketmq-client-go/core
# github.com/apache/rocketmq-client-go/core
../../../Documents/git/go/src/github.com/apache/rocketmq-client-go/core/cfuns.go:21:10: fatal error: 'rocketmq/CMessageExt.h' file not found
#include "rocketmq/CMessageExt.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

##################
How to install?

**Comment by ShannonDing** [comment]
You should install cpp core first. Download [CPP CORE & C HEAD FILES](https://opensource-rocketmq-client.oss-cn-hangzhou.aliyuncs.com/cpp-client/linux/1.0.2/RHEL7.x/librocketmq.tar.gz).
then copy the library to /usr/local/lib and the head files to /usr/local/include/rocketmq

**Comment by geekso001** [comment]
非常感谢，这么快就回复了，解决了我大问题，mac电脑上我试试可不可以，谢谢。

**Comment by wenfengwang** [comment]
librocketmq.so you downloaded had built on other platforms, so it can't be applied on macOS. because the binary library of macOS not available now, you have to build rocketmq-client-cpp on your macOS from source. you could refer [build-and-install](https://github.com/apache/rocketmq-client-cpp#build-and-install) for how to install, for ensuring compile code success on macOS, please modify your local repository according to changes of [PR-16](https://github.com/apache/rocketmq-client-cpp/pull/16)(the pr has not been merged.)

**Comment by geekso001** [comment]
MacOS could not install rocketmq-client-cpp, the installation time was wrong, the error message is as follows:
====================================
/Users/han/Downloads/rocketmq-client-cpp-master/src/consumer/ConsumeMessageConcurrentlyService.cpp:18:10: fatal error: 'sys/prctl.h' file not found
#include <sys/prctl.h>
         ^~~~~~~~~~~~~
1 error generated.

**Comment by geekso001** [comment]
thank you

**Comment by gaufung** [comment]
I have completed basic introduction about how to use this package. I hope it would help you. [introduction](https://github.com/gaufung/rocketmq-client-go/blob/master/doc/Introduction.md)

**Comment by mumushuiding** [comment]
windows环境下怎么搞？
我在windows下的操作顺序：
0.下载"http://opensource-rocketmq-client-us.oss-us-west-1.aliyuncs.com/cpp-client/windows/1.2.0/rocketmq-client-cpp.lib"和"http://opensource-rocketmq-client-us.oss-us-west-1.aliyuncs.com/cpp-client/windows/1.2.0/rocketmq-client-cpp.dll"并修改名字成rocketmq.lib和rocketmq.dll
1.将rocketmq.lib和rocketmq.dll放到C:\usr\local\lib下
2.go get github.com/apache/rocketmq-client-go
3.进入rocketmq-client-go/examples目录
4.go build
报错：-mingw32/bin/ld.exe: skipping incompatible /usr/local/lib\rocketmq.lib when searching for -lrocketmq
5.set GOOS=linux
6.go build
报错：..\core\api.go:32:20: undefined: LogConfig

真是难，没招了
3.进入rocketmq-client-go/examples目录
4.go build
报错：-mingw32/bin/ld.exe: skipping incompatible /usr/local/lib\rocketmq.lib when searching for -lrocketmq
5.set GOOS=linux
6.go build
报错：..\core\api.go:32:20: undefined: LogConfig

真是难，没招了

**Comment by wangqingshan** [comment]
> 非常感谢，这么快就回复了，解决了我大问题，mac电脑上我试试可不可以，谢谢。

你好，mac上解决了吗，能帮我一下吗

**Comment by ShannonDing** [comment]
> > 非常感谢，这么快就回复了，解决了我大问题，mac电脑上我试试可不可以，谢谢。
> 
> 你好，mac上解决了吗，能帮我一下吗

1. git clone https://github.com/apache/rocketmq-client-cpp
2. mkdir -p /usr/local/include/rocketmq/
3. cp rocketmq-client-cpp/include/* /usr/local/include/rocketmq
4. sh build.sh
5. after build sucess, cp bin/librocketmq.dylib /usr/local/lib
6. install the go SDK.
7. go build your code.

**Comment by wangqingshan** [comment]
> > > 非常感谢，这么快就回复了，解决了我大问题，mac电脑上我试试可不可以，谢谢。
> > 
> > 
> > 你好，mac上解决了吗，能帮我一下吗
> 
>     1. git clone https://github.com/apache/rocketmq-client-cpp
> 
>     2. mkdir -p /usr/local/include/rocketmq/
> 
>     3. cp rocketmq-client-cpp/include/* /usr/local/include/rocketmq
> 
>     4. sh build.sh
> 
>     5. after build sucess, cp bin/librocketmq.dylib /usr/local/lib
> 
>     6. install the go SDK.
> 
>     7. go build your code.

i follow your steps to build ,but i doesnot work ,where i run step4 ,and Mac has no "/usr/local/lib"

**Comment by ShannonDing** [comment]
> > > > 非常感谢，这么快就回复了，解决了我大问题，mac电脑上我试试可不可以，谢谢。
> > > 
> > > 
> > > 你好，mac上解决了吗，能帮我一下吗
> > 
> > 
> > ```
> > 1. git clone https://github.com/apache/rocketmq-client-cpp
> > 
> > 2. mkdir -p /usr/local/include/rocketmq/
> > 
> > 3. cp rocketmq-client-cpp/include/* /usr/local/include/rocketmq
> > 
> > 4. sh build.sh
> > 
> > 5. after build sucess, cp bin/librocketmq.dylib /usr/local/lib
> > 
> > 6. install the go SDK.
> > 
> > 7. go build your code.
> > ```
> 
> i follow your steps to build ,but i doesnot work ,where i run step4 ,and Mac has no "/usr/local/lib"

1. please show the error log.
2. mkdir /usr/local/lib

**Comment by wangqingshan** [comment]
when run step4 ,the error like this 
![图片](https://user-images.githubusercontent.com/42465887/72599970-b2029480-394d-11ea-9a2c-db657f47094c.png)

**Comment by ShannonDing** [comment]
pls refer to https://github.com/apache/rocketmq-client-cpp.
build tools should be installed first.

**Comment by wangqingshan** [comment]
> pls refer to https://github.com/apache/rocketmq-client-cpp.
> build tools should be installed first.

thanks for your help!

**Comment by nobsu** [comment]
export C_INCLUDE_PATH=/usr/local/include/
export CPLUS_INCLUDE_PATH=/usr/local/include/
export LIBRARY_PATH=/usr/local/lib/

**Comment by AegypiusMonachus** [comment]
admin@admindeMacBook-Pro-2 rocketmq-client-cpp % sh build.sh
###########################################################################
need build openssl lib
need build jsoncpp lib
need build libevent lib
need build boost lib
disable asan reporting
disable lsan reporting
need print detail logs
run unit tests without code coverage
disable debug
without build unit tests
###########################################################################

/Users/admin/rocketmq-client-cpp/tmp_down_dir exists
/Users/admin/rocketmq-client-cpp/tmp_build_dir exists
/Users/admin/rocketmq-client-cpp/tmp_packet_dir exists
/Users/admin/rocketmq-client-cpp/bin exists
build.sh: line 215: wget: command not found

**Comment by AegypiusMonachus** [comment]
i follow your steps to build . this's step4

**Comment by shencw** [comment]
> > > 非常感谢，这么快就回复了，解决了我大问题，mac电脑上我试试可不可以，谢谢。
> > 
> > 
> > 你好，mac上解决了吗，能帮我一下吗
> 
> 1. git clone https://github.com/apache/rocketmq-client-cpp
> 2. mkdir -p /usr/local/include/rocketmq/
> 3. cp rocketmq-client-cpp/include/* /usr/local/include/rocketmq
> 4. sh build.sh
> 5. after build sucess, cp bin/librocketmq.dylib /usr/local/lib
> 6. install the go SDK.
> 7. go build your code.

@ShannonDing  你有遇到过cp: include/c is a directory (not copied).问题么？  我的include下面还有c的目录 或者是不是我的代码版本太过于新了  。。。
