### ISSUE TITLE
[Native]  client-go do not support GET_CONSUMER_RUNNING_INFO

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#301]
**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?

    - What did you expect to see?
get clientId and relation info    
    - What did you see instead?
org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: the go client has not supported consumer running info
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
2. Please tell us about your environment:

     - What is your OS?

     - What is your client version?

     - What is your RocketMQ version?

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

    - [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
    - [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
    - ...

**Comment by wenfengwang** [comment]
fixed at #301
