### ISSUE TITLE
[Native] push consumer receives multiple messages, but just return one consumer status

### ISSUE THREAD

**Issue by twz915** [apache/rocketmq-client-go#302]
It is strange to me that push consumer receives multiple messages, but just return one consumer status. If one of msgs is unsuccessful, but the others are successful, which consumer status should I return?

```
	err := c.Subscribe("test", consumer.MessageSelector{}, func(ctx context.Context,
		msgs ...*primitive.MessageExt) (consumer.ConsumeResult, error) {
		fmt.Printf("subscribe callback: %v \n", msgs)
		return consumer.ConsumeSuccess, nil
	})
```

https://github.com/apache/rocketmq-client-go/blob/native/examples/consumer/simple/main.go#L37

**Comment by wenfengwang** [comment]
The RocketMQ provides `at least once` guarantee, which means some messages may be duplicated for consuming. For multiple messages that part consuming failed and another succeeded, you should return `ConsumeRetryLater` for consuming later. if you worry about consuming duplicated, you should assign a business ID for each message for avoiding double consuming depend on external DB like Redis or others.

**Comment by twz915** [comment]
I mean that the `callback func` of c.Subscribe receives msgs (multiple messages), but return value just one status.

**Comment by wenfengwang** [comment]
> I mean that the `callback func` of `c.Subscribe` receives msgs (multiple messages), but return value just one status.

Yes, the native version code is ok, no mistake. you could also refer Java: https://github.com/apache/rocketmq/blob/master/client/src/main/java/org/apache/rocketmq/client/consumer/listener/MessageListenerConcurrently.java#L33

**Comment by twz915** [comment]
OK, the java version remark explains the design. So normally just one msg in slice. When multiple msgs received, if one failed, all of msgs should retry later.
```
msgs msgs.size() >= 1
DefaultMQPushConsumer.consumeMessageBatchMaxSize=1, you can modify here
```
Thank you.

**Comment by wenfengwang** [comment]
@twz915 : )
