### ISSUE TITLE
[Native] not consistent with java impl

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#304]
**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
method `updateProcessQueueTable` of defaultConsumer is not consistent with java impl.

    - What did you expect to see?

    - What did you see instead?

2. Please tell us about your environment:

     - What is your OS?

     - What is your client version?

     - What is your RocketMQ version?

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by wenfengwang** [comment]
fixed at https://github.com/apache/rocketmq-client-go/pull/309
