### ISSUE TITLE
[Master] go build fail using static library.

### ISSUE THREAD

**Issue by hanzhonghua0927** [apache/rocketmq-client-go#305]
/usr/local/lib/librocketmq.a(exceptions.o):exceptions.cpp:(.text._ZN5boost9to_stringINS_3log12v2s_mt_posix23attribute_name_info_tagENS2_14attribute_nameEEESsRKNS_10error_infoIT_T0_EE[_ZN5boost9to_stringINS_3log12v2s_mt_posix23attribute_name_info_tagENS2_14attribute_nameEEESsRKNS_10error_infoIT_T0_EE]+0x83b): more undefined references to `std::string::_Rep::_M_dispose(std::allocator<char> const&)' follow
/usr/local/lib/librocketmq.a(exceptions.o):(.data.rel.ro._ZTIN5boost16exception_detail20error_info_containerE[_ZTIN5boost16exception_detail20error_info_containerE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'

**Comment by hanzhonghua0927** [comment]
my build script is :

**Comment by hanzhonghua0927** [comment]
script is : go build -a -installsuffix cgo -ldflags '-extldflags "-static -Istdc++"' -o bin/aaa cmd/aaa/main.go

**Comment by hanzhonghua0927** [comment]
please how to build it

**Comment by ShannonDing** [comment]
What is the g++ version, and you can have a try on removing the extldflags.

**Comment by wenfengwang** [comment]
> What is the g++ version, and you can have a try on removing the extldflags.

@hanzhonghua0927 The reply has resolved your problem?

**Comment by zengxiaobai** [comment]
> > What is the g++ version, and you can have a try on removing the extldflags.
> 
> @hanzhonghua0927 The reply has resolved your problem?

can you make a README course of using librocketmq.a. I also use go build with ldflags 'static'.  But run with sement failed with some thread funtion errors

**Comment by hanzhonghua0927** [comment]
> What is the g++ version, and you can have a try on removing the extldflags.

now it succ  ,  because i remove "-static"

**Comment by hanzhonghua0927** [comment]
> > > What is the g++ version, and you can have a try on removing the extldflags.
> > 
> > 
> > @hanzhonghua0927 The reply has resolved your problem?
> 
> can you make a README course of using librocketmq.a. I also use go build with ldflags 'static'. But run with sement failed with some thread funtion errors

you can remove "-static" and have a try

**Comment by ShannonDing** [comment]
Hello, @hanzhonghua0927 @zengxiaobai 
The Cgo SDK will link the dynamic CPP library as default, and the dependencies such as the zlib are linked dynamically.
if you want to use the CPP static library, the Zlib and libstdc++ libraries need to be linked manually, please follow 3 steps:
1. remove the dynamic library in your LDPATH(default: /usr/local/lib)
2. change the LDFLAGs in the go SDK from "cgo LDFLAGS: -L/usr/local/lib -lrocketmq" to "cgo LDFLAGS: -L/usr/local/lib -lz -l stdc++ -lrocketmq"
3. build your project directly without any building flags.

please have a try.

**Comment by zengxiaobai** [comment]
> Hello, @hanzhonghua0927 @zengxiaobai
> The Cgo SDK will link the dynamic CPP library as default, and the dependencies such as the zlib are linked dynamically.
> if you want to use the CPP static library, the Zlib and libstdc++ libraries need to be linked manually, please follow 3 steps:
> 
> 1. remove the dynamic library in your LDPATH(default: /usr/local/lib)
> 2. change the LDFLAGs in the go SDK from "cgo LDFLAGS: -L/usr/local/lib -lrocketmq" to "cgo LDFLAGS: -L/usr/local/lib -lz -l stdc++ -lrocketmq"
> 3. build your project directly without any building flags.
> 
> please have a try.

I try like this:
step1: remove librocketmq.so from /usr/local/lib, mv librocketmq.a to /usr/local/lib/
step2:  install zlib-static libstdc++-static 
step3: copy  libz.a libstdc++.a to /usr/local/lib
step4:  change  core/producer.go  core/message.go  core/cfuns.go  core/pull_consumer.go  core/push_consumer.go  FROM
#cgo LDFLAGS: -L /usr/local/lib/    TO  -L/usr/local/lib/ -lrocketmq -lz -lstdc++ (-lrocketmq)
step5: go build

ERRORS: 
```
global_logger_storage.cpp:(.text+0x224): undefined reference to `std::string::_Rep::_M_dispose(std::allocator<char> const&)'
/usr/local/lib/librocketmq.a(global_logger_storage.o):global_logger_storage.cpp:(.text+0x238): more undefined references to `std::string::_Rep::_M_dispose(std::allocator<char> const&)' follow
/usr/local/lib/librocketmq.a(global_logger_storage.o): In function `boost::log::v2s_mt_posix::sources::aux::global_storage::get_or_init(std::type_info const&, boost::shared_ptr<boost::log::v2s_mt_posix::sources::aux::logger_holder_base> (*)())':
global_logger_storage.cpp:(.text+0x678): undefined reference to `__cxa_guard_acquire'
```

**Comment by ShannonDing** [comment]
> > Hello, @hanzhonghua0927 @zengxiaobai
> > The Cgo SDK will link the dynamic CPP library as default, and the dependencies such as the zlib are linked dynamically.
> > if you want to use the CPP static library, the Zlib and libstdc++ libraries need to be linked manually, please follow 3 steps:
> > 
> > 1. remove the dynamic library in your LDPATH(default: /usr/local/lib)
> > 2. change the LDFLAGs in the go SDK from "cgo LDFLAGS: -L/usr/local/lib -lrocketmq" to "cgo LDFLAGS: -L/usr/local/lib -lz -l stdc++ -lrocketmq"
> > 3. build your project directly without any building flags.
> > 
> > please have a try.
> 
> I try like this:
> step1: remove librocketmq.so from /usr/local/lib, mv librocketmq.a to /usr/local/lib/
> step2: install zlib-static libstdc++-static
> step3: copy libz.a libstdc++.a to /usr/local/lib
> step4: change core/producer.go core/message.go core/cfuns.go core/pull_consumer.go core/push_consumer.go FROM
> #cgo LDFLAGS: -L /usr/local/lib/ -lrocketmq TO
> -L/usr/local/lib/ -lrocketmq -lz -lstdc++ (-lrocketmq)
> step5: go build
> 
> ERRORS:
> 
> ```
> /usr/local/lib/librocketmq.a(global_logger_storage.o):global_logger_storage.cpp:(.text+0x238): more undefined references to `std::string::_Rep::_M_dispose(std::allocator<char> const&)' follow
> /usr/local/lib/librocketmq.a(global_logger_storage.o): In function `boost::log::v2s_mt_posix::sources::aux::global_storage::get_or_init(std::type_info const&, boost::shared_ptr<boost::log::v2s_mt_posix::sources::aux::logger_holder_base> (*)())':
> global_logger_storage.cpp:(.text+0x678): undefined reference to `__cxa_guard_acquire'
> global_logger_storage.cpp:(.text+0x6d7): undefined reference to `__cxa_guard_release'
> global_logger_storage.cpp:(.text+0x802): undefined reference to `operator new(unsigned long)'
> global_logger_storage.cpp:(.text+0x845): undefined reference to `std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)'
> global_logger_storage.cpp:(.text+0x933): undefined reference to `__cxa_guard_acquire'
> global_logger_storage.cpp:(.text+0x992): undefined reference to `__cxa_guard_release'
> global_logger_storage.cpp:(.text+0xb23): undefined reference to `__cxa_guard_abort'
> global_logger_storage.cpp:(.text+0xba8): undefined reference to `__cxa_guard_abort'
> /usr/local/lib/librocketmq.a(global_logger_storage.o): In function `boost::log::v2s_mt_posix::type_info_wrapper::pretty_name() const':
> global_logger_storage.cpp:(.text._ZNK5boost3log12v2s_mt_posix17type_info_wrapper11pretty_nameEv[_ZNK5boost3log12v2s_mt_posix17type_info_wrapper11pretty_nameEv]+0x62): undefined reference to `__cxa_demangle'
> ```
Hello,
I think this error occurs caused by depency tree error in g++ link, "-lstdc++" should be linked before "-lrocketmq", KEEP "cgo LDFLAGS: -L/usr/local/lib **-lz -lstdc++ -lrocketmq**"
Could you please share your g++ version and try it again?

**Comment by zengxiaobai** [comment]
> > > Hello, @hanzhonghua0927 @zengxiaobai
> > > The Cgo SDK will link the dynamic CPP library as default, and the dependencies such as the zlib are linked dynamically.
> > > if you want to use the CPP static library, the Zlib and libstdc++ libraries need to be linked manually, please follow 3 steps:
> > > 
> > > 1. remove the dynamic library in your LDPATH(default: /usr/local/lib)
> > > 2. change the LDFLAGs in the go SDK from "cgo LDFLAGS: -L/usr/local/lib -lrocketmq" to "cgo LDFLAGS: -L/usr/local/lib -lz -l stdc++ -lrocketmq"
> > > 3. build your project directly without any building flags.
> > > 
> > > please have a try.
> > 
> > 
> > I try like this:
> > step1: remove librocketmq.so from /usr/local/lib, mv librocketmq.a to /usr/local/lib/
> > step2: install zlib-static libstdc++-static
> > step3: copy libz.a libstdc++.a to /usr/local/lib
> > step4: change core/producer.go core/message.go core/cfuns.go core/pull_consumer.go core/push_consumer.go FROM
> > #cgo LDFLAGS: -L /usr/local/lib/ -lrocketmq TO
> > -L/usr/local/lib/ -lrocketmq -lz -lstdc++ (-lrocketmq)
> > step5: go build
> > ERRORS:
> > ```
> > /usr/local/lib/librocketmq.a(global_logger_storage.o):global_logger_storage.cpp:(.text+0x238): more undefined references to `std::string::_Rep::_M_dispose(std::allocator<char> const&)' follow
> > /usr/local/lib/librocketmq.a(global_logger_storage.o): In function `boost::log::v2s_mt_posix::sources::aux::global_storage::get_or_init(std::type_info const&, boost::shared_ptr<boost::log::v2s_mt_posix::sources::aux::logger_holder_base> (*)())':
> > global_logger_storage.cpp:(.text+0x678): undefined reference to `__cxa_guard_acquire'
> > global_logger_storage.cpp:(.text+0x6d7): undefined reference to `__cxa_guard_release'
> > global_logger_storage.cpp:(.text+0x802): undefined reference to `operator new(unsigned long)'
> > global_logger_storage.cpp:(.text+0x845): undefined reference to `std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)'
> > global_logger_storage.cpp:(.text+0x933): undefined reference to `__cxa_guard_acquire'
> > global_logger_storage.cpp:(.text+0x992): undefined reference to `__cxa_guard_release'
> > global_logger_storage.cpp:(.text+0xb23): undefined reference to `__cxa_guard_abort'
> > global_logger_storage.cpp:(.text+0xba8): undefined reference to `__cxa_guard_abort'
> > /usr/local/lib/librocketmq.a(global_logger_storage.o): In function `boost::log::v2s_mt_posix::type_info_wrapper::pretty_name() const':
> > global_logger_storage.cpp:(.text._ZNK5boost3log12v2s_mt_posix17type_info_wrapper11pretty_nameEv[_ZNK5boost3log12v2s_mt_posix17type_info_wrapper11pretty_nameEv]+0x62): undefined reference to `__cxa_demangle'
> > ```
> 
> Hello,
> I think this error occurs caused by depency tree error in g++ link, "-lstdc++" should be linked before "-lrocketmq", KEEP "cgo LDFLAGS: -L/usr/local/lib **-lz -lstdc++ -lrocketmq**"
> Could you please share your g++ version and try it again?

 **g++ version**
```
[root@kvm-31 ~]# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
**Step4**
'_-L/usr/local/lib/ -lrocketmq -lz -lstdc++ (-lrocketmq)_ '  the () means I have test before and after, I get same result

**Comment by zengxiaobai** [comment]
I use _go build -ldflags '-extldflags "-static -lstdc++ -lz"'_  , build without stdc++ error but some warnings:
```
[root@kvm-31 rocketxclean]# !go
go build -ldflags '-extldflags "-static -lstdc++ -lz"'
# rocketmq-filemgr/src/rocketxclean
/tmp/go-link-108202940/000028.o: In function `mygetgrouplist':
/workdir/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-108202940/000027.o: In function `mygetgrgid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-108202940/000027.o: In function `mygetgrnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib/librocketmq.a(UtilAll.cpp.o): In function `rocketmq::UtilAll::getHomeDirectory()':
UtilAll.cpp:(.text+0x628): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-108202940/000027.o: In function `mygetpwnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-108202940/000027.o: In function `mygetpwuid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-108202940/000025.o: In function `_cgo_26061493d47f_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib/librocketmq.a(SocketUtil.cpp.o): In function `rocketmq::getHostName(sockaddr)':
SocketUtil.cpp:(.text+0x114): warning: Using 'gethostbyaddr' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/lib/librocketmq.a(evutil.o): In function `evutil_unparse_protoname':
evutil.c:(.text+0xefc): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
[root@kvm-31 rocketxclean]# 
```


And start failed with 

```
untime stack:
runtime.throw(0xba5cdd, 0x2a)
	/home/zwb/go/go1.13/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/home/zwb/go/go1.13/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall]:
runtime.cgocall(0x825ac0, 0xc0000fbcf8, 0x4)
	/home/zwb/go/go1.13/src/runtime/cgocall.go:128 +0x5b fp=0xc0000fbcc8 sp=0xc0000fbc90 pc=0x415fcb
github.com/apache/rocketmq-client-go/core._Cfunc_StartPushConsumer(0x7fa28c000940, 0x7fa200000000)
	_cgo_gotypes.go:1153 +0x49 fp=0xc0000fbcf8 sp=0xc0000fbcc8 pc=0x5363a9
github.com/apache/rocketmq-client-go/core.(*defaultPushConsumer).Start.func1(0xc00006a000, 0xc0000208d0)
	/home/zwb/go/src/github.com/apache/rocketmq-client-go/core/push_consumer.go:205 +0x5f fp=0xc0000fbd38 sp=0xc0000fbcf8 pc=0x539e3f
github.com/apache/rocketmq-client-go/core.(*defaultPushConsumer).Start(0xc00006a000, 0xb8fc58, 0x4)
	/home/zwb/go/src/github.com/apache/rocketmq-client-go/core/push_consumer.go:205 +0x2b fp=0xc0000fbd58 sp=0xc0000fbd38 pc=0x53830b
rocketmq-filemgr/src/rocketmqMy.ConsumeWithPush(0xc0000d0000, 0xb8fc58, 0x4, 0xb8fe76, 0x5, 0xc00002e120, 0x25)
	/home/zwb/go/src/rocketmq-filemgr/src/rocketmqMy/rocketmqMy.go:89 +0xc0 fp=0xc0000fbde8 sp=0xc0000fbd58 pc=0x8207c0
main.(*rocketmqXclean).RocketMQStart(0xc000100030)
	/home/zwb/go/src/rocketmq-filemgr/src/rocketxclean/rocketxclean.go:57 +0x1bc fp=0xc0000fbe68 sp=0xc0000fbde8 pc=0x82176c
rocketmq-filemgr/src/common.(*ExeCommon).Run(0xc0000d6300, 0xc408e0, 0xc000100030)
	/home/zwb/go/src/rocketmq-filemgr/src/common/exe_api.go:117 +0xea fp=0xc0000fbe98 sp=0xc0000fbe68 pc=0x817eaa
```

**Comment by ShannonDing** [comment]
hello, did you follow the steps?
1. remove the dynamic library in your LDPATH(default: /usr/local/lib)
2. change the LDFLAGs in the go SDK from "cgo LDFLAGS: -L/usr/local/lib -lrocketmq" to "cgo LDFLAGS: -L/usr/local/lib -lz -lstdc++ -lrocketmq"
3. build your project directly **without any building flags.**

I have checked that it works well on gcc/g++ 4.8.x.
