### ISSUE TITLE
[Master] Consumers can't work properly, It was good the other day

### ISSUE THREAD

**Issue by hanzhonghua0927** [apache/rocketmq-client-go#326]
The subscription was successful but no message was received

**Comment by hanzhonghua0927** [comment]
![image](https://user-images.githubusercontent.com/25861358/70423996-8f0cd700-1aa9-11ea-8deb-774831e3daeb.png)

**Comment by hanzhonghua0927** [comment]
for help ! ! !

**Comment by hanzhonghua0927** [comment]
I started multiple processes in the same group and multiple topics

**Comment by hanzhonghua0927** [comment]
@ShannonDing   i need your help

**Comment by ShannonDing** [comment]
Hi, @hanzhonghua0927 
There is too little information to see what is wrong. It is recommended to start with the following issues:
1. Check if there are any abnormal error messages in the CPP logs. The default log directory is {home} / logs.
2. The screenshot shows that many topics have been subscribed to. please confirm whether there are inconsistent subscription relationships.
3. You can try a topic separately to see if it works ok and rule out environmental problems.

**Comment by hanzhonghua0927** [comment]
hi, @ShannonDing

**Comment by hanzhonghua0927** [comment]
hi, @ShannonDing  Is it true that multiple consumers can only be multiple groups ?

**Comment by hanzhonghua0927** [comment]
> hi, @ShannonDing Is it true that multiple consumers can only be multiple groups ?

One consumer one group can, multiple consumers multiple groups can not

**Comment by hanzhonghua0927** [comment]
> hi, @ShannonDing Is it true that multiple consumers can only be multiple groups ?

A group of consumers can, a group of consumers can not

**Comment by hanzhonghua0927** [comment]
> hi, @ShannonDing Is it true that multiple consumers can only be multiple groups ?

One consumer a group can, multiple consumers a group can not

**Comment by ShannonDing** [comment]
> > hi, @ShannonDing Is it true that multiple consumers can only be multiple groups ?
> 
> One consumer a group can, multiple consumers a group can not

Multiple consumers can use one GroupID to consume message in multi-topics by Clustering model,
and the prerequisite is that the subscription relationship needs to be consistent.

**Comment by hanzhonghua0927** [comment]
> > > hi, @ShannonDing Is it true that multiple consumers can only be multiple groups ?
> > 
> > 
> > One consumer a group can, multiple consumers a group can not
> 
> Multiple consumers can use one GroupID to consume message in multi-topics by Clustering model,
> and the prerequisite is that the subscription relationship needs to be consistent.

and the prerequisite is that the subscription relationship needs to be consistent. What does this mean?

**Comment by ShannonDing** [comment]
Keeping the subscription relationship consistent means that all instances under the same consumer Group ID need to be consistent in the following two aspects:
1. Subscription topics must be consistent
2. The tags in the subscribed topics must be consistent

**Comment by hanzhonghua0927** [comment]
> Keeping the subscription relationship consistent means that all instances under the same consumer Group ID need to be consistent in the following two aspects:
> 
> 1. Subscription topics must be consistent
> 2. The tags in the subscribed topics must be consistent

Thank you very much. I see
