### ISSUE TITLE
[MASTER] The consumer does not work after running for some time

### ISSUE THREAD

**Issue by hanzhonghua0927** [apache/rocketmq-client-go#337]
52/5000 
A process starts with multiple consumers, and each consumer has a group corresponding to a topic. The consumers of this process do not consume after running for a period of time

**Comment by hanzhonghua0927** [comment]
@ShannonDing

**Comment by ShannonDing** [comment]
it may caused by CPP core.  this issue will be transferred to the CPP client project. I will close it first.
