### ISSUE TITLE
centos上编译遇到“未定义的引用”问题

### ISSUE THREAD

**Issue by sli4** [apache/rocketmq-client-go#34]
go build .
# configcenter/vendor/github.com/apache/rocketmq-client-go/core
/tmp/go-build465039094/b200/_x006.o：在函数‘_cgo_8957cb566e0b_Cfunc_SetProducerNameServerDomain’中：
/tmp/go-build/cgo-gcc-prolog:320：对‘SetProducerNameServerDomain’未定义的引用
/tmp/go-build465039094/b200/_x007.o：在函数‘_cgo_8957cb566e0b_Cfunc_SetPullConsumerNameServerDomain’中：
/tmp/go-build/cgo-gcc-prolog:256：对‘SetPullConsumerNameServerDomain’未定义的引用
/tmp/go-build465039094/b200/_x008.o：在函数‘_cgo_8957cb566e0b_Cfunc_SetPushConsumerNameServerDomain’中：
/tmp/go-build/cgo-gcc-prolog:255：对‘SetPushConsumerNameServerDomain’未定义的引用
collect2: 错误：ld 返回 1

**Comment by wenfengwang** [comment]
Does your `/usr/local/incude` include `rocketmq` directory and `/usr/local/lib` include `librokcetmq.so` & `librocketmq.a` file?

**Comment by sli4** [comment]
Yes, I found the reason, it's the C.SetProducerNameServerDomain、C.SetPullConsumerNameServerDomain、C.SetPushConsumerNameServerDomain func which may be not defined in rocketmq-client-cpp.
I comment these code and change to other func for replacement,  now compile result is OK.

```
if config.NameServerDomain != "" {
	cs = C.CString(config.NameServerDomain)
	err = rmqError(C.SetPushConsumerNameServerAddress(cconsumer, cs)) //err = rmqError(C.SetPushConsumerNameServerDomain(cconsumer, cs))
	C.free(unsafe.Pointer(cs))
	if err != NIL {
		return nil, err
	}
}
```
