### ISSUE TITLE
[Native]How about change TransactionListener's method param type from struct to pointer

### ISSUE THREAD

**Issue by Me1onRind** [apache/rocketmq-client-go#340]
When I try use transaction, I implement the interface,  I find the interface method's param is struct
```go
// primitive/message.go
type TransactionListener interface {
    ExecuteLocalTransaction(Message) LocalTransactionState
    CheckLocalTransaction(MessageExt) LocalTransactionState
}
```
I think passing struct isn't a efficient way. Then, my vim warning me  "copy locks"
becuse struct Message and MessageExt anonymous inheritance sync.RWMutex
```go
// primitive/message.go
type Message struct {
    // other codes                                                                                                                                                    
    mutex      sync.RWMutex                                                                                                                                                                  
}
// ...
type MessageExt struct {
    Message
    // other codes
}                                                                                                                                                                  
```
So I think mabey change TransactionListener to
```go
type TransactionListener interface {
    ExecuteLocalTransaction(*Message) LocalTransactionState
    CheckLocalTransaction(*MessageExt) LocalTransactionState
}
```
will be better, if it will not case other bug.  If it's  ok, I can try to change it.

**Comment by wenfengwang** [comment]
Thank you @Me1onRind , your are right, a pointer is better. could you create a Pull Request for the issue before next Monday(we wiil release rc version in next week) if possible

**Comment by Me1onRind** [comment]
Sorry I am busy these day, and see the message now (>_<),   So I can't finished it before Monday now. It not in next rc version may not bad thing, may just change it to pointer may bring some unpredictable hidden bug?

**Comment by wenfengwang** [comment]
@Me1onRind  There are no some unpredictable bugs appear in my head, I think the pointer will work well. How do you think of it? @xujianhai666

**Comment by Me1onRind** [comment]
emmm, I just not very familiar with all codes,  so afraid bring bug into project^_^. I have created Pull Request.

**Comment by wenfengwang** [comment]
close due to #373
