### ISSUE TITLE
[Master]build failed in Windows

### ISSUE THREAD

**Issue by xx132917** [apache/rocketmq-client-go#342]
# github.com/apache/rocketmq-client-go/core
..\github.com\apache\rocketmq-client-go\core\consumer_callback.go:23:10: fatal error: rocketmq/CMessageExt.h: No such file or directory
 #include <rocketmq/CMessageExt.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by wenfengwang** [comment]
sorry for we have not tested on Windows platform, the reason of you reported is the complier can not find the header file, please check it

**Comment by Aurora-ws** [comment]
where is CMessageExt.h‘s path   for windows platform？

**Comment by Aurora-ws** [comment]
where is CMessageExt.h‘s path on windows platform？
