### ISSUE TITLE
[native] branch v2.0.0-alpha3, how to choose the RocketMQ server version?

### ISSUE THREAD

**Issue by plhwin** [apache/rocketmq-client-go#348]
I installed RocketMQ v4.6.0 and used the rocket-client-go branch v2.0.0-alpha3, but found many problems:

1. Run two consumer client programs at the same time, they subscribe to the same topic and the same group, and use the consumer.Clustering mode, but the client cannot balance the consumption, but behaves like the BroadCasting mode, each client consumes Every message
2. Set consumer.WithConsumeFromWhere to consumer.ConsumeFromLastOffset, but every time you start the consumer program, you will still receive the old message sent before and behave like ConsumeFromFirstOffset

and many more...

I see through the rocket console that the client consumer program version connected to testGroup is V4_5_2. I am using Branch v2.0.0-alpha3 (Native branch has also tried, the effect is the same), so ask if the client version must be the same as Consistent on the server? Do I have to reinstall the v4.5.2 server version of RocketMQ?

![image](https://user-images.githubusercontent.com/1219345/71608818-e55bca00-2bbe-11ea-9a63-c926ac53c00f.png)

please see this picture, no matter how my consumer program changes the WithConsumerModel and WithConsumeFromWhere configurations, the two values ​​of CLUSTERING and CONSUME_FROM_FIRST_OFFSET will never change.

**Comment by wenfengwang** [comment]
@plhwin the V4_5_2 is not requried, your picture is die, could you provider another one?

**Comment by ShannonDing** [comment]
close due to time too long. a new issue is welcomed if this error still occurs.
