### ISSUE TITLE
How Does "rocketmq-client-go" Support Transaction

### ISSUE THREAD

**Issue by figoxu** [apache/rocketmq-client-go#35]
How Does This SDK Support The Methods Of 'Producer And Consumer' Such As : 'BeginTransaction' 'CommitTransaction' 'Rollback'

**Comment by wenfengwang** [comment]
The methods doesn't support now, it will be support  in Jun. or July

**Comment by wenfengwang** [comment]
please track [2.0.0 Production Ready Road map](https://github.com/apache/rocketmq-client-go/issues/57)

**Comment by wenfengwang** [comment]
It will be supported in 2.0.0-alpha3, you can refer: https://github.com/apache/rocketmq-client-go/issues/120

**Comment by wenfengwang** [comment]
added by https://github.com/apache/rocketmq-client-go/pull/138

**Comment by ShannonDing** [comment]
Close due to #138
