### ISSUE TITLE
[Native]how to get github.com/apache/rocketmq-client-go v2.0.0-alpha1 version?

### ISSUE THREAD

**Issue by maojinhua** [apache/rocketmq-client-go#379]
如题 使用 require (
    github.com/apache/rocketmq-client-go v2.0.0-alpha1
)获取该sdk获取不到 请问怎么解决呢谢谢

**Comment by maojinhua** [comment]
require github.com/apache/rocketmq-client-go: version "v2.0.0-alpha1" invalid: unknown revision v2.0.0-alpha1

**Comment by DevDavid1307** [comment]
这样可以

`require github.com/apache/rocketmq-client-go v2.0.0-rc1`

**Comment by ShannonDing** [comment]
Since the alpha3, the version label was changed to v2.x.x with a prefix "v", 
you can use `require github.com/apache/rocketmq-client-go v2.x.x`,
for old alpha version, maybe `require github.com/apache/rocketmq-client-go 2.0.0-alpha1` without prefix works well.
