### ISSUE TITLE
[native]get github.com/apache/rocketmq-client-go v2.0.0-rc1 error

### ISSUE THREAD

**Issue by doucheng** [apache/rocketmq-client-go#380]
go version
go version go1.13.4 darwin/amd64

require (
    github.com/apache/rocketmq-client-go v2.0.0-rc1+incompatible
)

error:
go: finding github.com/apache/rocketmq-client-go v2.0.0-rc1+incompatible
go list -m: github.com/apache/rocketmq-client-go@v2.0.0-rc1+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required

------------
or 

require (
    github.com/apache/rocketmq-client-go v2.0.0-rc1
)

error:
go: finding github.com/apache/rocketmq-client-go v2.0.0-rc1
go: errors parsing go.mod:
/apps/webroot/production/xmq-infra/go.mod:9: require github.com/apache/rocketmq-client-go: version "v2.0.0-rc1" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

stackoverflow:  https://stackoverflow.com/questions/59587606/invalid-version-incompatible-suffix-not-allowed-module-contains-a-go-mod-file

**Comment by ZaynJarvis** [comment]
https://github.com/golang/go/wiki/Modules#semantic-import-versioning
This is to do with some Golang package semantic

**Comment by ZaynJarvis** [comment]
A solution is change 
module github.com/apache/rocketmq-client-go -> module github.com/apache/rocketmq-client-go/v2

and 
```
import (
    "github.com/apache/rocketmq-client-go/v2"
)
```

**Comment by ZaynJarvis** [comment]
> A solution is change
> module github.com/apache/rocketmq-client-go -> module github.com/apache/rocketmq-client-go/v2
> 
> and
> 
> ```
> import (
>     "github.com/apache/rocketmq-client-go/v2"
> )
> ```

A temp walk around is to suffix +incompatible after go.mod `require` statement
and use `GOSUMDB=off go mod vendor` to install pkg

**Comment by wenfengwang** [comment]
close due to #385 merged
