### ISSUE TITLE
[Native] go mod import v2.0.0-rc1 error

### ISSUE THREAD

**Issue by duffiye** [apache/rocketmq-client-go#388]
require (

    github.com/apache/rocketmq-client-go v2.0.0-rc1

)

get error : 

`go: finding github.com/apache/rocketmq-client-go v2.0.0-rc1
go: finding github.com/apache/rocketmq-client-go v2.0.0-rc1
go: errors parsing go.mod:
/Users/duffiye/code/erp/go.mod:22: require github.com/apache/rocketmq-client-go: version "v2.0.0-rc1" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2`

golang version: 1.13 darwin/amd64

maybe in go.mod shoud be

`module github.com/apache/rocketmq-client-go/v2
`

**Comment by ShannonDing** [comment]
link #380

**Comment by wenfengwang** [comment]
closed due to duplicated
