### ISSUE TITLE
[native]怎么发送顺序消息

### ISSUE THREAD

**Issue by hanlukk** [apache/rocketmq-client-go#410]
看了producer没有发送顺序消息的api 
发现Message里面 可以放入Queue，在不是写死QueueId的情况下我要怎么获取这个Queue，
 有没有什么API可以根据topic 获取旗下所有的Queue

**Comment by xujianhai666** [comment]
> 不是写死QueueId的情况下我要怎么获取这个Queue，
> 有没有什么API可以根据topic 获取旗下所有的Queue

@hanlukk  是可以制定 queueSelector的
