### ISSUE TITLE
[Native]go.mod has non-.../v2 module pat

### ISSUE THREAD

**Issue by kpvt001** [apache/rocketmq-client-go#424]
go: github.com/apache/rocketmq-client-go/v2@v2.0.0-rc1: go.mod has non-.../v2 module path "github.com/apache/rocketmq-client-go" (and .../v2/go.mod does not exist) at revision v2.0.0-rc1

**Comment by ShannonDing** [comment]
link #380

**Comment by kpvt001** [comment]
> link #380

但是我是昨天发现的这个问题，#380在1.9已经merge了

**Comment by xujianhai666** [comment]
> > link #380
> 
> 但是我是昨天发现的这个问题，#380在1.9已经merge了

@kpvt001 你确定拉取的是最新的吗？

**Comment by zhangxinghao** [comment]
我也遇到了同样的问题：
go: github.com/apache/rocketmq-client-go/v2@v2.0.0-rc1: go.mod has non-.../v2 module path "github.com/apache/rocketmq-client-go" (and .../v2/go.mod does not exist) at revision v2.0.0-rc1

**Comment by whaios** [comment]
$ git checkout  v2.0.0-rc1
Note: switching to 'v2.0.0-rc1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

**Comment by whaios** [comment]
go.mod:
require github.com/apache/rocketmq-client-go/v2 v2.0.0-rc1.0.20200119045717-cfdf53880dea

**Comment by zhangxinghao** [comment]
@whaios Thanks, `go get github.com/apache/rocketmq-client-go/v2@af4067cae785c6e632df9f0f5c689e7d5aa86646` works for me

**Comment by ShannonDing** [comment]
v2.0.0-rc2 is pre-reelased, and v2.0.0 will be released soon.
