### ISSUE TITLE
[Native] fix brokerName not found when broker  recover from machine crash

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#428]
**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?

    - What did you expect to see?

    - What did you see instead?

2. Please tell us about your environment:

     - What is your OS?

     - What is your client version?

     - What is your RocketMQ version?

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by ShannonDing** [comment]
yes, it is a bug of broker info update.

**Comment by ShannonDing** [comment]
link #429
