### ISSUE TITLE
[native] query topic route from server error underlayError="topic not exist"

### ISSUE THREAD

**Issue by zhangxinghao** [apache/rocketmq-client-go#434]
consumer start 报错：
INFO[0002] the consumer start beginning                  consumerGroup="MQ_INST_XXX%GID_YEE_MSG" messageModel=Clustering unitMode=false
INFO[0002] the topic route info changed                  changeTo="" changedFrom="<nil>" topic="MQ_INST_XXX%WECHAT_MSG_FROM_USER"
WARN[0002] query topic route from server error           underlayError="topic not exist"
WARN[0002] do balance in group failed, the topic does not exist  consumerGroup="MQ_INST_XXX%GID_YEE_MSG" topic="%RETRY%MQ_INST_XXX%GID_YEE_MSG"
WARN[0004] query topic route from server error           underlayError="topic not exist"
INFO[0004] remoting conn closed                          remote="118.190.213.42:80"
consumer start failed, the topic=%RETRY%MQ_INST_XXX%GID_YEE_MSG route info not found, it may not exist
INFO[0004] The RMQClient stopping do rebalance           clientID=192.168.1.179@DEFAULT
INFO[0004] The RMQClient stopping update topic route info.  clientID=192.168.1.179@DEFAULT
INFO[0004] The RMQClient stopping persist offset         clientID=192.168.1.179@DEFAULT
INFO[0004] The RMQClient stopping clean off line broker and heart beat  clientID=192.168.1.179@DEFAULT

**Comment by zhangxinghao** [comment]
mconsumer, err := rocketmq.NewPushConsumer(
		// consumer.WithInstance(instanceId),
		consumer.WithNamespace(instanceId),
		consumer.WithGroupName(msgGroupId),
		consumer.WithNameServer([]string{endpoint}),
		consumer.WithConsumerModel(consumer.Clustering),
		consumer.WithConsumeFromWhere(consumer.ConsumeFromFirstOffset),
		consumer.WithConsumerOrder(true),
		consumer.WithCredentials(primitive.Credentials{
			AccessKey: accessKey,
			SecretKey: secretKey,
		}),
	)

**Comment by ShannonDing** [comment]
Did you use the version v2.0.0-rc1 and link the ALIYUN cloud service?   the consumer will check the RETRY topic too strict on start.
the issue fixed by #403 and #406, you can get the latest code to have a try.
Another way, you can use this GroupID to link the cloud service by other SDK(such as Go master, CPP,Java), the RETRY topic will be created by the ALIYUN service background automatically, then the rc1 will work fine.

**Comment by ShannonDing** [comment]
link #404

**Comment by zhangxinghao** [comment]
@ShannonDing  Thanks, `go get github.com/apache/rocketmq-client-go/v2@af4067cae785c6e632df9f0f5c689e7d5aa86646`  works for me
