### ISSUE TITLE
[Native] Send message error.

### ISSUE THREAD

**Issue by Yarollingstone** [apache/rocketmq-client-go#435]
version: 1.2.4
os：centos 7
gcc: 4.8.5
When I have used go goroutines to  invoke the 'rocketmq.SendMessageSync' API .    When Send 1500 messages at a time, it always reported error 'runtime error: invalid memory address or nil pointer dereference'.
Here is my call method and error log
![image](https://user-images.githubusercontent.com/40456822/75448040-770c6b80-59a5-11ea-8c11-f0bceb4617a3.png)
![image](https://user-images.githubusercontent.com/40456822/75448093-90adb300-59a5-11ea-95ea-cc70804f5c67.png)

**Comment by xujianhai666** [comment]
@Yarollingstone there is no msg found, could u support more info?
