### ISSUE TITLE
[Native] ERRO[0003] consumer start failed

### ISSUE THREAD

**Issue by duffiye** [apache/rocketmq-client-go#440]
consumer start failed 

ERRO[0003] get consumer list of group from broker error  broker="192.168.2.210:10911" consumerGroup=ZB_WALLET_GROUP underlayError="service close is not running, please check"

telnet 192.168.2.210 10911, result connected

server config incorrect ?

**Comment by xujianhai666** [comment]
@duffiye  "service close is not running, please check" is internal err, that info just mean `get consumer list` failed. but are u sure ur consumer start failed ?

**Comment by duffiye** [comment]
start failed, maybe SDK can not autocreate group, topic.
