### ISSUE TITLE
[Native] Any More ERRO details console log?

### ISSUE THREAD

**Issue by duffiye** [apache/rocketmq-client-go#443]
when comsumer start, sometimes can get error log in console, why? can we get more details?
ERRO[0124] io ReadFull error when read header            underlayError=EOF
ERRO[0124] conn error, close connection                  underlayError=EOF
ERRO[0125] io ReadFull error when read header            underlayError=EOF
ERRO[0125] conn error, close connection                  underlayError=EOF
ERRO[0127] io ReadFull error when read header            underlayError=EOF
ERRO[0127] conn error, close connection                  underlayError=EOF
ERRO[0128] io ReadFull error when read header            underlayError=EOF
ERRO[0128] conn error, close connection                  underlayError=EOF

**Comment by xujianhai666** [comment]
@duffiye that is golang socket failed info, maybe we should ignore this err
