### ISSUE TITLE
[Native]use Aliyun RocketMQ,all topic not exist

### ISSUE THREAD

**Issue by Xsxdot** [apache/rocketmq-client-go#447]
1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
send message use aliyun RocketMQ
    - What did you expect to see?
send success
    - What did you see instead?
WARN[0002] query topic route from server error           underlayError="topic not exist"
WARN[0002] queryTopicRouteInfoFromServer return nil      topic=L*****V

2. Please tell us about your environment:

     - What is your OS?
Mac OS 10.15
     - What is your client version?
2.0.0 rc-1
     - What is your RocketMQ version?
Aliyun RocketMQ
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
all topic can't use,I have already created by aliyun console

**Comment by Xsxdot** [comment]
![截屏2020-03-16下午7 28 30](https://user-images.githubusercontent.com/24730668/76754045-71dc5880-67bc-11ea-859b-4c4eb7ae7f08.png)

**Comment by ShannonDing** [comment]
set NameSpace using WithNameSpace(MQ_INST_XXXXXXX)
https://github.com/apache/rocketmq-client-go/tree/native/examples/producer/namespace

**Comment by Xsxdot** [comment]
Thanks,it worked!
