### ISSUE TITLE
[Native] "send heart beat to broker error" underlayError="request timeout"

### ISSUE THREAD

**Issue by lxm** [apache/rocketmq-client-go#448]
The issue tracker is **ONLY** used for the go client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
     produce/consumer msgs 
    - What did you expect to see?
     no error
    - What did you see instead?
     time="2020-03-16T15:38:53Z" level=warning msg="send heart beat to broker error" underlayError="request timeout"
2. Please tell us about your environment:

     - What is your OS?
       linux(docker ubuntu)
     - What is your client version?
      v2.0.0-rc2.0.20200311112413-1ce9fd9c6cb6 (lastest native branch)
     - What is your RocketMQ version?
      aliyun public cloud
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

    - [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
    - [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
    - ...

**Comment by lxm** [comment]
tested with latest native version, still report this error

**Comment by lxm** [comment]
update



broker data

```
{
    "OrderTopicConf":"",
    "queueDatas":[
        {
            "brokerName":"qd8internet-02",
            "readQueueNums":8,
            "writeQueueNums":8,
            "perm":6,
            "topicSynFlag":0
        },
        {
            "brokerName":"qd8internet-03",
            "readQueueNums":8,
            "writeQueueNums":8,
            "perm":6,
            "topicSynFlag":0
        },
        {
            "brokerName":"qd8internet-01",
            "readQueueNums":8,
            "writeQueueNums":8,
            "perm":6,
            "topicSynFlag":0
        }
    ],
    "brokerDatas":[
        {
            "cluster":"qd8internet",
            "brokerName":"qd8internet-02",
            "brokerAddrs":{
                "0":"broker2-01:80",
                "1":"broker2-02:80"
            }
        },
        {
            "cluster":"qd8internet",
            "brokerName":"qd8internet-01",
            "brokerAddrs":{
                "0":"broker1-01:80",
                "1":"broker1-02:80"
            }
        },
        {
            "cluster":"qd8internet",
            "brokerName":"qd8internet-03",
            "brokerAddrs":{
                "0":"broker3-01:80",
                "1":"broker3-02:80"
            }
        }
    ]
}
```

```
WARN[1384] send heart beat to broker error               addr="broker1-02:80" id=1 underlayError="request timeout"
WARN[1387] send heart beat to broker error               addr="broker2-02:80" id=1 underlayError="request timeout"
WARN[1390] send heart beat to broker error               addr="broker3-02:80" id=1 underlayError="request timeout"

```

**Comment by bygzyz** [comment]
Got the same issue，anyone solve this problem？

rocketmq server and broker run normal and i use python client send/recevie message works，but i use go client got the error message：time="2024-03-24T11:40:09+08:00" level=warning msg="send heart beat to broker error" underlayError="dial tcp 172.19.0.3:10911: i/o timeout"
