### ISSUE TITLE
[Master] go build error

### ISSUE THREAD

**Issue by hanzhonghua0927** [apache/rocketmq-client-go#458]
../../vendor/github.com/apache/rocketmq-client-go/core/message.go:89:29: could not determine kind of name for C.GetOriginDelayTimeLevel
../../vendor/github.com/apache/rocketmq-client-go/core/message.go:88:26: could not determine kind of name for C.GetOriginMessageBody
../../vendor/github.com/apache/rocketmq-client-go/core/message.go:87:26: could not determine kind of name for C.GetOriginMessageKeys
../../vendor/github.com/apache/rocketmq-client-go/core/message.go:50:20: could not determine kind of name for C.GetOriginMessageProperty
../../vendor/github.com/apache/rocketmq-client-go/core/message.go:86:26: could not determine kind of name for C.GetOriginMessageTags
../../vendor/github.com/apache/rocketmq-client-go/core/message.go:85:27: could not determine kind of name for C.GetOriginMessageTopic

**Comment by hanzhonghua0927** [comment]
For help

**Comment by ShannonDing** [comment]
did you install the cpp core?

**Comment by hanzhonghua0927** [comment]
> did you install the cpp core?

yes  cpp is The latest master

**Comment by ShannonDing** [comment]
did you update the header file of CPP?

**Comment by hanzhonghua0927** [comment]
> did you update the header file of CPP?

no, What do you mean

**Comment by hanzhonghua0927** [comment]
> > did you update the header file of CPP?
> 
> no, What do you mean

how can i update the header file of CPP

**Comment by ShannonDing** [comment]
> > > did you update the header file of CPP?
> > 
> > 
> > no, What do you mean
> 
> how can i update the header file of CPP

introduction：
https://github.com/apache/rocketmq-client-go/blob/master/doc/Introduction.md
