### ISSUE TITLE
go-process abort when no topic in MQ-Cluster

### ISSUE THREAD

**Issue by appendHan** [apache/rocketmq-client-go#46]
When the MQ-cluster does not have any topics, call the SendMessageSync method will cause the GO-program to directly interrupt the exit.
stderr like this:
terminate called after throwing an instance of 'rocketmq::MQException'
what():msg:No route info of this topic,,error:in file </home/jonnxu/git/rocketmq-client-cpp/src/producer/DefaultMQProducer.cpp> line:319
terminate called recursively
SIGABRT:abort
PC=xxxxx

Can you catch that Exception to error, don't let the go-program exit directly?

**Comment by wenfengwang** [comment]
please track [2.0.0 Production Ready Road map](https://github.com/apache/rocketmq-client-go/issues/57)

**Comment by wenfengwang** [comment]
The Go client in pure go has more feature, welcome have a try, and The 2.0.0-alpha2 is preparing to release, the release note: https://github.com/apache/rocketmq-client-go/pull/121. and can download in page: https://github.com/apache/rocketmq-client-go/releases
