### ISSUE TITLE
The message mode was wrong in the heartbeat data.

### ISSUE THREAD

**Issue by DandelionJR** [apache/rocketmq-client-go#471]
我在测试rocketmq时，消费者订阅采用的是BROADCASTING，页面上却显示为CLUSTERING。我在源码中仔细查找，发现写死CLUSTERING，如下所示：
c.consumerMap.Range(func(key, value interface{}) bool { consumer := value.(InnerConsumer) cData := consumerData{ GroupName: key.(string), CType: "PUSH", MessageModel: "CLUSTERING", Where: "CONSUME_FROM_FIRST_OFFSET", UnitMode: consumer.IsUnitMode(), SubscriptionDatas: consumer.SubscriptionDataList(), } hbData.ConsumerDatas.Add(cData) return true })
这段代码在internal.client.go的SendHeartbeatToAllBrokerWithLock中，当我改变MessageModel的值为BROADCASTING时，页面上显示为BROADCASTING，请问这是bug还是我自己测试错误

**Comment by ShannonDing** [comment]
yes, It is a bug. the message mode should be getting from the inner client and set here in the heartbeat data. then it will be sent to the broker.
Could you pls create a PR to fix it?

**Comment by DandelionJR** [comment]
Ok, I'm looking at the interface method of the inner client. I haven't found where the model is, but I can clearly find it from the debug. I want to study it furtherly.

**Comment by ShannonDing** [comment]
Maybe you can refer to the implementation logic of IsUnitMode().

**Comment by DandelionJR** [comment]
Thanks, i know how to solve it

**Comment by DandelionJR** [comment]
I have solved this problem, you can review it, thanks

**Comment by ShannonDing** [comment]
GJ, I find that you create a PR on the release 2.0.0 branch, could you please move this PR to the native branch?
we should not modify the branch which has been released.
