### ISSUE TITLE
Error: send message with sync failed

### ISSUE THREAD

**Issue by wjw1758548031** [apache/rocketmq-client-go#485]
producer, err := rocketmq.NewProducer(config)
	if err != nil {
		fmt.Println("create common producer failed, error:", err)
		return
	}
	//请确保参数设置完成之后启动 Producer。
	err = producer.Start()
	if err != nil {
		fmt.Println("start common producer error", err)
		return
	}
	defer producer.Shutdown()
	fmt.Printf("Common producer: %s started... \n", producer)
	for i := 0; i < 10; i++ {
		msg := fmt.Sprintf("%s-%d", "Hello,Common MQ Message-", i)
		//发送消息时请设置您在阿里云 RocketMQ 控制台上申请的 Topic。
		result, err := producer.SendMessageSync(&rocketmq.Message{Topic: "TopTest", Body: msg})
		if err != nil {
			fmt.Println("Error:", err)
		}
		fmt.Printf("send message: %s result: %s\n", msg, result)
	}
	fmt.Println("shutdown common producer.")
执行上面的程序，配置都是填对了然后执行就是发送失败，而且我故意再把配置填错，使用Start()的时候，也不会有事，都是出现在发送消息的时候说发送失败，这是为什么呢。如何解决这个问题呢。

Error: send message with sync failed

**Comment by wjw1758548031** [comment]
直接换成公网地址试一试就好了，阿里云不能通过账号登陆直接去连接内网的tcp，除非都是一个内网的服务器

**Comment by leeyisoft** [comment]
config 需要配置哪些项目，参数名称是啥，能否贴出来一下？（我现在用 rocketmq-client-go 链接阿里云MQ 不知道如何配置）

**Comment by shencw** [comment]
> 直接换成公网地址试一试就好了，阿里云不能通过账号登陆直接去连接内网的tcp，除非都是一个内网的服务器

我现在也遇到了这个问题，但是我的配置设置的也是内网，却还是提示失败。。

WARN[0049] send message error, error is: send message with sync failed
