### ISSUE TITLE
can't take effect with aliyun rocketmq

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/rocketmq-client-go#486]
When i try to communicate with aliyun rocketmq using rocketmq-client-go sdk, i always get errors:
```
WARN[0000] query topic route from server error           underlayError="topic not exist"
WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
WARN[0000] query topic route from server error           underlayError="topic not exist"
WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
WARN[0000] query topic route from server error           underlayError="topic not exist"
WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
WARN[0000] query topic route from server error           underlayError="topic not exist"
WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
WARN[0000] query topic route from server error           underlayError="topic not exist"
WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
WARN[0000] query topic route from server error           underlayError="topic not exist"
WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
send message error: the topic=saas-stat-test route info not found

```

Following is my test code snippets, I'm sure all the configs such as endpoints,top and so on are correct. So what's the problem?
```
package main

import (
	"context"
	"fmt"
	"os"

	rocketmq "github.com/apache/rocketmq-client-go/v2"
	"github.com/apache/rocketmq-client-go/v2/primitive"
	"github.com/apache/rocketmq-client-go/v2/producer"
)

func main() {
	p, err := rocketmq.NewProducer(
		producer.WithNameServer([]string{"my correct endpoint"}),
		producer.WithRetry(2),
		producer.WithCredentials(primitive.Credentials{
			AccessKey: "my correct key",
			SecretKey: "my correct secret",
		}),
	)

	if err != nil {
		fmt.Println("init producer error: " + err.Error())
		os.Exit(0)
	}

	err = p.Start()
	if err != nil {
		fmt.Printf("start producer error: %s", err.Error())
		os.Exit(1)
	}
	for i := 0; i < 1; i++ {
		res, err := p.SendSync(
			context.Background(),
			primitive.NewMessage(
				"saas-stat-test",
				[]byte("Hello RocketMQ Go Client!"),
			),
		)

		if err != nil {
			fmt.Printf("send message error: %s\n", err)
		} else {
			fmt.Printf("send message success: result=%s\n", res.String())
		}
	}
	err = p.Shutdown()
	if err != nil {
		fmt.Printf("shutdown producer error: %s", err.Error())
	}
}
```

**Comment by xujianhai666** [comment]
@ShannonDing Is there aliyun rocketmq test env for our dev, I thought I should check that way

**Comment by xujianhai666** [comment]
> When i try to communicate with aliyun rocketmq using rocketmq-client-go sdk, i always get errors:
> 
> ```
> WARN[0000] query topic route from server error           underlayError="topic not exist"
> WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> WARN[0000] query topic route from server error           underlayError="topic not exist"
> WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> WARN[0000] query topic route from server error           underlayError="topic not exist"
> WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> WARN[0000] query topic route from server error           underlayError="topic not exist"
> WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> WARN[0000] query topic route from server error           underlayError="topic not exist"
> WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> WARN[0000] query topic route from server error           underlayError="topic not exist"
> WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> send message error: the topic=saas-stat-test route info not found
> ```
> 
> Following is my test code snippets, I'm sure all the configs such as endpoints,top and so on are correct. So what's the problem?
> 
> ```
> package main
> 
> import (
> 	"context"
> 	"fmt"
> 	"os"
> 
> 	rocketmq "github.com/apache/rocketmq-client-go/v2"
> 	"github.com/apache/rocketmq-client-go/v2/primitive"
> 	"github.com/apache/rocketmq-client-go/v2/producer"
> )
> 
> func main() {
> 	p, err := rocketmq.NewProducer(
> 		producer.WithNameServer([]string{"my correct endpoint"}),
> 		producer.WithRetry(2),
> 		producer.WithCredentials(primitive.Credentials{
> 			AccessKey: "my correct key",
> 			SecretKey: "my correct secret",
> 		}),
> 	)
> 
> 	if err != nil {
> 		fmt.Println("init producer error: " + err.Error())
> 		os.Exit(0)
> 	}
> 
> 	err = p.Start()
> 	if err != nil {
> 		fmt.Printf("start producer error: %s", err.Error())
> 		os.Exit(1)
> 	}
> 	for i := 0; i < 1; i++ {
> 		res, err := p.SendSync(
> 			context.Background(),
> 			primitive.NewMessage(
> 				"saas-stat-test",
> 				[]byte("Hello RocketMQ Go Client!"),
> 			),
> 		)
> 
> 		if err != nil {
> 			fmt.Printf("send message error: %s\n", err)
> 		} else {
> 			fmt.Printf("send message success: result=%s\n", res.String())
> 		}
> 	}
> 	err = p.Shutdown()
> 	if err != nil {
> 		fmt.Printf("shutdown producer error: %s", err.Error())
> 	}
> }
> ```

@UnderTreeTech Is that topic exist?

**Comment by UnderTreeTech** [comment]
> > When i try to communicate with aliyun rocketmq using rocketmq-client-go sdk, i always get errors:
> > ```
> > WARN[0000] query topic route from server error           underlayError="topic not exist"
> > WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> > WARN[0000] query topic route from server error           underlayError="topic not exist"
> > WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> > WARN[0000] query topic route from server error           underlayError="topic not exist"
> > WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> > WARN[0000] query topic route from server error           underlayError="topic not exist"
> > WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> > WARN[0000] query topic route from server error           underlayError="topic not exist"
> > WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> > WARN[0000] query topic route from server error           underlayError="topic not exist"
> > WARN[0000] queryTopicRouteInfoFromServer return nil      topic=saas-stat-test
> > send message error: the topic=saas-stat-test route info not found
> > ```
> > 
> > 
> > Following is my test code snippets, I'm sure all the configs such as endpoints,top and so on are correct. So what's the problem?
> > ```
> > package main
> > 
> > import (
> > 	"context"
> > 	"fmt"
> > 	"os"
> > 
> > 	rocketmq "github.com/apache/rocketmq-client-go/v2"
> > 	"github.com/apache/rocketmq-client-go/v2/primitive"
> > 	"github.com/apache/rocketmq-client-go/v2/producer"
> > )
> > 
> > func main() {
> > 	p, err := rocketmq.NewProducer(
> > 		producer.WithNameServer([]string{"my correct endpoint"}),
> > 		producer.WithRetry(2),
> > 		producer.WithCredentials(primitive.Credentials{
> > 			AccessKey: "my correct key",
> > 			SecretKey: "my correct secret",
> > 		}),
> > 	)
> > 
> > 	if err != nil {
> > 		fmt.Println("init producer error: " + err.Error())
> > 		os.Exit(0)
> > 	}
> > 
> > 	err = p.Start()
> > 	if err != nil {
> > 		fmt.Printf("start producer error: %s", err.Error())
> > 		os.Exit(1)
> > 	}
> > 	for i := 0; i < 1; i++ {
> > 		res, err := p.SendSync(
> > 			context.Background(),
> > 			primitive.NewMessage(
> > 				"saas-stat-test",
> > 				[]byte("Hello RocketMQ Go Client!"),
> > 			),
> > 		)
> > 
> > 		if err != nil {
> > 			fmt.Printf("send message error: %s\n", err)
> > 		} else {
> > 			fmt.Printf("send message success: result=%s\n", res.String())
> > 		}
> > 	}
> > 	err = p.Shutdown()
> > 	if err != nil {
> > 		fmt.Printf("shutdown producer error: %s", err.Error())
> > 	}
> > }
> > ```
> 
> @UnderTreeTech Is that topic exist?

Absolutely.

**Comment by wenfengwang** [comment]
@UnderTreeTech There is some advice for you may useful:
1.  Can the network of your go-client instance establish with Aliyun RocketMQ instance?
2. Is AK/SK correct?

**Comment by UnderTreeTech** [comment]
@wenfengwang I'm sure the network works and all mq configs are correct.

**Comment by wenfengwang** [comment]
> @wenfengwang I'm sure the network works and all mq configs are correct.

use this option when create producer/consumer instance:  https://github.com/apache/rocketmq-client-go/blob/6b7f96c1a217e2ce9915d2fbbbdcb5c527a05f81/consumer/option.go#L187,  the argument is '实例ID' in the pic: 
![image](https://user-images.githubusercontent.com/9766821/81780180-afddca80-9528-11ea-8b79-713dac33b602.png)

refer from: https://help.aliyun.com/document_detail/146599.html?spm=a2c4g.11186623.6.544.1cd777fcnOrpPh

**Comment by ShannonDing** [comment]
package main

import (
	"context"
	"fmt"
	"github.com/apache/rocketmq-client-go/v2"
	"github.com/apache/rocketmq-client-go/v2/primitive"
	"github.com/apache/rocketmq-client-go/v2/producer"
	"math/rand"
	"os"
	"time"
)
func main() {
	var endPoint = []string{"http://MQ_INST_XXXXXXX.mq-internet-access.mq-internet.aliyuncs.com:80"}
	var credentials = primitive.Credentials{
		AccessKey: “AK”,
		SecretKey: “SK”,
	}
	p, err := rocketmq.NewProducer(
		producer.WithNameServer(endPoint),
		//producer.WithNsResovler(primitive.NewPassthroughResolver(endPoint)),
		producer.WithGroupName("GID_XXXXXXXXX”),
		**producer.WithNamespace("MQ_INST_XXXXXXXX”),**
		producer.WithCredentials(credentials),
		producer.WithTrace(&primitive.TraceConfig{
			GroupName:    "GID_XXXXXXX”,
			Access:       primitive.Cloud,
			NamesrvAddrs: endPoint,
			Credentials:  credentials,
		}),
	)

	if err != nil {
		fmt.Println("init producer error: " + err.Error())
		os.Exit(0)
	}

	err = p.Start()
	if err != nil {
		fmt.Printf("start producer error: %s", err.Error())
		os.Exit(1)
	}
	for i := 0; i < 3; i++ {
		res, err := p.SendSync(context.Background(), primitive.NewMessage(“XXXXXXXXXX”,
			[]byte("Hello RocketMQ Go Client!")))

		if err != nil {
			fmt.Printf("send message error: %s\n", err)
		} else {
			fmt.Printf("send message success: result=%s\n", res.String())
		}
		time.Sleep(200 * time.Millisecond)
	}
	time.Sleep(1000 * time.Millisecond)
	err = p.Shutdown()
	if err != nil {
		fmt.Printf("shutdown producer error: %s", err.Error())
	}
}
func getRandomString(l int) string {
	str := "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
	bytes := []byte(str)
	result := []byte{}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	for i := 0; i < l; i++ {
		result = append(result, bytes[r.Intn(len(bytes))])
	}
	return string(result)
}

**Comment by UnderTreeTech** [comment]
@ShannonDing Cool, it works. It can produce and consume.👍👍👍

**Comment by chidaobanjiu** [comment]
@ShannonDing just solved this problem, but anyone explanation why this work? what's the meaning for this option "Namespace". thanks
