### ISSUE TITLE
rocketmq-client-go consumer restart with shutdown and start

### ISSUE THREAD

**Issue by navychi** [apache/rocketmq-client-go#497]
rmqClient will put into clientMap(sync.Map) when create a new GetOrNewRocketMQClient.
![image](https://user-images.githubusercontent.com/43361137/83586375-d5398380-a57e-11ea-91e5-9663834c49d2.png)

But rmqClient did not remove when shutdown consumer.
![image](https://user-images.githubusercontent.com/43361137/83586443-087c1280-a57f-11ea-86ed-044ff730d456.png)

So if I want to shutdown the consumer. And then re-start consumer again(Required by business logic), The new consumer will use old connection which is closed. 
So if I want to realization consumer restart logic. Will it be supported in the future. or The Architecture design is like this which not ready to support consumer restart logic.

**Comment by YiyangLin** [comment]
Same problem here.

**Comment by maixiaohai** [comment]
@YiyangLin @navychi This has been fixed.
