### ISSUE TITLE
How to set consume thread nums?

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/rocketmq-client-go#499]
In Java SDK, it can set consume thread nums by property, like
```
 properties.setProperty(PropertyKeyConst.ConsumeThreadNums,"20");
```
Does Go SDK support this features? If it is, how to config the parameter?

**Comment by ttwanzai** [comment]
did you get the answer? I am looking for the way to set consume thread nums in go SDK but noway

**Comment by UnderTreeTech** [comment]
> did you get the answer? I am looking for the way to set consume thread nums in go SDK but noway

Go SDK use goroutines to consume messages concurrently, you can find that by reading source code.
