### ISSUE TITLE
core\api.go:32:20: undefined: LogConfig

### ISSUE THREAD

**Issue by mumushuiding** [apache/rocketmq-client-go#50]
rocketmq-client-cpp已经安装，
 在windows上测试时报：core\api.go:32:20: undefined: LogConfig

**Comment by wenfengwang** [comment]
please track [2.0.0 Production Ready Road map](https://github.com/apache/rocketmq-client-go/issues/57)

**Comment by wenfengwang** [comment]
The Go client in pure go has more feature, welcome have a try, and The 2.0.0-alpha2 is preparing to release, the release note: https://github.com/apache/rocketmq-client-go/pull/121. and can download in page: https://github.com/apache/rocketmq-client-go/releases

**Comment by ShannonDing** [comment]
please refer to https://github.com/apache/rocketmq-client-go/releases/tag/2.0.0-alpha2

**Comment by seanyinx** [comment]
@wenfengwang do you have any solution to this issue before native rocket-mq-go-client is production ready?

**Comment by wenfengwang** [comment]
@seanyinx Could I have a discussion with you in wechat? my wechat ID is: sxian1994

**Comment by seanyinx** [comment]
@mumushuiding 
i solved my issue by simply adding `export CGO_ENABLED=1`, before building my go project.
