### ISSUE TITLE
[v2.1.0-rc3] 使用NewPushConsumer，阿里云mq,隔几天就发生一次消费堆积 bug

### ISSUE THREAD

**Issue by giifast** [apache/rocketmq-client-go#500]
启用了5个消费节点，经常出现的报错有
1、 Msg: map[underlayError:request timeout], Err: query topic route from server error
2、Err: connect to namesrv failed.
3、Err: queryTopicRouteInfoFromServer return nil

从节点信息看，即使报错了，数据还在继续消费，但是偶尔，几天就发生一次消费堆积，但是客户端还在继续消费，阿里云后台看到堆积了，代码如下
err := r.Consumer.Subscribe(r.Config.Topic, rocketC.MessageSelector{}, func(ctx context.Context, msgs ...*RespMessage) (rocketC.ConsumeResult, error) {
		consumerFunc(msgs)
		return rocketC.ConsumeSuccess, nil
	})
	if err != nil {
		return err
	}

	<-ctx.Done()
	consumer.Shutdown()

代码处理这里应该没有堆积的可能，收到 msg 就丢到协程了，麻烦看下可能是什么原因导致的堆积？

**Comment by liangyuanpeng** [comment]
建议阿里云的MQ直接提工单比较好,

**Comment by clllanqing** [comment]
> 启用了5个消费节点，经常出现的报错有
> 1、 Msg: map[underlayError:request timeout], Err: query topic route from server error
> 2、Err: connect to namesrv failed.
> 3、Err: queryTopicRouteInfoFromServer return nil
> 
> 从节点信息看，即使报错了，数据还在继续消费，但是偶尔，几天就发生一次消费堆积，但是客户端还在继续消费，阿里云后台看到堆积了，代码如下
> err := r.Consumer.Subscribe(r.Config.Topic, rocketC.MessageSelector{}, func(ctx context.Context, msgs ...*RespMessage) (rocketC.ConsumeResult, error) {
> consumerFunc(msgs)
> return rocketC.ConsumeSuccess, nil
> })
> if err != nil {
> return err
> }
> 
> ```
> <-ctx.Done()
> consumer.Shutdown()
> ```
> 
> 代码处理这里应该没有堆积的可能，收到 msg 就丢到协程了，麻烦看下可能是什么原因导致的堆积？



> 启用了5个消费节点，经常出现的报错有
> 1、 Msg: map[underlayError:request timeout], Err: query topic route from server error
> 2、Err: connect to namesrv failed.
> 3、Err: queryTopicRouteInfoFromServer return nil
> 
> 从节点信息看，即使报错了，数据还在继续消费，但是偶尔，几天就发生一次消费堆积，但是客户端还在继续消费，阿里云后台看到堆积了，代码如下
> err := r.Consumer.Subscribe(r.Config.Topic, rocketC.MessageSelector{}, func(ctx context.Context, msgs ...*RespMessage) (rocketC.ConsumeResult, error) {
> consumerFunc(msgs)
> return rocketC.ConsumeSuccess, nil
> })
> if err != nil {
> return err
> }
> 
> ```
> <-ctx.Done()
> consumer.Shutdown()
> ```
> 
> 代码处理这里应该没有堆积的可能，收到 msg 就丢到协程了，麻烦看下可能是什么原因导致的堆积？

你好，找到问题所在了么
