### ISSUE TITLE
windows环境下一直报mingw32/bin/ld.exe: cannot find -lrocketmq

### ISSUE THREAD

**Issue by mumushuiding** [apache/rocketmq-client-go#51]
windows环境下一直报mingw32/bin/ld.exe: cannot find -lrocketmq

**Comment by 15332318109** [comment]
配置文件发一下

**Comment by mumushuiding** [comment]
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lt\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\lt\go;D:\Workspaces\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\lt\AppData\Local\Temp\go-build822932370=/tmp/go-build -gno-record-gcc-switches

**Comment by mumushuiding** [comment]
已经将rocketmq-client-cpp对应windows的lib文件rocketmq.lib和rocketmq.dll放到C:\usr\local\lib下

**Comment by mumushuiding** [comment]
我在windows下的操作顺序：
1.将rocketmq.lib和rocketmq.dll放到C:\usr\local\lib下
2.go get github.com/apache/rocketmq-client-go
3.进入rocketmq-client-go/examples目录
4.go build
报错：-mingw32/bin/ld.exe: skipping incompatible /usr/local/lib\rocketmq.lib when searching for -lrocketmq
5.set GOOS=linux
6.go build
报错：..\core\api.go:32:20: undefined: LogConfig

真是难，没招了

**Comment by wenfengwang** [comment]
We have very sorry to not to test cgo code on windows platform, the alpha version of pure go implementation of RocketMQ Client will be released on next week, welcome to have a try in the future :)~

**Comment by 15332318109** [comment]
I want to contribute to Apache rocketmq.
Would you please give me the contributor permission?
My JIRA ID is wenbo.sun   


发件人： wenfeng
发送时间： 2019-05-05 14:16
收件人： apache/rocketmq-client-go
抄送： wenbo.sun; Comment
主题： Re: [apache/rocketmq-client-go] windows环境下一直报mingw32/bin/ld.exe: cannot find -lrocketmq (#51)
We have very sorry to not to test cgo code on windows platform, the alpha version of pure go implementation of RocketMQ Client will be released on next week, welcome to have a try in the future :)~
