### ISSUE TITLE
SDK2.0 Cannot using domain for name server

### ISSUE THREAD

**Issue by morysky** [apache/rocketmq-client-go#511]
I am a SDK 1.0 user, this time I want to migrate to V2.0 rc3.

But I stucked firstly, because I cannot initialize Producer, it shows error that "IP addr error".

I can use IP address to make it work, but it's too shame.

**Comment by lpb-007** [comment]
I also have the same problem. I cannot use the domain name to connect to the server. Have you solved the problem?

**Comment by wuhongbing** [comment]
I also encountered this problem, did you solve it?

**Comment by Zfzlv** [comment]
I also have the same problem. Have somebody  solved the problem? this is ridiculous

**Comment by wenfengwang** [comment]
@wuhongbing @Zfzlv What version you used?

**Comment by Zfzlv** [comment]
@wenfengwang  v2.1.0

**Comment by holdpower** [comment]
有人解决了吗？我也碰到了这个问题。不能解析域名，只能使用ip

**Comment by j-deng** [comment]
> 有人解决了吗？我也碰到了这个问题。不能解析域名，只能使用ip

http://domainname;http://other.domainname

**Comment by holdpower** [comment]
解决了，谢谢

**Comment by littleantfly** [comment]
> 



> 决了，谢谢

怎么解决的？

**Comment by holdpower** [comment]
在域名前加  http://  或者 https://
