### ISSUE TITLE
panic when pullconsumer started.

### ISSUE THREAD

**Issue by edgar1992** [apache/rocketmq-client-go#513]
报错如下
goroutine 53 [running]:
sync.(*Mutex).Lock(...)
	/Users/luzhenfei/WorkSpace/go/src/sync/mutex.go:74
github.com/apache/rocketmq-client-go/internal.(*namesrvs).cleanOfflineBroker(0x0)
	/Users/luzhenfei/WorkSpace/src/github.com/apache/rocketmq-client-go/internal/route.go:55 +0x2d
github.com/apache/rocketmq-client-go/internal.(*rmqClient).Start.func1.3.1()
	/Users/luzhenfei/WorkSpace/src/github.com/apache/rocketmq-client-go/internal/client.go:314 +0x36
github.com/apache/rocketmq-client-go/internal.(*rmqClient).Start.func1.3()
	/Users/luzhenfei/WorkSpace/src/github.com/apache/rocketmq-client-go/internal/client.go:319 +0x79
github.com/apache/rocketmq-client-go/primitive.WithRecover(0xc00001f120)
	/Users/luzhenfei/WorkSpace/src/github.com/apache/rocketmq-client-go/primitive/base.go:96 +0x4d
created by github.com/apache/rocketmq-client-go/internal.(*rmqClient).Start.func1
	/Users/luzhenfei/WorkSpace/src/github.com/apache/rocketmq-client-go/internal/client.go:312 +0x16d

问题定位为pullconsumer 初始化过程中漏了 defaultOpts.Namesrv = srvs
![image](https://user-images.githubusercontent.com/8499494/88024111-c3c72d80-cb64-11ea-9002-12008102c0fd.png)

**Comment by ShannonDing** [comment]
A PR to fix this issue is welcomed. @edgar1992
