### ISSUE TITLE
咨询一下，将部分内容封装在internal包是出于什么目的。

### ISSUE THREAD

**Issue by murDDock** [apache/rocketmq-client-go#518]
我看rocketmq-client-java中，client是支持比如TopicPublishInfo一些信息的查询以及与namesever的交互的，但是由于internal包，哪怕我自己去实现相应的SendMessageRequestHeader，也没办法去应用。
虽然开源版本目前没有admin,但是到时候这部分内容会去支持吗？
还是在internal包中的信息就不去做支持了。

**Comment by ShannonDing** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about Apache RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address] (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
