### ISSUE TITLE
FindBrokerAddrByName parameter problem？

### ISSUE THREAD

**Issue by xly0713** [apache/rocketmq-client-go#533]
https://github.com/apache/rocketmq-client-go/blob/3d5dab0405228dda740554a04ab06263e8e99e7d/consumer/consumer.go#L932

如上代码行，传参是否有误？是否应该传参**mq.BrokerName**？

**Comment by vongosling** [comment]
Thank you very much for your review. There are some problems here. Would you like to help PR here?
