### ISSUE TITLE
重启的时候会有大量重复消费

### ISSUE THREAD

**Issue by sdgmf** [apache/rocketmq-client-go#534]
单机10000QPS，rocketmq consumer 重启的时候会有大量重复消费，这个可以通过参数配置避免吗？可以容忍丢失消息。

**Comment by sdgmf** [comment]
目前参数配置
        c, err := rocketmq.NewPushConsumer(
		consumer.WithGroupName(o.ConsumerGroup),
		consumer.WithNameServer(o.NameServer),
		consumer.WithMaxReconsumeTimes(0),
		consumer.WithPullBatchSize(32),
		consumer.WithConsumeMessageBatchMaxSize(1),
		consumer.WithAutoCommit(true),
	)

**Comment by vongosling** [comment]
No, data loss is not allowed by design. As to duplicated messages, you could check the FromWhere logic to verify your case.
