### ISSUE TITLE
receive broker's requests, but no func to handle  responseCode=309

### ISSUE THREAD

**Issue by fwhezfwhez** [apache/rocketmq-client-go#542]
Sometimes receive this responseCode, and don't know how to fix

{
    "code": 309,
    "language": "GO",
    "version": 355,
    "opaque": 92004948,
    "flag": 0,
    "remark": "",
    "extFields": {
      "brokerName": "broker-a",
      "clientId": "xxxxx",
      "consumerGroup": "default%GID_xyx_srv",
      "msgId": "5144ABED00002A9F000000000014E9FD"
    }
  }

**Comment by Happyzmq** [comment]
I also encountered the same problem, have you solved this problem?

**Comment by ShannonDing** [comment]
public static final int CONSUME_MESSAGE_DIRECTLY = 309;
Just ignore it.
