### ISSUE TITLE
【FEATURE】Refactor design

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq-client-go#565]
more information refer by
https://docs.google.com/document/d/1SovDAthbiD66x4hu5KflEF0Kc8WPnK3sC5ztf8FIdBU/edit?usp=sharing

**Comment by maixiaohai** [comment]
When this feature could be used in production？
Recently we will use go sdk widely, and if it's not compatible, how could we migrate to new version?

**Comment by xujianhai666** [comment]
> When this feature could be used in production？
> Recently we will use go sdk widely, and if it's not compatible, how could we migrate to new version?

we will ensure all interface is compatible

**Comment by maixiaohai** [comment]
> > When this feature could be used in production？
> > Recently we will use go sdk widely, and if it's not compatible, how could we migrate to new version?
> 
> we will ensure all interface is compatible

So nice~
