### ISSUE TITLE
Dose this lib support aliyun rocketmq?

### ISSUE THREAD

**Issue by codinl** [apache/rocketmq-client-go#569]
RT
thanks

**Comment by codinl** [comment]
I use like below, but have the error:  'query topic route from server error" underlayError="topic not exist"'

`	
p, _ := rocketmq.NewProducer(
		producer.WithNameServer([]string{"my url"}),
		producer.WithInstanceName("MY Instance"),
		producer.WithRetry(2),
		producer.WithGroupName("MY GROUP"),
		producer.WithQueueSelector(producer.NewManualQueueSelector()),
		producer.WithCredentials(primitive.Credentials{
			AccessKey: "my AccessKey",
			SecretKey: "my SecretKey",
		}),
		//producer.WithCreateTopicKey("test"),
	)

	err := p.Start()
	if err != nil {
		log.Error().Msgf("start producer error: %s", err.Error())
		os.Exit(1)
	}

	topic := "test"

	for i := 0; i < 10; i++ {
		msg := &primitive.Message{
			Topic: topic,
			Body:  []byte("Hello RocketMQ Go Client! " + strconv.Itoa(i)),
		}
		res, err := p.SendSync(context.Background(), msg)

		if err != nil {
			log.Error().Msgf("send message error: %s\n", err)
		} else {
			log.Error().Msgf("send message success: result=%s\n", res.String())
		}
	}
	err = p.Shutdown()
	if err != nil {
		log.Error().Msgf("shutdown producer error: %s", err.Error())
	}`

**Comment by codinl** [comment]
And the "test" topic exists.

**Comment by ShannonDing** [comment]
see https://github.com/apache/rocketmq-client-go/blob/v1.2.4/examples/producer_orderly.go

**Comment by codinl** [comment]
My imports:

```
	"github.com/apache/rocketmq-client-go/v2"
	"github.com/apache/rocketmq-client-go/v2/primitive"
	"github.com/apache/rocketmq-client-go/v2/producer"
```

**Comment by codinl** [comment]
加了这行后，好了。

```
producer.WithNamespace("实例 ID"),
```

不能理解这个操作。。。。。😳

**Comment by duhenglucky** [comment]
> 加了这行后，好了。
> 
> ```
> producer.WithNamespace("实例 ID"),
> ```
> 
> 不能理解这个操作。。。。。😳
> 
> 难道不应该是：WithInstanceId("xxxxx") ????????????????????

可以支持的，这个就是设置实例id

**Comment by wujuan-glit** [comment]
> 加了这行后，好了。
> 
> ```
> producer.WithNamespace("实例 ID"),
> ```
> 
> 不能理解这个操作。。。。。😳
> 
> 难道不应该是：WithInstanceId("xxxxx") ????????????????????
为什么我加了以后还是报这个错

**Comment by wujuan-glit** [comment]
> 加了这行后，好了。
> 
> ```
> producer.WithNamespace("实例 ID"),
> ```
> 
> 不能理解这个操作。。。。。😳
> 
> 难道不应该是：WithInstanceId("xxxxx") ????????????????????
为什么加上以后 会在主题前面拼接上实例id呢 然后还是显示主题不存在
