### ISSUE TITLE
[native]2.0.0 Production Ready Road map

### ISSUE THREAD

**Issue by wenfengwang** [apache/rocketmq-client-go#57]
**Current Status: preparing to releasing 2.0.0-alpha2**

Link: [RocketMQ Go Client 2.0.0-alpha2 Roadmap](https://github.com/apache/rocketmq-client-go/issues/75)

### 2.0.0-alpha1
- release date: 2019.5.12
- goal: 
    - native implementation of RocketMQ Go Client
    - gather feedback
    - attract more contributors
- include:
    - producer with sync/async
    - consumer with push
    - consuming with concurrently
    - clustering & broadcast
    - load balance
    - offset store 
    - topic route 
    - RocketMQ Protocol & RPC
    
###  2.0.0-alpha2
- goal: 
  - bugfix
  - more features
  - more tests
- include:
  - delay message
  - Hook
  - consuming with orderly
  - statistics
  - message retry when consume failed(sendBack)

###  2.0.0-rc1
- goal:
    - bugfix
    - test

###  2.0.0
- goal: production ready & full feature supported

**Comment by jamesbee** [comment]
终于等到了官方版本的 Pure Go 版本 SDK，CGO 版本的 SDK 在最新的 Golang docker image 里面无法使用，我只能一直找一些古老的 Go 版本 SDK，第一个可用的 Alpha 版本会在什么时候提供呢？

**Comment by wenfengwang** [comment]
@jamesbee The vote of alpha.1 will be proposed today, and if the vote success, the alpha.1 will be released immediately. So, the alpha.1 may be available this week.

**Comment by chxfantasy** [comment]
Are you still developing the pure go client? 
last commit is 24 days ago

**Comment by wenfengwang** [comment]
@chxfantasy yes, but I'm working at 996..., please give me more time :)~

**Comment by chxfantasy** [comment]
> @chxfantasy yes, but I'm working at 996..., please give me more time :)~

poor guy 😂

**Comment by wenfengwang** [comment]
The 2.0.0-alpha2 is preparing to release, the release note: https://github.com/apache/rocketmq-client-go/pull/121. and can download in page: https://github.com/apache/rocketmq-client-go/releases

**Comment by icearith** [comment]
@wenfengwang how can I get an invitation of your slack workspace, thanks.

https://rocketmq-community.slack.com/

**Comment by wenfengwang** [comment]
@icearith join here: https://rocketmq-invite-automation.herokuapp.com/. if you have any question or need help, mail-lists: https://rocketmq.apache.org/about/contact/ or open an issue is prefered.

**Comment by chxfantasy** [comment]
> The 2.0.0-alpha2 is preparing to release, the release note: #121. and can download in page: https://github.com/apache/rocketmq-client-go/releases

兄弟，rc版啥时候能发布呀，等了半年了，再不发布就3.25了 😂

**Comment by ShannonDing** [comment]
> > The 2.0.0-alpha2 is preparing to release, the release note: #121. and can download in page: https://github.com/apache/rocketmq-client-go/releases
> 
> 兄弟，rc版啥时候能发布呀，等了半年了，再不发布就3.25了 😂

建议一起加入到native的优化中来，把现在的native分支拿下来一起测试一下，发现有问题提下issue一起解决，可以加快发版的进度。

**Comment by ShannonDing** [comment]
ping @all, pre-release for [v2.0.0-alpha3](https://github.com/apache/rocketmq-client-go/releases/tag/v2.0.0-alpha3), please have a try and any feedback will be welcomed.

**Comment by icc99** [comment]
半年了 第二个版本还没发..... 啥时候才有sendOrder 功能

**Comment by phantomk** [comment]
2020 年了，啥时候 rc

**Comment by wenfengwang** [comment]
the [v2.0.0-rc1](please have a try and any feedback will be welcomed.) has been released! please have a try and any feedback will be welcomed.

@icc99 @phantomk  @chxfantasy @icearith @jamesbee

**Comment by ShannonDing** [comment]
close first due to v2.0.0-rc1.
