### ISSUE TITLE
when is store offset.json.bak file

### ISSUE THREAD

**Issue by feiquan123** [apache/rocketmq-client-go#572]
useing `BroadCasting`  model.  I find `offset.json.bak` is empty.  I think  it should be updated when consumer's offset is change.

rocketmq-client-go/internal/utils/files.go:75
```go
if err != nil {
	_, err = bakFile.Write(prevContent)
}
```

modify :
```go
if err == nil {
	_, err = bakFile.Write(prevContent)
}
```

**Comment by ShannonDing** [comment]
a new pr is welcomed, and it will be reviewed soon.
