### ISSUE TITLE
trace producer send message with trace message send failed

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq-client-go#581]
**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
       use trace producer to test trace message.
    - What did you expect to see?
       Both normal message and trace message were sended.
    - What did you see instead?
      Only normal message was send, trace message could not found.
2. Please tell us about your environment:

     - What is your OS?

     - What is your client version?
        2.1.0
     - What is your RocketMQ version?
       4.7.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by ShannonDing** [comment]
link: https://github.com/apache/rocketmq-client-go/blob/master/examples/producer/trace/main.go

**Comment by maixiaohai** [comment]
I change the log level and print as follows
```send trace data success:                      SendResult="%!v(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)"```

Then I use **InvokeSync** method to send trace message, it return the **acl exception**. I add Credentials parameters with traceCfg, it worked.
 I'am green to Go language, If the print log `send success` meet our expectation?

**Comment by maixiaohai** [comment]
It maybe caused by we deploy on dledger mode, and version 4.7.0 not support asyn send message.
I will close this issue.
