### ISSUE TITLE
测试过程中报错信息：get consumer list of group from broker error

### ISSUE THREAD

**Issue by daiweihai** [apache/rocketmq-client-go#589]
测试过程中报错信息：get consumer list of group from broker error，查看源码后发现有一个TODO提示：超时机制有问题，rocketmq-client-go现在能用于生产吗？
![rocketmq](https://user-images.githubusercontent.com/16814315/103866534-e7753480-5100-11eb-9a0e-8dd25bc45564.png)

**Comment by mazihao66** [comment]
遇到了同样的问题，请问怎么解决的
