### ISSUE TITLE
How to limit consumer rate for a certain topic?

### ISSUE THREAD

**Issue by fwhezfwhez** [apache/rocketmq-client-go#593]
I've initialized a global consumer in go project, and I use it to subscribe many topics.

Now I want some of my topics consumed 100 messages per push behavior. Each push action should have 10 seconds intervel at least.

I want only some of topics work like this......

**Comment by maixiaohai** [comment]
Hi you may try this method consumer.WithConsumeMessageBatchMaxSize

**Comment by fwhezfwhez** [comment]
> Hi you may try this method consumer.WithConsumeMessageBatchMaxSize

It seems I should initialize many consumer instances...

A consumer instance can subscribe many topics, but this consumer instance seems can't configurate specific scheme for different topics.

**Comment by ShannonDing** [comment]
close  due to that the client does not implement an accurate flow limiting module
