### ISSUE TITLE
undefined: consumer.WithNsResovler?

### ISSUE THREAD

**Issue by DwenSir** [apache/rocketmq-client-go#594]
consumer, e := rocketmq.NewPushConsumer(
		consumer.WithGroupName(config.consumerGroup),
		consumer.WithNsResovler(primitive.NewPassthroughResolver([]string{config.NameSrv})),
		consumer.WithCredentials(primitive.Credentials{
			AccessKey: config.AccessKey,
			SecretKey: config.SecretKey,
		}),
		consumer.WithNamespace("default"),
	)
console: undefined: consumer.WithNsResovler
go 1.12

**Comment by ShannonDing** [comment]
it seems a typo in "WithNsResovler",  link https://github.com/apache/rocketmq-client-go/pull/554

**Comment by cuibaiyi** [comment]
undefined: producer.WithNsResolver
undefined: primitive.NewPassthroughResolver
