### ISSUE TITLE
[Benchmark] [Enhancement] Fix benchmark command execute failed, add producer and consumer client code

### ISSUE THREAD

**Issue by maixiaohai** [apache/rocketmq-client-go#596]
1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
           use benchmark demo to test
          
              cd benchmark
              go build
              ./benchmark 

    - What did you expect to see?
          some Usage of command
    - What did you see instead?
         
```
          panic: consumer command existed
          
          goroutine 1 [running]:
          main.registerCommand(0x4e54b0, 0x8, 0x508240, 0xc0000c8000)
	          /home/zhangxu/workspace/rocketmq-client-go-community/benchmark/main.go:41 +0x16c
          main.init.2()
	          /home/zhangxu/workspace/rocketmq-client-go-community/benchmark/producer.go:119 +0x2f9
  ```      
2. Please tell us about your environment:

     - What is your OS?
          Centos 7
     - What is your client version?
          2.1.0
     - What is your RocketMQ version?
         4.7.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
    (1) the produer command register 'consumer' 
![image](https://user-images.githubusercontent.com/3734319/105324433-617be200-5c06-11eb-93b8-c8c0a6af3a3a.png)

    (2) the producer and consumer code has been commented, it will never send or consumer messages.
![image](https://user-images.githubusercontent.com/3734319/105324580-8ff9bd00-5c06-11eb-8748-d3514d9fbd7a.png)

**Comment by ShannonDing** [comment]
link #597
