### ISSUE TITLE
concurrently sync send message sometimes will have error the topic= route info not found 

### ISSUE THREAD

**Issue by juyuancai** [apache/rocketmq-client-go#598]
when I start a go client , and conrrently sync send message , it will sometimes show "the topic= route info not found" error ,but not always, can anyone help me what's wrong here? Thank you

**Comment by ShannonDing** [comment]
could you pls add more logs here and share the client version?

**Comment by fnquit** [comment]
code here:
`package main

import (
	"context"
	"fmt"
	"github.com/apache/rocketmq-client-go/v2"
	"github.com/apache/rocketmq-client-go/v2/primitive"
	"github.com/apache/rocketmq-client-go/v2/producer"
	"sync"
	"time"
)

func main() {
	var wg sync.WaitGroup

	for i := 0; i < 2; i ++ {
		wg.Add(1)
		go func() {
			defer func() {
				if r := recover(); r!= nil {
					fmt.Printf("recover: %v\n", r)
				}
			}()
			defer wg.Done()
			produceMsg()
		}()
	}

	wg.Wait()
	time.Sleep(time.Second)

}

func produceMsg() {
	p, err := rocketmq.NewProducer(
		producer.WithNameServer([]string{"localhost:9876"}),
		producer.WithRetry(2),
	)
	if err != nil {
		panic(err)
	}
	err = p.Start()
	defer p.Shutdown()

	fmt.Println("start Produce.")
	topic := "goTestTopic"
	msgStr := "testMsg"
	ctx := context.Background()
	err = p.SendOneWay(ctx, primitive.NewMessage(topic, []byte(msgStr)))
	fmt.Printf("SendSync res: %+v, err: %v\n", err)
	if err != nil {
		fmt.Errorf("err: %v", err)
		return
	}

}
`

-----------------------------------------
result:
the topic=goTestTopic route info not found, err: %!v(MISSING)

version:github.com/apache/rocketmq-client-go/v2 v2.1.0

**Comment by wumingzhidewu** [comment]
I also have the same problem, only occasionally. Did any problems be found in the final investigation?
