### ISSUE TITLE
Produce a few but consume a lot!

### ISSUE THREAD

**Issue by fwhezfwhez** [apache/rocketmq-client-go#601]
Today Consume Count: 20509
Today Produce Count: 86

Broker | NO. | Address | Version | Produce Massage TPS | Consumer Massage TPS | Yesterday Produce Count | Yesterday Consume Count | Today Produce Count | Today Consume Count | Operation
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
broker-a | 0(master) | x.x.x.x.:10911 | V4_8_0 | 0.00 | 0.00 | 646 | 13234 | 86 | 20509 | STATUS

msgPutTotalTodayNow | 928
-- | --
commitLogDiskRatio | 0.005764318949211384
getFoundTps | 0.0 0.0 0.0
EndTransactionThreadPoolQueueCapacity | 100000
sendThreadPoolQueueHeadWaitTimeMills | 0
putMessageDistributeTime | [<=0ms]:0 [0~10ms]:0 [10~50ms]:0 [50~100ms]:0 [100~200ms]:0 [200~500ms]:0 [500ms~1s]:0 [1~2s]:0 [2~3s]:0 [3~4s]:0 [4~5s]:0 [5~10s]:0 [10s~]:0
queryThreadPoolQueueHeadWaitTimeMills | 0
remainHowManyDataToFlush | 0 B
msgGetTotalTodayNow | 34502
commitLogMaxOffset | 417804
queryThreadPoolQueueSize | 0
getMessageEntireTimeMax | 20
msgPutTotalTodayMorning | 842
putMessageTimesTotal | 928
bootTimestamp | 1611197690316
msgGetTotalTodayMorning | 13993
msgPutTotalYesterdayMorning | 196
msgGetTotalYesterdayMorning | 759
pullThreadPoolQueueSize | 0
brokerVersionDesc | V4_8_0
sendThreadPoolQueueSize | 0
startAcceptSendRequestTimeStamp | 0
commitLogMinOffset | 0
putMessageEntireTimeMax | 38
pullThreadPoolQueueHeadWaitTimeMills | 0
runtime | [ 7 days, 9 hours, 48 minutes, 12 seconds ]
earliestMessageTimeStamp | -1
commitLogDirCapacity | Total : 499.8 GiB, Free : 496.9 GiB.
dispatchMaxBuffer | 0
brokerVersion | 373
putTps | 0.0 0.0 0.0
remainTransientStoreBufferNumbs | 2147483647
getMissTps | 0.399720195862896 1.399766705549075 1.563169200567274
queryThreadPoolQueueCapacity | 20000
putMessageAverageSize | 449.7726293103448
getTransferedTps | 0.0 0.0 0.0
dispatchBehindBytes | 0
putMessageSizeTotal | 417389
sendThreadPoolQueueCapacity | 10000
EndTransactionQueueSize | 0
getTotalTps | 0.399720195862896 1.399766705549075 1.563169200567274
pullThreadPoolQueueCapacity | 100000
consumeQueueDiskRatio | 0.005764318949211384
pageCacheLockTimeMills | 0
split | broker-a
index | 0
address | x.x.x.9:10911
brokerName | broker-a

There is only one consumer group of a single node is consuming. 

Topic | SubExpression
-- | --
alarm%alarm_info | prop \|\| server \|\| activity_prop \|\| system
%RETRY%alarm%alarm_platform | *

Help wanted, why the consumed counting is  such different to  produced counting.

**Comment by ShannonDing** [comment]
It is better to post the consumer's implementation code.

**Comment by wenfengwang** [comment]
@fwhezfwhez is there any update?
