### ISSUE TITLE
failed to go get admin pkg

### ISSUE THREAD

**Issue by FlyingOnion** [apache/rocketmq-client-go#603]
**BUG REPORT**  

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
go get github.com/apache/rocketmq-client-go/v2/admin
    - What did you expect to see?
success
    - What did you see instead?
```
go get github.com/apache/rocketmq-client-go/v2/admin: module
github.com/apache/rocketmq-client-go/v2@upgrade found (v2.0.0), but does not contain
package github.com/apache/rocketmq-client-go/v2/admin
```

2. Please tell us about your environment:

     - What is your OS? 
Window 10
     - What is your client version?
go 1.14.7
     - What is your RocketMQ version?

**Comment by ShannonDing** [comment]
is it still failed in the latest 2.1.0 rc?

**Comment by FlyingOnion** [comment]
> is it still failed in the latest 2.1.0 rc?

Yes I'm afraid, because the [v2/admin package](https://pkg.go.dev/github.com/apache/rocketmq-client-go/v2/admin?tab=versions) does not have the same version tags with [main package](https://pkg.go.dev/github.com/apache/rocketmq-client-go/v2?tab=versions).

Adding the version tag will solve, but it is surely better to keep the version tags consistent.
```
PS C:\Users\Administrator> go get github.com/apache/rocketmq-client-go/v2/admin
go get github.com/apache/rocketmq-client-go/v2/admin: module github.com/apache/rocketmq-client-go/v2@upgrade found (v2.0.0), but does not contain package github.com/apache/rocketmq-client-go/v2/admin
```
```
PS C:\Users\Administrator> go get github.com/apache/rocketmq-client-go/v2/admin@v2.1.0-rc5.0.20210115095702-7e36c751e428
go: downloading github.com/apache/rocketmq-client-go/v2 v2.1.0-rc5.0.20210115095702-7e36c751e428
go: found github.com/apache/rocketmq-client-go/v2/admin in github.com/apache/rocketmq-client-go/v2 v2.1.0-rc5.0.20210115095702-7e36c751e428
```

**Comment by netdevops-lucasun** [comment]
好家伙，最新版admin包直接没了

**Comment by FlyingOnion** [comment]
> 好家伙，最新版admin包直接没了

用 `v2.1.0-rc5.0.20210115095702-7e36c751e428` 作为版本号。
