### ISSUE TITLE
PushConsumer 无法消费之前生产的消息

### ISSUE THREAD

**Issue by wjw1758548031** [apache/rocketmq-client-go#606]
代码：

c, err := rocketmq.NewPushConsumer(
		consumer.WithNameServer(primitive.NamesrvAddr{"...."}),
		//producer.WithNsResolver(primitive.NewPassthroughResolver(endPoint)),
		consumer.WithGroupName("...."),
		consumer.WithCredentials(primitive.Credentials{
			AccessKey: "....",
			SecretKey: "...",
		}),
		consumer.WithNamespace("......"),
	)
	if err != nil {
		panic(err)
	}

	err = c.Subscribe("spider_product", consumer.MessageSelector{}, func(ctx context.Context,
		msgs ...*primitive.MessageExt) (consumer.ConsumeResult, error) {
		for i := range msgs {
			fmt.Printf("subscribe callback: %v \n", msgs[i])
		}

		return consumer.ConsumeSuccess, nil
	})
	if err != nil {
		panic(err)
	}
	// Note: start after subscribe
	err = c.Start()
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(-1)
	}
	time.Sleep(time.Hour)
	err = c.Shutdown()
	if err != nil {
		fmt.Printf("shutdown Consumer error: %s", err.Error())
	}

代码如上
相当于只有PushConsumer服务订阅开启后，生产消息才能消费，如果服务没有开启，没有订阅，先去生产消息，在进行订阅,就消费不了，之前的一大推消息都消费不成功

**Comment by bilinxing** [comment]
是不是控制台消息堆积数很大

**Comment by wjw1758548031** [comment]
不是的,就几条消息也不行,只能在我消费端起来的时候，生产消息才有效，您方便留个联系方式么,我想请教下,因为也有可能是我没注意一些情况，不过我确实没发现.

**Comment by bilinxing** [comment]
我也只是在查一个问题，不是维护这个项目的。 不知道你试过WithConsumeFromWhere没有

**Comment by wjw1758548031** [comment]
试过，	
ConsumeFromLastOffset ConsumeFromWhere = iota
ConsumeFromFirstOffset
ConsumeFromTimestamp
这三种都尝试过，还是没有解决问题

**Comment by bilinxing** [comment]
我是接的阿里云，但是发现阿里云控制台一直有消息堆积。而实际上订阅的消息都消费成功了，不知哪里来的堆积。跟你的不是一个问题。

**Comment by wjw1758548031** [comment]
已解决

**Comment by wjw1758548031** [comment]
已解决

**Comment by wjw1758548031** [comment]
是出现了多个消费端的情况

**Comment by duhenglucky** [comment]
@wjw1758548031 那先关闭这个issue，如果有问题的话随时再打开
