### ISSUE TITLE
Can consumer auto-create topics that don't exist?

### ISSUE THREAD

**Issue by SetForU** [apache/rocketmq-client-go#610]
I used v2.1.0-rc5 version to subscribe a topic that does not exist, then consumer will report an error "the topic=XXX route info not found, it may not exist".
So I want consumer can auto-create topics that don't exist, or there is a way to create a topic by myself.
I see a merged issue #515 in branch master，and which release version will support the feature and when will it be released.

**Comment by FlyingOnion** [comment]
Use version tag `v2.1.0-rc5.0.20210115095702-7e36c751e428` could solve. It contains `admin` subpackage.

**Comment by SetForU** [comment]
> Use version tag `v2.1.0-rc5.0.20210115095702-7e36c751e428` could solve. It contains `admin` subpackage.

Thanks, but if create the topic by myself, then I still need a way to determine whether to create a topic.

**Comment by FlyingOnion** [comment]
> > Use version tag `v2.1.0-rc5.0.20210115095702-7e36c751e428` could solve. It contains `admin` subpackage.
> 
> Thanks, but if create the topic by myself, then I still need a way to determine whether to create a topic.

I think you can "always create" topics before producers and consumers (maybe in `func init()`). If the topics already exist just ignore the error.
