### ISSUE TITLE
[Master][Bug] Message lost when consumer failed in consumeOrderly

### ISSUE THREAD

**Issue by qianlongzt** [apache/rocketmq-client-go#618]
in Cluster mode, consume orderly. if consume fail message A, and next message B consume  success, it will make message A lost .

due to https://github.com/apache/rocketmq-client-go/pull/616, put message  only make sure cachedMsgCount right,and forget message A should put back to msgCache.

https://github.com/apache/rocketmq-client-go/blob/c6a314851f8c90cbf753d43d683b22ab0e8bf009/consumer/process_queue.go#L95-L108

Related bugs https://github.com/apache/rocketmq-client-go/issues/615

**Comment by qianlongzt** [comment]
before next release, should resovle this issues

**Comment by jwrookie** [comment]
When will it be merged?

**Comment by maixiaohai** [comment]
> When will it be merged?

merged~
