### ISSUE TITLE
core/api.go:32:20: undefined: LogConfig

### ISSUE THREAD

**Issue by chxfantasy** [apache/rocketmq-client-go#62]
on mac, already installed cpp client

> go build

can work.
But, i want to build a ubuntu version on my mac:

> env CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build 

throws a error: core/api.go:32:20: undefined: LogConfig

How to fix this? 
Thanks

**Comment by derrck** [comment]
I have got this same issue, how did you fixed it?
