### ISSUE TITLE
Unexpected delay count and not-consume-yet record

### ISSUE THREAD

**Issue by fwhezfwhez** [apache/rocketmq-client-go#627]
SubscriptionGroup | Quantity | Version | Type | Mode | TPS | Delay | Operation
-- | -- | -- | -- | -- | -- | -- | --
default%xyx_srv | 4 | V4_5_2 | CONSUME_PASSIVELY | CLUSTERING | 2 | 10104 | CLIENT

I find one of my consumer group got 10104 delay counts.

To well locate its reason, I find message with topic 'xyx_order', tag 'finish_order' will have unconsumed yet record, it's like : 
consumerGroup	trackType	Operation
flink-calculate-group-deploy	NOT_ONLINE	 
flink-calculate-deploy-pay-group	CONSUMED	 
default%gid_xyx_srv_task	CONSUMED	 	 
default%xyx_srv	NOT_CONSUME_YET	 

Ok, here is the question.

I only subscribe topic 'xyx_order', tag 'cancel_order' and never have subscribe tag 'finish_order'. There comes unexpected not-consume-yet record of `xyx_srv - finish_order`.

Is this a bug?

Does this unexpected delay counting need fix?

**Comment by maixiaohai** [comment]
If a message have unsubscrible tag and filtered by consumer, the status should be ```CONSUMED_BUT_FILTERED```
