### ISSUE TITLE
async send message  have error the topic= route info not found

### ISSUE THREAD

**Issue by qpb8023** [apache/rocketmq-client-go#630]
i used java client  send async message success,  but  go sdk  2.1.0  examples async send message error.                                            log info: time="2021-03-21T21:31:05+08:00" level=warning msg="query topic route from server error" underlayError="topic not exist"                                                    send message error: the topic=test route info not found

**Comment by maixiaohai** [comment]
@qpb8023  remove	`producer.WithQueueSelector(producer.NewManualQueueSelector()))`

**Comment by qpb8023** [comment]
> @qpb8023 remove `producer.WithQueueSelector(producer.NewManualQueueSelector()))`
