### ISSUE TITLE
 No enum constant org.apache.rocketmq.remoting.protocol.LanguageCode.GO

### ISSUE THREAD

**Issue by dk-laosiji** [apache/rocketmq-client-go#638]
EXCEPTION:
com.alibaba.fastjson.JSONException: No enum constant org.apache.rocketmq.remoting.protocol.LanguageCode.GO, com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:614)

**Comment by wenfengwang** [comment]
is any update @wcl7592059 ?

**Comment by lastares** [comment]
I have the same problem

**Comment by ShannonDing** [comment]
what's the clent version and the broker version?
