### ISSUE TITLE
Name server does not support domain

### ISSUE THREAD

**Issue by agzou** [apache/rocketmq-client-go#649]
In K8S environment, I use DNS to replace the IP address as the address of name server, for example:``` namesrv-0.namesrv-service.rocketmq: 9876; namesrv-1.namesrv-service.rocketmq: 9876```, but I read the code, name server address must be in the format of an ip address? ``` namesrv-0.namesrv-service.rocketmq: 9876; namesrv-1.namesrv-service.rocketmq: 9876```,it can work in java client
```go
func main(){
	addr, err := primitive.NewNamesrvAddr("namesrv-0.namesrv-service.rocketmq:9876;namesrv-1.namesrv-service.rocketmq:9876")
	if err != nil {
		log.Fatal(err)
	}
	rp, err := rocketmq.NewProducer(producer.WithNameServer(addr))
	if err != nil {
		log.Fatalf("Can not start rocketmq producer:%v", err)
	}
	err = rp.Start()
}
```

**Comment by agzou** [comment]
use http://namesrv-0.namesrv-service.rocketmq: 9876;http://namesrv-1.namesrv-service.rocketmq: 9876

**Comment by ljx0520** [comment]
use http://namesrv-0.namesrv-service.rocketmq:9876;http://namesrv-1.namesrv-service.rocketmq:9876
be careful with the space
