### ISSUE TITLE
2.0.0-alpha1: Produce message success but missing tag and properties.

### ISSUE THREAD

**Issue by easyforgood** [apache/rocketmq-client-go#65]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

Here is my code, it's a producer: 

```
	_msg := kernel.NewMessage(cli.opts.pTopic, body)
	_msg.PutProperty(kernel.PropertyTags, "test_tag")
	_msg.PutProperty("user_defined_key", "hi")
	result, err := cli.p.SendSync(context.Background(), _msg)

	zap.S().Infow("RMQ message", "msg", _msg.String())
	zap.S().Infow("Send Result", "result", result)
```

  - What did you expect to see?

`Tag` and `Property` should be shown in RocketMQ Dashboard.

  - What did you see instead?

There is not.

Here is my log: 
![image](https://user-images.githubusercontent.com/3717140/58922343-12e9ad80-876d-11e9-99c2-86875cd6a4cd.png)

Here is RocketMQ Dashboard:
![image](https://user-images.githubusercontent.com/3717140/58922885-855b8d00-876f-11e9-8c8e-810be79ab292.png)

2. Please tell us about your environment:

     - What is your OS?
OSX 10.14.4
 
     - What is your client version?
2.0.0-alpha1

     - What is your RocketMQ version?
Sorry, I dont know

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

I notice that `./kernel/request.go`, there's no `properties` in  `SendRequest.Encode()`, So I fixed it as follow:

<img width="752" alt="Snipaste_2019-06-05_08-50-44" src="https://user-images.githubusercontent.com/3717140/58922786-0fefbc80-876f-11e9-85b1-0cf77cc033ff.png">

**But It still did not work.** 

So Maybe the whole rmq message header encode has problem.

**Comment by wenfengwang** [comment]
Thank you @easyforgood , we will fix it in next release

**Comment by xujianhai666** [comment]
@easyforgood Hi, we have fix the bug, can u check and close the ISSUE?

**Comment by easyforgood** [comment]
@xujianhai666 Thanks for your bugfix. I'm looking forward to trying it in the coming release tag, 2.0.0-alpha2.

**Comment by wenfengwang** [comment]
@ShannonDing please close the issue

**Comment by wenfengwang** [comment]
The 2.0.0-alpha2 is preparing to release, the release note: https://github.com/apache/rocketmq-client-go/pull/121. and can download in page: https://github.com/apache/rocketmq-client-go/releases
