### ISSUE TITLE
How to ignore old messages ? 

### ISSUE THREAD

**Issue by fwhezfwhez** [apache/rocketmq-client-go#656]
Now, I add a new consumer-group. It will consume histroy messages ,which are too many.

Is there any api to help ignore those old history messages, just by time.

It's alright to add it into selector like:
```go

consumer.MessageSelector{
		Type:       consumer.TAG,
		Expression: tag,
                StartTime: -time.Now().Add(30 * time.Second),
}
```

**Comment by maixiaohai** [comment]
https://github.com/apache/rocketmq-externals/tree/master/rocketmq-console 
Console has a api which could reset consumer offset through timestamp, you can refer to it.

**Comment by fwhezfwhez** [comment]
@maixiaohai reset offset  requires specific topic, but I want to reset all.
