### ISSUE TITLE
when application run for some hours，some of all queue consumerOffset don't update，and diffTotal Increasing .

### ISSUE THREAD

**Issue by thinmonkey** [apache/rocketmq-client-go#66]
os : mac os、linux
cpp: rocketmq-client-cpp-1.2.2
golang:rocketmq-client-go-1.2.0

当应用启动之后，消费者开始消费，应用运用了几个小时之后，某些broker中的queue 消费者位点不在更新，消费时间也不在更新，diffTotal一直在增长。有没有人遇到过这种问题？

**Comment by wenfengwang** [comment]
The Go client in pure go has more feature, welcome have a try, and The 2.0.0-alpha2 is preparing to release, the release note: https://github.com/apache/rocketmq-client-go/pull/121. and can download in page: https://github.com/apache/rocketmq-client-go/releases
