### ISSUE TITLE
[Master] Namespace Bug fix

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq-client-go#662]
**BUG REPORT**  
1. Please describe the issue you observed:
namespace目前对发送的msg对应的topic添加namespace前缀，如果为批量消息，需要对所有消息对应的topic添加Namespace，目前只对批量消息封装后的msg对应的topic添加了namespace。

2. Please tell us about your environment:
 - Ubuntu 4.8.4
 - rocketmq 4.8

**Comment by maixiaohai** [comment]
@Git-Yang pls split your pr based on the issue and add more background.

**Comment by Git-Yang** [comment]
> @Git-Yang pls split your pr based on the issue and add more background.

Okay, I'm done.

**Comment by wenfengwang** [comment]
pr merged
