### ISSUE TITLE
tackType = UNKNOWN ;result=com.alibaba.fastjson.JSONException: No enum constant org.apache.rocketmq.remoting.protocol.LanguageCode.GO, com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:614)

### ISSUE THREAD

**Issue by fumenglin** [apache/rocketmq-client-go#666]
核心代码如下：

```golang
traceCfg := &primitive.TraceConfig{
		Access:   primitive.Local,
		Resolver: primitive.NewPassthroughResolver(addrs),
	}
	TopicConsumer := "topic"
	ConsumerGroupName := "consumer"
	c, _ := rocketmq.NewPushConsumer(
		consumer.WithGroupName(ConsumerGroupName),
		consumer.WithNsResovler(primitive.NewPassthroughResolver(addrs)),
		consumer.WithTrace(traceCfg),
	)
	err := c.Subscribe(TopicConsumer, consumer.MessageSelector{}, func(ctx context.Context,
		msgs ...*primitive.MessageExt) (consumer.ConsumeResult, error) {
		for i := range msgs {
					waybillMsg := msgs[i]
					t.Log(waybillMsg.OffsetMsgId)
					t.Log(string(waybillMsg.Body))
				}
		return consumer.ConsumeSuccess, nil
	})
	if err != nil {
		fmt.Println(err.Error())
	}
	// Note: start after subscribe
	err = c.Start()
	if err != nil {
		fmt.Println(err.Error())

	}
	time.Sleep(time.Hour)
	err = c.Shutdown()
	if err != nil {
		fmt.Printf("shutdown Consumer error: %s", err.Error())
	}

```

但是在监控端；显示的:tackType = UNKNOWN ;result=com.alibaba.fastjson.JSONException: No enum constant org.apache.rocketmq.remoting.protocol.LanguageCode.GO, com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:614)

请问是trace用的不对么；

**Comment by bilinxing** [comment]
Probably because you used an old version of the docker image of rocketmq-console, for example:https://hub.docker.com/r/styletang/rocketmq-console-ng. Just replace it with the new version: https://hub.docker.com/r /apacherocketmq/rocketmq-console

**Comment by bilinxing** [comment]
Probably because you used an old version of the docker image of rocketmq-console, for example:https://hub.docker.com/r/styletang/rocketmq-console-ng. Just replace it with the new version: https://hub.docker.com/r/apacherocketmq/rocketmq-console

**Comment by wenfengwang** [comment]
> Probably because you used an old version of the docker image of rocketmq-console, for example:https://hub.docker.com/r/styletang/rocketmq-console-ng. Just replace it with the new version: https://hub.docker.com/r/apacherocketmq/rocketmq-console

thanks @bilinxing ,  does the solution working? @fumenglin
