### ISSUE TITLE
get subscribed topic list for PushConsumer

### ISSUE THREAD

**Issue by maqingxiang** [apache/rocketmq-client-go#671]
**FEATURE REQUEST**

1. describe the feature: get subscribed topic list for PushConsumer.

2. proposed use case for this feature:

![image](https://user-images.githubusercontent.com/35321391/119958844-00aa4f00-bfd6-11eb-8337-f3eabc6657d0.png)

**Comment by maixiaohai** [comment]
Admin tools is recommended at meta opt case.

**Comment by maqingxiang** [comment]
I didn't get it. Can you tell me more about it.

**Comment by maixiaohai** [comment]
> I didn't get it. Can you tell me more about it.
> Thanks.

我理解，元数据的操作更多通过管理工具去实现，生产和消费更专注与数据操作本身

**Comment by wenfengwang** [comment]
we need have a discussion,  @maqingxiang could you give us some use scenarios for the `GetSubTopics` method?

**Comment by maqingxiang** [comment]
The business only needs to provide the latest topic subscription list, and then the platform can dynamically adjust the topic subscription list according to the latest requirements of the business.
