### ISSUE TITLE
[bug] The Unsubscribe() interface not in effect for PushConsumer

### ISSUE THREAD

**Issue by maqingxiang** [apache/rocketmq-client-go#674]
**BUG REPORT**  

```
// push_consumer.go

func (pc *DefaultPushConsumer) Unsubscribe(topic string) error {}

```

the client version is github.com/apache/rocketmq-client-go/v2 v2.1.0

**Comment by maixiaohai** [comment]
https://github.com/apache/rocketmq-client-go/pull/626

**Comment by maqingxiang** [comment]
It has been tested and it does not work.

The call link is:
consumer.NewPushConsumer() - c.Subscribe() - c.Start() - c.Unsubscribe() - c.Shutdown()

**Comment by maixiaohai** [comment]
> It has been tested and it does not work.
> 
> The call link is:
> consumer.NewPushConsumer() - c.Subscribe() - c.Start() - c.Unsubscribe() - c.Shutdown()

can u post some test details about Unsubscribe method did not work， I could not reproduce.

**Comment by maixiaohai** [comment]
@maqingxiang is this pr can fix your problem? https://github.com/apache/rocketmq-client-go/pull/680

**Comment by maqingxiang** [comment]
That seems to be the problem. Let me test it.

Thank you.
