### ISSUE TITLE
admin support get topic route  info

### ISSUE THREAD

**Issue by yiyouguisu** [apache/rocketmq-client-go#675]
Feature Support：

- We use the Proxy component to proxy rocketmq traffic and need to be able to obtain the address information of the broker，We can get the route info for the topic by admin interface

**Comment by francisoliverlee** [comment]
https://github.com/apache/rocketmq-client-go/blob/817ad27ef30a911ad561d00deae08e6ecefcc40d/internal/route.go#L333

check it!

**Comment by yiyouguisu** [comment]
> https://github.com/apache/rocketmq-client-go/blob/817ad27ef30a911ad561d00deae08e6ecefcc40d/internal/route.go#L333
> 
> check it!

The func can't be referenced from outside, may be exposed through the admin interface
