### ISSUE TITLE
service close is not running, please check

### ISSUE THREAD

**Issue by fwhezfwhez** [apache/rocketmq-client-go#676]
Hi, my app service suffers from a kick-off (All my nodes of app group are just offline with rocketmq, regardless of producer or consumer). I'm confused and can't feagure why.

Producer error is `service close is not running, please check`. However this suggests nothing.

There is three things need to be confirmed:

- If consumer subscribe a topic whose topic producer has not produced yet, will rocketmq regard this kind of clients invalid and kick them off?
- if app group has a node whose subscribed topics are more than others (contains others' topics), will this advanced node be kicked off after some time?
- If rocketmq will kick those unconsistently subscribed topic nodes off, will it forcely kick produce of a same node too? I suggest this is exactly a bug!!!

**Comment by fwhezfwhez** [comment]
After many time testing, I find unconsistent nodes will be auto-kickoff.

What wil happen if app group has many nodes and they're rebuilding. Apperantly this process might cost time and occurs unconsitent cases.Will some nodes be kicked off? This is fatal!!!

**Comment by francisoliverlee** [comment]
- please leave the client version , RocketMQ version
- there are 3 nodes for consumer, one sub none-existence topic, other 2 would be kick off, or 3 nodes sub none-existence topic, all would be kicked off, WHICH ONE?

**Comment by fwhezfwhez** [comment]
@francisoliverlee 

go-client-version:
	github.com/apache/rocketmq-client-go/v2 v2.1.0-rc5

rocketmq version:
         in rocketmq-console, verison in `Cluster` tab shows that cluster broker version is V4_7_1。 in `Consumer` tag shows V4_5_2.

All will be kickoff.
