### ISSUE TITLE
[master] request parameter type error fix

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq-client-go#683]
1. Please describe the issue you observed:
    发送batch message时，broker解析request出现类型转换错误。
    ![image](https://user-images.githubusercontent.com/30995057/122389350-6e2d1800-cfa3-11eb-8b0d-ab573ddb3523.png)
   
    问题原因为go sdk 中defaultTopicQueueNums字段类型为string，且该字段未设值，即初始化后为空字符串，导致在broker中request解析出现类型转换异常。

2. Please tell us about your environment:
    centos 7
    go sdk v2.1.0
    rocketmq 4.8

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
    稍后提交修复代码

**Comment by wenfengwang** [comment]
close due to related PR merged
