### ISSUE TITLE
offset question?

### ISSUE THREAD

**Issue by zczhen** [apache/rocketmq-client-go#687]
![lADPDg7mRA06w6HNA3rNBQA_1280_890](https://user-images.githubusercontent.com/29100710/123267374-8535b200-d52f-11eb-84b1-62957f991558.jpg)
使用广播模式消费，可以消费成功，但是offset报错，the process cannot access the file because it is    
 being used by another process   ,因公司电脑无法联网，只能手机拍照了

**Comment by wenfengwang** [comment]
could you provide more detail information?
