### ISSUE TITLE
SendAsync send big message panic

### ISSUE THREAD

**Issue by weichangdong** [apache/rocketmq-client-go#690]
go mod use this version 

```
github.com/apache/rocketmq-client-go/v2 v2.1.0
```

```	
err = rocketmqclient.RocketmqProducer.SendAsync(context.Background(),
		func(ctx context.Context, result *primitive.SendResult, e error) {
			if e != nil || result == nil || (result != nil && result.Status != primitive.SendOK) {
				logs.Error("SendAsync SendAsync message error: ", e, " result:", result, " msgLen:", len(string(msgByte)), " ctime:", ctime, " relatedUid:", relatedUid, " relatedTid:", relatedTid)
				if result != nil {
					logs.Error("result:", result.String())
				}
				err = e
				sendOk = false
			} else {
				sendOk = true
			}
		}, rocketmqMsg)

```
the log output
```
SendAsync SendAsync message error:  <nil>  result: %!v(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)  msgLen: 788741  ctime: 1624901003080  relatedUid: radtatmbcpg5cemoqjs8t324l0  relatedTid: 
```

maxMessageSize=65536

Although our setting is small, it should not panic

**Comment by weichangdong** [comment]
This problem did not appear after we changed the maximum message Settings,
maxMessageSize=4194304
but for now there is Panic using the current master code(Fork the code to tag myself )

I suspect RocketMQ is under stress at that point, Grafana's monitoring shows that the Broker's TPS has grown to 100 to 150, but no RocketMQ error log is available

**Comment by weichangdong** [comment]
SendAsync SendAsync message error:  <nil>  result: %!v(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)  msgLen: 1077  ctime: 1626150327634

**Comment by weichangdong** [comment]
```
SendAsync SendAsync message error:  request timeout  result: <nil>  msgLen: 764  ctime: 1626257106588  relatedUid:    ctx: context.Background.WithDeadline(2021-07-14 15:35:09.592028007 +0530 IST m=+3764.379185364 [2.999812347s])  ctxErr: context canceled
```
使用了master的代码,panic没了,但是一直报错,但是消息并没有丢. 我觉得主要应该是最新的代码 加了 
-- 之前的
ctx, _ = context.WithTimeout(ctx, 3*time.Second)
-- 最新的
var cancel context.CancelFunc
ctx, cancel = context.WithTimeout(ctx, 3*time.Second)
defer cancel()

这是bug么?

**Comment by wenfengwang** [comment]
it is not a bug, i will check it

**Comment by wenfengwang** [comment]
the issue was fixed at https://github.com/apache/rocketmq-client-go/pull/702
