### ISSUE TITLE
pull consumer has not supported

### ISSUE THREAD

**Issue by duffiye** [apache/rocketmq-client-go#696]
pull consumer has not supported , any schedule？

**Comment by wenfengwang** [comment]
no plan now, if there is any update ,i will update here

**Comment by zongtanghu** [comment]
I think you can write an design document, and then I and my workmates can participate into coding.And then we can splite this issues into serveral prs. @wenfengwang

**Comment by vongosling** [comment]
Community behavior always encourages our maintainers not eager to say no, if any guys want to volunteer to it. don't be hesitate:-)
