### ISSUE TITLE
waitResponse request timeout error

### ISSUE THREAD

**Issue by fengberlin** [apache/rocketmq-client-go#703]
Many `request timeout` error occur when call `SendAsync`, the same problem as #701.

rocketmq-client-go version: the latest master commit [e5d5631
](https://github.com/apache/rocketmq-client-go/commit/e5d56316563ab66b0c173ac6226867842eb2cbf4)
go version: 1.13.6

**Comment by wenfengwang** [comment]
the change has been reverted in https://github.com/apache/rocketmq-client-go/pull/702
