### ISSUE TITLE
[Master] Multiple consumers with the same instance name will prevent topic route data to update

### ISSUE THREAD

**Issue by luyui** [apache/rocketmq-client-go#707]
**BUG REPORT**

1. Please describe the issue you observed:

    - *What did you do (The steps to reproduce)?*
    - Start multiple PushConsumer with the same instance name

    - *What did you expect to see?*
    - All consumer will update&react to topic route change(i.e. broker cluster scale, topic permission change, etc.)

    - *What did you see instead?*
    - Only the first consumer instance will get the updated topic route info

2. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

Multiple consumer will share one `rmqClient` instance if the client id/ instance name is the same.
However each consumer will initiate it's own `namesrvs` instance, and the only `rmqClient` instance gets
the first consumers's `namesrvs`, which the only instance gets updated `topicRouteData`.

To fix the issue, it's suggested to remove local `namesrvs` field in `pushConsumer` and `pullConsumer`
And add an interface to retrieve `rmqClient`'s `namesrvs` instance on demand.

**Comment by maixiaohai** [comment]
@fluyu welcome to submit a pr~
