### ISSUE TITLE
[bug] The Unsubscribe() interface influence retrytopic

### ISSUE THREAD

**Issue by maqingxiang** [apache/rocketmq-client-go#711]
BUG REPORT

// push_consumer.go

func (pc *DefaultPushConsumer) Unsubscribe(topic string) error {
    ...
    retryTopic := internal.GetRetryTopic(pc.consumerGroup)
    pc.subscriptionDataTable.Delete(retryTopic)
    ...
}

There's a scene where the same ConsumerGroup subscries to T1, subscries to T2, and unsubscribe T1. Is that a problem?

the client version is github.com/apache/rocketmq-client-go/v2 v2.1.0

**Comment by francisoliverlee** [comment]
### as java client does in following files, client no need to Unsubscribe retry topic.

> https://github.com/apache/rocketmq/blob/a20f31bb3de242756542c552d7212a7a40000ba4/client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java#L792

> https://github.com/apache/rocketmq/blob/a20f31bb3de242756542c552d7212a7a40000ba4/client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java#L932

## as checked broker codes,  subscribtion for retry topic would never delete. broker update subscribtions on heartbeat:
> https://github.com/apache/rocketmq/blob/a20f31bb3de242756542c552d7212a7a40000ba4/broker/src/main/java/org/apache/rocketmq/broker/processor/ClientManageProcessor.java#L75
