### ISSUE TITLE
consumerOptions无法访问ConsumeTimestamp字段

### ISSUE THREAD

**Issue by whisper-a** [apache/rocketmq-client-go#715]
如题，我当前使用github.com/apache/rocketmq-client-go/v2，当我想使用consumer.WithConsumeFromWhere(consumer.ConsumeFromTimestamp)这个类型时，
却发现对应的ConsumeTimestamp没有对外暴露设置的接口，请问这是你们有意为之吗？？

**Comment by whisper-a** [comment]
I think you may not understand the meaning of my question. I need to use the “ConsumeFromTimestamp” type, which means that this is a time-related option, but I can‘t pass in a timestamp? Because this option cannot be accessed externally.
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/13915674/131945962-acfdd0ab-d551-4bcd-b703-2f0732721c8a.png">

**Comment by whisper-a** [comment]
I think you may need to add an external access interface to the **_ConsumeFromTimestamp_** field like adding these options。
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/13915674/131946291-42867251-0c68-4dac-9aef-530c11002f91.png">

**Comment by ShannonDing** [comment]
This parameter only takes effect for the consumer who added it for the first time, and the consumer will start to consume from the last consumption offset by default.
