### ISSUE TITLE
[bug] The Subscribe() interface not in effect with consumer.MessageSelector{}

### ISSUE THREAD

**Issue by maqingxiang** [apache/rocketmq-client-go#718]
**BUG REPORT**  

```
// push_consumer.go

Subscribe(topic string, selector consumer.MessageSelector,
		f func(context.Context, ...*primitive.MessageExt) (consumer.ConsumeResult, error)) error

```

The first call with theconsumer.MessageSelector is fine, but the second call is error-free and can not update the subscription in real time.

For the first time,
```
consumer.Subscribe("topic1", consumer.MessageSelector{Type: consumer.ExpressionType("TAG"), Expression: "tag1 || tag2"}, func... )
```
The second time, 
```
consumer.Subscribe("topic1", consumer.MessageSelector{Type: consumer.ExpressionType("TAG"), Expression: "tag1 || tag3"}, func... )
```

After the second call, tag2 can still be consumed, but no messages are consumed for tag3.

the client version is github.com/apache/rocketmq-client-go/v2 v2.1.0

**Comment by maqingxiang** [comment]
https://github.com/apache/rocketmq-client-go/pull/720

**Comment by ShannonDing** [comment]
see #720, set subversion when buildSubscriptionData
