### ISSUE TITLE
sendAsync method can't send different messages to multiple topics

### ISSUE THREAD

**Issue by gjack1385** [apache/rocketmq-client-go#719]
var ms []*primitive.Message
m=&primitive.NewMessage("topic1", []byte("Hello RocketMQ Go Client!"))
ms=append(ms,m)
m=&primitive.NewMessage("topic2", []byte("Hello RocketMQ Go Client!"))
ms=append(ms,m)
....
sendSync(..... ,.... ,ms...)

These messages are sent to topic1。

**Comment by maixiaohai** [comment]
Your title and code is contradictory.
and a client version is needed to replay your situation.

**Comment by ShannonDing** [comment]
hi, sendSync or sendAsync?
IMO, maybe we can have a try on the latest version v2.1.0 and print more logs as far as possible.
