### ISSUE TITLE
example can not work

### ISSUE THREAD

**Issue by bq49** [apache/rocketmq-client-go#72]
[root@localhost examples]# go test main.go
./main.go:55:4: undefined: sendMessageOrderly
./main.go:57:4: undefined: sendMessage
./main.go:71:3: undefined: ConsumeWithPush
[root@localhost examples]#

**Comment by wenfengwang** [comment]
The Go client in pure go has more feature, welcome have a try, and The 2.0.0-alpha2 is preparing to release, the release note: https://github.com/apache/rocketmq-client-go/pull/121. and can download in page: https://github.com/apache/rocketmq-client-go/releases
