### ISSUE TITLE
feat: use sendMsgTimeout option for sendSync

### ISSUE THREAD

**Issue by hnlq715** [apache/rocketmq-client-go#721]
Currently it‘s simply hard code...

https://github.com/apache/rocketmq-client-go/blob/29d789edcaa3408e569e96e76bd71591ee66dbe7/producer/producer.go#L206-L210

**Comment by yuanmoon** [comment]
@wenfengwang 
For this code segment, the hard code of request timeout is also used.
https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/consumer/offset_store.go#L357-L361
I find that the object doesn't have property for request timeout, which I think should be added.
https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/consumer/offset_store.go#L224-L230

**Comment by yuanmoon** [comment]
Here is another code segment and has the same problem that the object doesn't have property for request timeout.
https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/admin/admin.go#L111-L112
https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/admin/admin.go#L41-L43

**Comment by yuanmoon** [comment]
The code segment in consumer/consumer.go also uses hard code.
https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/consumer/consumer.go#L587-L590
https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/consumer/consumer.go#L614-L619
https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/consumer/option.go#L27-L109

**Comment by yuanmoon** [comment]
Many similar places can be found through global code search. Mainly involves the calling cases of the following two functions
https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/internal/client.go#L141-L142
https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/internal/client.go#L145-L146

If I want to fix this issue and optimize code, I‘m not sure that it's necessary or not to have a unified standard of request timeout and set different default values ​​according to different usage cases.
