### ISSUE TITLE
Why specify Broker when creating a topic?

### ISSUE THREAD

**Issue by njutsiang** [apache/rocketmq-client-go#725]
https://github.com/apache/rocketmq-client-go/blob/406561060cb7d27c84df7f146a5ef003122c9cda/examples/admin/topic/main.go#L43

I'm very sorry, but I don't understand why this is so?

1. When there is no topic to send a message, the topic will be automatically created, and the queue will be created automatically without executing the broker.
2. The broker behind the NameServer may be a cluster. I don't know which broker I should specify, and the broker I specify is very likely to be unavailable. Why can't the nameserver automatically select the broker?

**Comment by maixiaohai** [comment]
1. In production Cluster, topic do not support auto-create because of multi-tenant
2. When a cluster has so many brokers,  how to decide which brokers to select

**Comment by njutsiang** [comment]
Well, although I still have some doubts, maybe I should study further.
