### ISSUE TITLE
[push_consumer] offset cannot be updated

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq-client-go#731]
1. Please describe the issue you observed:

Background:
- New subscription group.
- Start spending from the latest location.
- No new data is written to the topic.

Problem:
- Request the broker to get the data and return PullNoNewMsg. But the offset is not updated to the offsetTable, and the nextOffset is not processed.

2. Please tell us about your environment:
- Linux
- Go SDK 2.1.0
- RocketMQ 4.8

**Comment by maixiaohai** [comment]
merged
