### ISSUE TITLE
[PullConsumer] Low level implementation

### ISSUE THREAD

**Issue by wenfengwang** [apache/rocketmq-client-go#737]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
add implementation of LowLevel PullConsumer
2. Provide any additional detail on your proposed use case for this feature.
```go
type ManualPullConsumer interface {
    // get n messages from specified queue with offset
    PullFromQueue(ctx context.Context, mq *primitive.MessageQueue, offset int64, numbers int) (*primitive.PullResult, error)

    // get queues of the topic
    GetMessageQueues(ctx context.Context, topic string) []*mq primitive.MessageQueue

    // get the offset of mq in groupName, if mq not exist, -1 will be return
    CommittedOffset(groupName string, mq primitive.MessageQueue) (int64, error)
    
    // seek comsume position to the offset, this api can be used to reset offset and commit offset
    Seek(groupName string, mq primitive.MessageQueue, offset int64) error
    
    // query offset according to timestamp(ms), the maximum offset that born time less than timestamp will be return
    // if timestamp less than any message's born time, the earliest offset will be returned
    // if timestamp great than any message's born time, the latest offset will be returned
    Lookup(ctx context.Context, mq primitive.MessageQueue, timestamp int64) (int64, error)
}
```
3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
 must-have
4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
none

**Comment by vongosling** [comment]
Looking forward to it. We could stay compatible with java interface semantics.

**Comment by zongtanghu** [comment]
Nice job! We will discuss this implementation, and my friends will claim this feature developing!

**Comment by shendongsd** [comment]
Could I develop this feature? @zongtanghu @wenfengwang

**Comment by zongtanghu** [comment]
Okay, good! It's yours!   @shendongsd
