### ISSUE TITLE
[Master] create topic nil pointer dereference

### ISSUE THREAD

**Issue by baerwang** [apache/rocketmq-client-go#739]
The issue tracker is **ONLY** used for the go client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**  
**Please add the branch name [Native]/[Master] at the header of the Isssue title.**

1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?

          create topic

    - What did you expect to see?

          create topic success

    - What did you see instead?

          create topic nil pointer dereference

2. Please tell us about your environment:

     - What is your OS?

           win,centos

     - What is your client version?

           Rocketmq-client-go-2.1.0

     - What is your RocketMQ version?

           rocketmq-4.9.2

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

    - [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
    - [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
    - ...

**Comment by maixiaohai** [comment]
how to reproduce this?
can you post more error logs

**Comment by baerwang** [comment]
In the exampls/admin/topic directory
```error
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xedcc73]

goroutine 1 [running]:
github.com/apache/rocketmq-client-go/v2/internal.GetOrNewRocketMQClient(0xf6dbee, 0xb, 0x0, 0x0, 0x0, 0x0, 0xc00000a260, 0xc, 0xc000012ac0, 0x34, ...)
	/opt/rocketmq-client-go/internal/client.go:191 +0x3b3
github.com/apache/rocketmq-client-go/v2/admin.NewAdmin(0xc00010fd78, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/opt/rocketmq-client-go/admin/admin.go:79 +0x167
main.main()
	/opt/rocketmq-client-go/examples/admin/topic/main.go:34 +0x1ad
```

**Comment by xiaolin13** [comment]
> The issue tracker is **ONLY** used for the go client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.
> 
> Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.
> 
> Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:
> 
> **BUG REPORT** **Please add the branch name [Native]/[Master] at the header of the Isssue title.**
> 
> 1. Please describe the issue you observed:
>    
>    * What did you do (The steps to reproduce)?
>      ```
>      create topic
>      ```
>    * What did you expect to see?
>      ```
>      create topic success
>      ```
>    * What did you see instead?
>      ```
>      create topic nil pointer dereference
>      ```
> 2. Please tell us about your environment:
>    
>    * What is your OS?
>      ```
>      win,centos
>      ```
>    * What is your client version?
>      ```
>      Rocketmq-client-go-2.1.0
>      ```
>    * What is your RocketMQ version?
>      ```
>      rocketmq-4.9.2
>      ```
> 3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
> 
> **FEATURE REQUEST**
> 
> 1. Please describe the feature you are requesting.
> 2. Provide any additional detail on your proposed use case for this feature.
> 3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
> 4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
>    
>    * [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here,
>    * [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
>    * ...

I have the same problem, is there a solution?
