### ISSUE TITLE
When is it supported native golang?

### ISSUE THREAD

**Issue by wolftankk** [apache/rocketmq-client-go#74]
The current integration into the project is too costly, build hard, deploy hard.

Is it a plan to support native golang?

**Comment by icc99** [comment]
+1

**Comment by exquisite2007** [comment]
+1
currenty, rocketmq is really not friendly for go developer

**Comment by wenfengwang** [comment]
@wolftankk @icc99 @exquisite2007 The native client in pure go released alpha1 version in last month, you can find it in [release page](https://github.com/apache/rocketmq-client-go/releases) and the alpha2 is developing, roadmap page is here: [2.0.0-alpha2 Roadmap](https://github.com/apache/rocketmq-client-go/issues/75)

**Comment by wenfengwang** [comment]
the source code located in **native** branch

**Comment by CodeJuan** [comment]
WOW !!!!!
Thank you, it would be very helpful to us.

**Comment by wenfengwang** [comment]
The 2.0.0-alpha2 is preparing to release, the release note: https://github.com/apache/rocketmq-client-go/pull/121. and can download in page: https://github.com/apache/rocketmq-client-go/releases

**Comment by wohenbushuang** [comment]
@wenfengwang request to publish the native branch to a independent repo, since when using `go get` to pull the package, it will check the default branch and report missing `go` files. This can be solved by git clone manually, but cannot be used in dockerfile `go get -d -v ./...`

**Comment by xujianhai666** [comment]
> @wenfengwang request to publish the native branch to a independent repo, since when using `go get` to pull the package, it will check the default branch and report: missing `go` files. This can be solved by git clone manually, but cannot be used in dockerfile `go get -d -v ./...`

maybe  go mod is what u want!

**Comment by xujianhai666** [comment]
> @wenfengwang request to publish the native branch to a independent repo, since when using `go get` to pull the package, it will check the default branch and report: missing `go` files. This can be solved by git clone manually, but cannot be used in dockerfile `go get -d -v ./...`

@wohenbushuang maybe  go mod is what u want

**Comment by zenghur** [comment]
timeframe for pure go rc release？

**Comment by ShannonDing** [comment]
update： [v2.0.0-alpha3](https://github.com/apache/rocketmq-client-go/releases/tag/v2.0.0-alpha3)

**Comment by luthfikw** [comment]
+1

**Comment by plhwin** [comment]
+1

**Comment by wenfengwang** [comment]
the [v2.0.0-rc1](https://github.com/apache/rocketmq-client-go/releases/tag/v2.0.0-rc1) has been released! please have a try and any feedback will be welcomed.

@luthfikw @plhwin @zenghur @wohenbushuang @CodeJuan @exquisite2007 @icc99 @wolftankk

**Comment by wenfengwang** [comment]
close the issue, please refer #57
