### ISSUE TITLE
Consumers will be closed when the topic does not exist

### ISSUE THREAD

**Issue by littleantfly** [apache/rocketmq-client-go#751]
rocketmq-client-go version: 2.1.0

希望可以像Java SDK一样，Consumer 在Topic没创建时可以定时检测而不是自动将client shutdown。
push_consumer.go
`pc.client.UpdateTopicRouteInfo()
	for k := range pc.subscribedTopic {
		_, exist := pc.topicSubscribeInfoTable.Load(k)
		if !exist {
			pc.client.Shutdown()
			return fmt.Errorf("the topic=%s route info not found, it may not exist", k)
		}
	}`

目前需要手动通过
`err = testAdmin.CreateTopic(
		context.Background(),
		admin.WithTopicCreate(topic),
		admin.WithBrokerAddrCreate(brokerAddr),
	)`  来创建，
且必须提供brokerAddr。通过namesrvAddr获取brokerAddr的接口被封装到了sdk内部，外部无法调用.

**Comment by qshuai** [comment]
same problem. 

How to create the topic automaticly when consuming a existed topic?

**Comment by qshuai** [comment]
> same problem.
> 
> How to create the topic automaticly when consuming a existed topic?

Or consumer hold on until the topic created
