### ISSUE TITLE
Master code reset consumer offset cause program exit

### ISSUE THREAD

**Issue by WJL3333** [apache/rocketmq-client-go#759]
1. Please describe the issue you observed:
    1. start local RocketMQ cluster 
    2. use example/consumer/simple/main.go start a consumer.
    3. use ./mqadmin resetOffset tool to reset offset.
    4. consumer process exit with.
   
          INFO[0005] receive reset consumer offset request...      broker="127.0.0.1:30931" consumerGroup=groupB timestamp=631123200000 topic=topicB
panic: runtime error: index out of range [1] with length 1
goroutine 113 [running]:
github.com/apache/rocketmq-client-go/v2/internal.(*ResetOffsetBody).Decode(0xc000461d20, {0xc00040c100, 0xfd, 0xfd})
        /Users/bytedance/github/rocketmq-client-go/internal/model.go:309 +0xa45
github.com/apache/rocketmq-client-go/v2/internal.GetOrNewRocketMQClient.func5(0xc000416a80, {0x14ed5c8, 0xc0003260c0})
        /Users/bytedance/github/rocketmq-client-go/internal/client.go:303 +0x3f8
github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).processCMD.func2()
        /Users/bytedance/github/rocketmq-client-go/internal/remote/remote_client.go:207 +0x94
github.com/apache/rocketmq-client-go/v2/primitive.WithRecover(0xc000421ef0)
        /Users/bytedance/github/rocketmq-client-go/primitive/base.go:100 +0x47
created by github.com/apache/rocketmq-client-go/v2/internal/remote.(*remotingClient).processCMD
        /Users/bytedance/github/rocketmq-client-go/internal/remote/remote_client.go:206 +0x378
Exiting.
    ```

2. Please tell us about your environment:
    mac local 
    master client-go code.
    rocketmq broker with fastjson-1.2.76.jar

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
the test code in decode ResetOffsetBody json format is different from mine

mine from rocketmq broker response rpc
```json
{"offsetTable":{{"brokerName":"RaftNode00","queueId":0,"topic":"topicB"}:0,{"brokerName":"RaftNode00","queueId":1,"topic":"topicB"}:0,{"brokerName":"RaftNode00","queueId":2,"topic":"topicB"}:0,{"brokerName":"RaftNode00","queueId":3,"topic":"topicB"}:0}}
```

any different from fastjson config ?

**Comment by WJL3333** [comment]
@maixiaohai hello,can you check this problem. i think the json is not the same cause the parse problem. what is your fastjson version

**Comment by WJL3333** [comment]
more context: see https://github.com/apache/rocketmq-client-go/blob/82dcf51c7c9bcec25a29e9617da61089db44b16d/internal/model_test.go#L407-L422

**Comment by wenfengwang** [comment]
@WJL3333 Thanks for your report, Could you have any idea for fixing this?

**Comment by WJL3333** [comment]
@wenfengwang i think the json decode method cause this problem. the current json here is different from my rocketmq cluster, fastjson-1.2.76.jar i wonder if there is some special config for json serialization? if we can find why json is different, may be use different json lib in rocketmq or different fastjson version? the fix is apperent.

**Comment by maixiaohai** [comment]
> @maixiaohai hello,can you check this problem. i think the json is not the same cause the parse problem. what is your fastjson version

We use Gson internal, can you help fix this?

**Comment by WJL3333** [comment]
yes, but should we just follow the fastjson schema, and change the origin gson format? @maixiaohai @wenfengwang

**Comment by maixiaohai** [comment]
> yes, but should we just follow the fastjson schema, and change the origin gson format? @maixiaohai @wenfengwang

Yeah, fastjson format is original currently. RMQ server use fastjson to encode and decode as default. 
And Fastjson has security problem and produce some non-standard json schema. Only change the client schema can not solve this problem. 
This is a related issue to describe the background https://github.com/apache/rocketmq/issues/2462.

**Comment by WJL3333** [comment]
yes, i agree with you. the non-standard json schema is very annoying when port some admin interface from java to go.
and for this case. i will try to parse response json first. if we found this is non-standard json schema. the code will try to parse response as fastjson format.
