### ISSUE TITLE
2.1 版本 客户端消费成功，阿里云后台显示未消费

### ISSUE THREAD

**Issue by leader318** [apache/rocketmq-client-go#760]
客户端有消费到消息，查询阿里云后台的消费状态，是未消费，group 里也没有消息堆积，不知道是什么原因

客户端是正常 返回
`return consumer.ConsumeSuccess, nil`

**Comment by lowmanisbusy** [comment]
oh，xiongdie，you should write it in english，github is a beautiful country‘s website

**Comment by duhenglucky** [comment]
@leader318 可以去阿里云提个工单

**Comment by ckall** [comment]
你好,我也遇到了请问是如何解决的
