### ISSUE TITLE
[Consumer]The exception handling of function doUnlock needs to be optimized

### ISSUE THREAD

**Issue by yuanmoon** [apache/rocketmq-client-go#762]
**BUG REPORT**  
1. Please describe the issue you observed:
https://github.com/apache/rocketmq-client-go/blob/de5f56172c82d3f6633575c7904c5ab4f1c8a977/consumer/consumer.go#L614-L635
    - What did you do (The steps to reproduce)?
    Call function doUnlock with oneway=false.
    - What did you expect to see?
    There is no error message output when request is successful.
    - What did you see instead?
    There is some error message output when request is successful.

2. Please tell us about your environment:
     Optimize code, improve the logic of exception handling.
     - What is your OS?
     macOS 10.14.5
     - What is your client version?
     rocketmq-client-go v2.1.0
     - What is your RocketMQ version?
     v4.9.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by wenfengwang** [comment]
Hi @yuanmoon, `OneWay` means the caller doesn't care about the execution result, if one wants to know something response content, he/she should not use `oneway`.

**Comment by yuanmoon** [comment]
> Hi @yuanmoon, `OneWay` means the caller doesn't care about the execution result, if one wants to know something response content, he/she should not use `oneway`.

@wenfengwang 
I don't understand what you mean very much. Maybe I don't express it clearly enough. The key point I want to optimize is that when `oneway` is false, no matter `err` is null or not, there is always error message output by `rlog.Error`. I think this is unreasonable and it's better that error message is output when `err` isn't null or `response.Code` isn't success.
So I make some change based on the above.
