### ISSUE TITLE
Mac M1 build failed 

### ISSUE THREAD

**Issue by shencw** [apache/rocketmq-client-go#786]
The issue tracker is **ONLY** used for the go client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**  
1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
    
    i used github.com/apache/rocketmq-client-go v1.2.4
    
   compile locally https://github.com/apache/rocketmq-client-cpp/tree/re_dev
   
   PC OS Macbook Pro M1 (arm64)
    
    - What did you expect to see?
    
    success

    - What did you see instead?
    
    fatal error: 'rocketmq/CMessageExt.h' file not found

2. Please tell us about your environment:

     - What is your OS?
     
Macbook Pro M1 (arm64)

     - What is your client version?
v1.2.4
     - What is your RocketMQ version?

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

I need to use pullconsumer mode

only 1.* version is supported

2. Provide any additional detail on your proposed use case for this feature.

The location of the file path has changed https://github.com/apache/rocketmq-client-cpp/blob/re_dev/include/c/CMessageExt.h

github.com/apache/rocketmq-client-go@v1.2.4/core/cfuns.go:19

```go
/*
#cgo LDFLAGS: -L/usr/local/lib -lrocketmq

#include <rocketmq/CMessageExt.h>
#include <rocketmq/CPushConsumer.h>
*/
```

I tried the historical version(46dd8f597a25aafc27c488e48a9f335b8a64796c) of `rocketmq-client-cpp(re_dev)` but it fails to compile

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

blocker

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

    - [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
    - [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
    - ...

**Comment by zl03jsj** [comment]
have this been fixed?  or some solutions?
