### ISSUE TITLE
Problem with select queue of producer: Should we sort MessageQueues of producer by BrokerName

### ISSUE THREAD

**Issue by hukaixuan** [apache/rocketmq-client-go#795]
We setup producer with WithQueueSelector, but found some messages with same hashkey was sent to different broker.
After insearch of the code, found that the way of sorting queues maybe wrong:
https://github.com/apache/rocketmq-client-go/blob/6c97b55c8ca21a0dc5e1f25a8ce949cb99c213f3/internal/route.go#L488-L490
should we sort the messagequeues in the same way of topicRouteDataIsChange: https://github.com/apache/rocketmq-client-go/blob/6c97b55c8ca21a0dc5e1f25a8ce949cb99c213f3/internal/route.go#L446-L451

**Comment by francisoliverlee** [comment]
there is a PR to solve it : https://github.com/apache/rocketmq-client-go/pull/1077
