### ISSUE TITLE
rocketmq-client-go not support rocketmq version 3.6.4

### ISSUE THREAD

**Issue by waney316** [apache/rocketmq-client-go#821]
The issue tracker is **ONLY** used for the go client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**  
1. Please describe the issue you observed:
i use rocektmq-client-go/example/producer/simple/main.go to test ,but got error：connect to namesrv failed
my rocketmq cluster version == 3.6.4，
![image](https://user-images.githubusercontent.com/23314093/165965647-65bbbcfc-1974-4f52-a720-706a5213741d.png)

2. Please tell us about your environment:
     - What is your OS?
     centos:7.6
     - What is your client version?
    go version：1.17.7
     - What is your RocketMQ version?
   rocketmq：3.6.4

    - ...

**Comment by ShannonDing** [comment]
The version RocketMQ 3.6.4 seems too old to process LanguageCode...

**Comment by qshuai** [comment]
So which version of rocketmq server are supported when using rocketmq-client-go v2.x?
