### ISSUE TITLE
go1.18 consumer failed to start

### ISSUE THREAD

**Issue by zhanglibo1993** [apache/rocketmq-client-go#823]
The go version is 1.18, and the rocketmq-client-go version is 2.1.0. The producer is successfully started, but the consumer cannot get the return and disconnects from rocketmq. When I downgraded the version of go to 1.17 it worked fine

**Comment by wunengbiao** [comment]
+1
INFO[0000] the consumer start beginning                  consumerGroup=iot-command messageModel=Clustering unitMode=false
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x10600df]

**Comment by zk-blde** [comment]
在本地启动了消费者可以拿到数据, 但是测试环境, 时间长了会拿不到数据

**Comment by iGoogle-ink** [comment]
我这有同样的问题，go 1.18 版本，直接 panic 了，部分截图如下：
![image](https://user-images.githubusercontent.com/17245594/170487761-2f11e46c-cdbf-4d18-84e9-60f9ab832e6b.png)

**Comment by yusank** [comment]
是其依赖的一个库有 bug，go mod 里 replace 一下最新版即可，亲测有效
<img width="1743" alt="image" src="https://user-images.githubusercontent.com/21994267/173484295-c50a9311-805d-4f9b-9ac5-634afca8ad65.png">

**Comment by ShannonDing** [comment]
> 是其依赖的一个库有 bug，go mod 里 replace 一下最新版即可，亲测有效 <img alt="image" width="1743" src="https://user-images.githubusercontent.com/21994267/173484295-c50a9311-805d-4f9b-9ac5-634afca8ad65.png">

Could you submit a PR to fix it?

**Comment by yusank** [comment]
> Could you submit a PR to fix it?

Sure , I will submit a PR now.
