### ISSUE TITLE
How to consume from last offset when create new consumer group?

### ISSUE THREAD

**Issue by udoless** [apache/rocketmq-client-go#855]
**BUG REPORT**  
1. Please describe the issue you observed:

    - What did you do (The steps to reproduce)?
Create a new consumer group with ConsumeFromLastOffset option.
    - What did you expect to see?
Consume from last offset
    - What did you see instead?
Consumer from first offset

2. Please tell us about your environment:

     - What is your OS?
macOS
     - What is your client version?
2.1.0
     - What is your RocketMQ version?
4.3.1

**Comment by Ikepi** [comment]
as for a new consumer group, i guess the last offset is as same as first offset because it never consume before.

**Comment by guyinyou** [comment]
Maybe mqadmin class can satisfy you

**Comment by guyinyou** [comment]
You can search for the following related information:
mqadmin resetOffsetByTime

In this way, the consumption offset can be updated to the latest time offset
