### ISSUE TITLE
Security Advisories from deps.dev

### ISSUE THREAD

**Issue by lifepuzzlefun** [apache/rocketmq-client-go#864]
see https://deps.dev/go/github.com%2Fapache%2Frocketmq-client-go%2Fv2

**Comment by ShannonDing** [comment]
for 
golang.org/x/sys,
need to be updated to 0.0.0-20220412211240-33da011f77ad or the latest version.

**Comment by ShannonDing** [comment]
@WJL3333 could you pls have a review on this PR again?

**Comment by ShannonDing** [comment]
github.com/sirupsen/logrus v1.9.0
github.com/stretchr/testify v1.7.0  
this version seems not support go 1.12.

**Comment by WJL3333** [comment]
@ShannonDing thanks for your fix~ https://endoflife.date/go it seems go 1.12 is release 4 years ago. should we support this version yet?
