### ISSUE TITLE
Functional Options

### ISSUE THREAD

**Issue by wenfengwang** [apache/rocketmq-client-go#90]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Using private config members to protect them with functional options

2. Provide any additional detail on your proposed use case for this feature.
- [Functional Options Pattern in Go](https://halls-of-valhalla.org/beta/articles/functional-options-pattern-in-go,54/)
- [gRPC examples](https://github.com/grpc/grpc-go/blob/263405c7fe47948606651e13ea1c47b30622de90/dialoptions.go)

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
must-have

**Comment by wenfengwang** [comment]
implementation here: https://github.com/apache/rocketmq-client-go/pull/85

**Comment by alahijani** [comment]
Was the grpc example ever implemented?

**Comment by wenfengwang** [comment]
what's the gRPC example in rocketmq-go? could you privider more detail? We have olny referred to the parameter configuration form of gRPC, full options of rocketmq-go you can find in: 
- https://github.com/apache/rocketmq-client-go/blob/native/producer/option.go
- https://github.com/apache/rocketmq-client-go/blob/native/consumer/option.go
