### ISSUE TITLE
Producer compile error

### ISSUE THREAD

**Issue by yuzx2008** [apache/rocketmq-client-go#919]
/home/yuzx/go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.1.1/producer/producer.go:157:19: multiple-value uuid.NewV4() (value of type (uuid.UUID, error)) in single-value context

**Comment by ShannonDing** [comment]
what’s the go version.
could you pls try to have a test on #911 and give some feedback?

**Comment by BLAZZ** [comment]
also have this problem when we using dubbo-go who use mod github.com/satori/go.uuid v1.2.1,  is conflict with v 1.2.0, so we cant use both in a project.
consider upgrade version may cause someone else have a compile error and  github.com/satori/go.uuid is seemingly EOL, so 
how about change to gitee.com/gofrs/uuid/v4 ?

**Comment by hnlq715** [comment]
I thinks it's glad to see this change, seems like github.com/satori/go.uuid is not maintained anymore.

**Comment by dawn2zhang** [comment]
When this fea will be merged?
