### ISSUE TITLE
使用阿里云RocketMQ时无法使用域名,报错: new Namesrv failed.: IP addr error

### ISSUE THREAD

**Issue by KilluaChen** [apache/rocketmq-client-go#920]
### 代码片段
```golang
c, err := rocketmq.NewPushConsumer(
  consumer.WithGroupName("test-group"),
  consumer.WithNsResolver(primitive.NewPassthroughResolver([]string{"rmq-cn-123456.cn-shanghai.rmq.aliyuncs.com:8080"})),
  consumer.WithCredentials(primitive.Credentials{
	  AccessKey: "111",
	  SecretKey: "222",
  }),
)
```
### 运行报错:
```bash
init consumer error: new Namesrv failed.: IP addr error
```
### 版本信息
- RocketMQ 版本: 阿里云5.0
- 客户端版本: 2.1.1
- 操作系统: MacOS 12.5

### 现状
> 目前是使用ping 解析出ip后,再进行配置,例如`ping rmq-cn-123456.cn-shanghai.rmq.aliyuncs.com`得到`10.1.2.3.4`

**Comment by Ikepi** [comment]
hi, chen,  i think u can try this:
`c, err := rocketmq.NewPushConsumer(
  consumer.WithGroupName("test-group"),
  consumer.WithNsResolver(primitive.NewPassthroughResolver([]string{"http://rmq-cn-123456.cn-shanghai.rmq.aliyuncs.com:8080"})),
  consumer.WithCredentials(primitive.Credentials{
	  AccessKey: "111",
	  SecretKey: "222",
  }),
)`

**Comment by KilluaChen** [comment]
> hi, chen, i think u can try this: `c, err := rocketmq.NewPushConsumer( consumer.WithGroupName("test-group"), consumer.WithNsResolver(primitive.NewPassthroughResolver([]string{"http://rmq-cn-123456.cn-shanghai.rmq.aliyuncs.com:8080"})), consumer.WithCredentials(primitive.Credentials{ AccessKey: "111", SecretKey: "222", }), )`

Thanks, now it's working
