### ISSUE TITLE
使用阿里云RocketMQ时无法批量发送消息,报错:request code unsupported, code 320

### ISSUE THREAD

**Issue by KilluaChen** [apache/rocketmq-client-go#921]
### 代码片段
```golang
p, err := rocketmq.NewProducer(
	producer.WithNsResolver(primitive.NewPassthroughResolver([]string{"10.1.2.3.4:8080"})),
	producer.WithRetry(2),
	producer.WithCredentials(primitive.Credentials{
		AccessKey: "111",
		SecretKey: "222",
	}),
)
if err != nil {
	fmt.Println("init producer error: " + err.Error())
	os.Exit(0)
}
err = p.Start()
if err != nil {
	fmt.Printf("start producer error: %s", err.Error())
	os.Exit(1)
}
msg1 := primitive.NewMessage("debug-topic", []byte("msg1"))
msg2 := primitive.NewMessage("debug-topic", []byte("msg2"))
rst, err := p.SendSync(context.Background(), msg1, msg2)
if err != nil {
	fmt.Printf("SendSync error: %s", err.Error())
	os.Exit(1)
}
fmt.Println(rst)
```
### 运行报错:
```bash
SendSync error: request code unsupported, code 320
```
### 版本信息
- RocketMQ 版本: 阿里云5.0
- 客户端版本: 2.1.1
- 操作系统: MacOS 12.5

**Comment by hjianbo** [comment]
挖一下，补充更多的信息，当前这个时间(2026-08-27)阿里云的文档说明了 它托管的 v4.x 系列的 RocketMQ确实不支持批量：

<img width="1700" height="816" alt="Image" src="https://github.com/user-attachments/assets/1ccbc046-92ae-42dc-b407-2329d2ce6956" />
参考：https://help.aliyun.com/zh/apsaramq-for-rocketmq/cloud-message-queue-rocketmq-4-x-series/product-overview/limits
（这个我实测过，确实会报告 ` request code unsupported, code 320` 错误）

但 v5.x 系列是支持的：
<img width="883" height="221" alt="Image" src="https://github.com/user-attachments/assets/47231f31-f495-423a-bdc4-3938240e3fb6" />

参考：https://help.aliyun.com/zh/apsaramq-for-rocketmq/cloud-message-queue-rocketmq-5-x-series/support/other-questions#qfAl5


确实挺坑的..
