### ISSUE TITLE
windows消费者广播模式下，消费者出现多进程访问文件异常

### ISSUE THREAD

**Issue by zc24** [apache/rocketmq-client-go#922]
![image](https://user-images.githubusercontent.com/61010755/191543367-a81ab889-f18c-41b4-a622-a6fb673c89c6.png)

**Comment by zc24** [comment]
![image](https://user-images.githubusercontent.com/61010755/191553665-4f5dd233-991a-4fae-be36-877eb85367eb.png)

**Comment by guyinyou** [comment]
great! can you put a pr to fix it
