### ISSUE TITLE
fetch offset of mq from broker error   

### ISSUE THREAD

**Issue by chowhugh** [apache/rocketmq-client-go#967]
ERRO[0400] fetch offset of mq from broker error   
 underlayError="broker response code: 22, remarks: Not found, V3_0_6_SNAPSHOT maybe this group consumer boot first"

**Comment by weinberggithub** [comment]
> 

did you fix it ?

**Comment by chowhugh** [comment]
> 

 not yet :(

**Comment by GrumpyCat0413** [comment]
did you fix it ?

**Comment by chowhugh** [comment]
> did you fix it ?
not

**Comment by ngyhd** [comment]
我也遇到了这个问题，主题启动新消费组，消费者无法正常消费，应该怎么解决呢？

**Comment by chowhugh** [comment]
>你解决了嘛

**Comment by GrumpyCat0413** [comment]
你需要更新他的client版本，直接更新master吧 更新到最新就行了，2.2版本不知道什么时候发布呢

**Comment by Larrouse2015** [comment]
使用master的版本 ，又报 the consumer group option validate fail  

> 你需要更新他的client版本，直接更新master吧 更新到最新就行了，2.2版本不知道什么时候发布呢

**Comment by chowhugh** [comment]
我目前解决了，首先我是用的是云服务商提供的RocketMQ，
在管理后台重置该消费组消费点位 就可以了。

**Comment by Larrouse2015** [comment]
我也解决了，确实用master版本就可以了

**Comment by francisoliverlee** [comment]
处理这个issue的pr已经关联， 大家了解下根本原因。 此issue这里关闭了，有需要随时重新打开
