### ISSUE TITLE
Difference with https://github.com/apache/rocketmq-clients/tree/master/golang

### ISSUE THREAD

**Issue by bilinxing** [apache/rocketmq-client-go#980]
What is the difference between  https://github.com/apache/rocketmq-clients/tree/master/golang , and which one should I use

**Comment by francisoliverlee** [comment]
### rocketmq-clients
> 这个是5.0的客户端，通过grpc协议访问rocketmq proxy的。 这个仓库是grpc的go语言客户端， 这个仓库中还包含java等其他语言，也是通过grpc访问rocketmq proxy的

### rocketmq-client-go
> 这个是4.X的客户端，通过原来的remoting协议访问4.x/5.x的rocketmq broker
