### ISSUE TITLE
Should unlock queue sending unlock(42) request to brokers where orderly consumer shutdown

### ISSUE THREAD

**Issue by qshuai** [apache/rocketmq-client-go#994]

**Comment by francisoliverlee** [comment]
从RocketMQ代码看， 是需要的。 方法调用链：https://github.com/apache/rocketmq/blob/abdf5dcb236db68dd285fdbba045086cb7a5b806/client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java#L108

![image](https://user-images.githubusercontent.com/5908412/218627916-7f2279ae-85a8-4a65-9491-d6f9f2ddf9d1.png)

![image](https://user-images.githubusercontent.com/5908412/218628024-fa0572c3-800f-483f-8943-1cb4ec6e1488.png)


![image](https://user-images.githubusercontent.com/5908412/218628175-3c6a4b72-2203-4cbb-a25a-1332afc92709.png)

**Comment by qshuai** [comment]
所以，go客户端需要在consumer关闭的时候主动向broker发起unlock请求，是这样的吗？

**Comment by francisoliverlee** [comment]
> 所以，go客户端需要在consumer关闭的时候主动向broker发起unlock请求，是这样的吗？

是的

**Comment by SchopenhauerZhang** [comment]
如果是正常退出可以考虑加上unlock；
比如
````
trylock()
defer unlock()
xxxx
````
但是如果是异常或者程序interrupt，broker会在到期后强制转移使用权；
````
if (lockEntry.isExpired()) {
                            lockEntry.setClientId(clientId);
                            lockEntry.setLastUpdateTimestamp(System.currentTimeMillis());
                            log.warn(
                                "tryLockBatch, message queue lock expired, I got it. Group: {} OldClientId: {} NewClientId: {} {}",
                                group,
                                oldClientId,
                                clientId,
                                mq);
                            lockedMqs.add(mq);
                            continue;
 }
````
isExpired后，会强制将锁给到此时的请求者，完成所有权转换。

**Comment by cserwen** [comment]
@qshuai @SchopenhauerZhang  Hi, I have fixed it, please help me to review.
